nspcc-dev/neofs-node

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Add simple Issue templates for a start.
Fixes #1

[#1] Add GitHub issue templates

---

cmd/neofs-node/grpc.go
cmd/neofs-node/main.go
cmd/neofs-node/object.go
pkg/network/transport/object/grpc/service.go
pkg/services/accounting/sign.go
pkg/services/container/sign.go
pkg/services/object/executor.go
pkg/services/object/sign.go
pkg/services/session/sign.go
pkg/services/util/sign.go

- Define `Object` service executors;
- Implement execution service;
- Implement signing/verifying service;
- Fix some errors in gRPC handlers.

Implement some Object service handlers

---

pkg/innerring/innerring.go
pkg/innerring/invoke/balance.go
pkg/innerring/invoke/netmap.go
pkg/innerring/processors/balance/handlers.go
pkg/innerring/processors/balance/process_assets.go
pkg/innerring/processors/container/handlers.go
pkg/innerring/processors/neofs/handlers.go
pkg/innerring/processors/neofs/process_assets.go
pkg/innerring/processors/neofs/process_config.go
pkg/innerring/processors/neofs/process_update.go
pkg/innerring/processors/neofs/processor.go
pkg/innerring/processors/netmap/handlers.go
pkg/morph/client/client.go
pkg/morph/event/neofs/bind.go
pkg/morph/event/neofs/bind_test.go
pkg/morph/event/neofs/config.go
pkg/morph/event/neofs/config_test.go
pkg/morph/event/neofs/ir_update.go
pkg/morph/event/neofs/ir_update_test.go
pkg/morph/event/neofs/unbind.go
pkg/morph/event/neofs/unbind_test.go

Inner ring must relay neofs global configuration and inner ring list from neofs contract to netmap contract.

Add neofs to netmap realy processors

---

go.mod
go.sum
pkg/policy/doc.go
pkg/policy/grammar.ebnf
pkg/policy/grammar.go
pkg/policy/query.go
pkg/policy/query_test.go

Implement library for parsing.

[#23] Support SQL-like queries for placement

---

pkg/policy/json.go
pkg/policy/json_test.go
pkg/policy/query.go

Support JSON marshalers for placement policy

---

pkg/services/object/head/service.go
pkg/services/object/search/query/v1/keys.go
pkg/services/object/search/query/v1/v1.go
pkg/services/object/search/service.go

Add steps for restoring object header from children.

Finalize object.Head service

---

pkg/services/object_manager/transformer/transformer.go

In previous implementations object size limiter left checksums of parent
object payload unset. This was caused by the closure that written calculated
checksums to the child object instead of parent one.
Construct payload checksum writers in separate function in order to prevent
closure bug.

object/transformer: Fix incorrect checksums of parent object

---

pkg/innerring/innerring.go
pkg/innerring/invoke/container.go

Fix for environments with ~7 inner ring nodes. #47 will be better solution one day.

Increase extra fee on container put invocation on inner rings

---

pkg/services/object/put/remote.go

object/put: Fix incorrect splited object streaming

---

pkg/services/object_manager/transformer/transformer.go

In previous implementation payload size limiter panicked in case of payload
emptiness. It was caused by the component waiting for at least one write of
a part of the payload.
Fix NPE occurrence with internal initialization after the WriteHeader call.

object/transformer: Fix NPE in case of empty payload

---

go.mod
go.sum
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/put/validation.go
pkg/services/object_manager/transformer/fmt.go

- implement object `FormatValidator` that checks checksums and signatures;
- use format validator in object.Put service (untrusted session);
- write session token to object bodies in object.Put service (trusted session).

Object format validation

---

pkg/services/object/acl/eacl/opts.go
pkg/services/object/acl/eacl/types.go
pkg/services/object/acl/eacl/v2/eacl_test.go
pkg/services/object/acl/eacl/v2/headers.go
pkg/services/object/acl/eacl/v2/localstore.go
pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/acl/eacl/v2/opts.go
pkg/services/object/acl/eacl/v2/xheader.go
pkg/services/object/acl/eacl/validator.go

object/eacl: Implement eACL validator

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/services/object/delete/service.go
pkg/services/object/put/prm.go
pkg/services/object/put/streamer.go
pkg/services/object/search/query/v1/v1.go

This pull request:
- fixes issue when tombstone was not broadcasted to container nodes,
- fixes issue when root object search returned tombstones,
- makes GC parameter available in config:
```yml
gc:
queuesize: 1000
duration:
sleep: 5s
timeout: 5s
```

Small GC improvements

---

cmd/neofs-ir/defaults.go
pkg/innerring/innerring.go
pkg/innerring/invoke/alphabet.go
pkg/innerring/invoke/neofs.go
pkg/innerring/invoke/netmap.go
pkg/innerring/processors/alphabet/handlers.go
pkg/innerring/processors/alphabet/process_emit.go
pkg/innerring/processors/alphabet/processor.go
pkg/innerring/state.go
pkg/innerring/timers/alphabet.go
pkg/innerring/timers/timers.go

This pull request adds support of alphabet contracts in neofs-ir. Nodes will call `Emit` method to produce utility token in sidechain and distribute it among inner ring nodes.

Call alphabet contracts periodically

---

pkg/policy/grammar.ebnf
pkg/policy/grammar.go
pkg/policy/query.go
pkg/policy/query_test.go

[#46] Make SELECT attribute optional

---

.github/workflows/dco.yml
.github/workflows/go.yml
Makefile

@im-kulikov test and build dependencies are now separate. =)
Also adding our standard GH Actions checks.

Improve build experience and add GH Actions for DCO, tests and linter

---

pkg/morph/client/client.go
pkg/morph/client/client_test.go

[#22] Support string type in stack parameter converter

---

cmd/neofs-cli/modules/object.go
go.sum

Implement everything except `Search`.

[#79] Implement object commands

---

cmd/neofs-cli/modules/container.go
go.mod
go.sum
pkg/innerring/processors/netmap/process_peers.go
pkg/morph/client/container/wrapper/container.go
pkg/morph/client/container/wrapper/eacl.go
pkg/morph/client/netmap/wrapper/netmap.go

Also update contains JSON converters for neofs-cli.

Update neofs-api-go with new protobuf API

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go
cmd/neofs-node/morph.go
cmd/neofs-node/netmap.go
cmd/neofs-node/object.go
cmd/neofs-node/worker.go
go.sum
pkg/services/object/head/distributed.go
pkg/services/object/head/remote.go
pkg/services/object/head/service.go
pkg/services/object_manager/placement/netmap.go
pkg/services/policer/check.go
pkg/services/policer/policer.go
pkg/services/policer/process.go
pkg/services/policer/queue.go

Implement Policer service

---

pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/search/query/v1/v1.go

Fix ID encoding in Search/eACL handlers

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go
cmd/neofs-node/object.go
pkg/core/netmap/state.go
pkg/morph/client/netmap/client.go
pkg/morph/client/netmap/epoch.go
pkg/morph/client/netmap/wrapper/epoch.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object_manager/transformer/fmt.go

Set CreationEpoch field value for new objects

---

cmd/neofs-node/object.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/classifier.go
pkg/services/object/acl/eacl/types.go
pkg/services/object/acl/eacl/validator.go
pkg/services/object/acl/opts.go

If bearer token is presented in the request then check if it is a valid one and then use it to process extended ACL checks.
There are several steps to check if bearer token is valid:
- it should be signed correctly,
- it should be signed by container owner,
- request sender should be specified in `token.OwnerID` field if it is not empty,
- it should have correct lifetime (check will be implemented later).

Process bearer token in ACL service

---

cmd/neofs-node/accounting.go
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/netmap.go
cmd/neofs-node/object.go
cmd/neofs-node/session.go
pkg/services/accounting/executor.go
pkg/services/accounting/response.go
pkg/services/accounting/sign.go
pkg/services/container/executor.go
pkg/services/container/response.go
pkg/services/container/sign.go
pkg/services/netmap/executor.go
pkg/services/netmap/response.go
pkg/services/netmap/sign.go
pkg/services/object/response.go
pkg/services/object/sign.go
pkg/services/session/executor.go
pkg/services/session/response.go
pkg/services/session/sign.go
pkg/services/util/response/client_stream.go
pkg/services/util/response/server_stream.go
pkg/services/util/response/service.go
pkg/services/util/response/unary.go
pkg/services/util/sign.go

Set values of response meta header

---

cmd/neofs-node/object.go
pkg/morph/client/netmap/client.go
pkg/morph/client/netmap/config.go
pkg/morph/client/netmap/wrapper/config.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go

Read max object size from sidechain

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/services/object/put/remote.go
pkg/services/policer/check.go
pkg/services/policer/policer.go
pkg/services/replicator/process.go
pkg/services/replicator/replicator.go
pkg/services/replicator/task.go

Implement Replicator service

---

go.mod
go.sum
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/get.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go

Implement bolt-based metabase that is going to be used in local object storage.

Implement primary metabase

---

pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/acl/eacl/validator.go
pkg/services/object/search/query/v1/keys.go
pkg/services/object/search/query/v1/v1.go
pkg/services/object/search/query/v1/v1_test.go

Use latest well-known filters

---

pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/delete_test.go
pkg/local_object_storage/metabase/get_test.go
pkg/local_object_storage/metabase/put_test.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/select_test.go

Metabase should return empty search result for a nonexistent object attribute.

metabase: Fix nonexistent attribute behavior

---

go.mod
go.sum
pkg/core/container/fmt.go
pkg/core/container/fmt_test.go
pkg/innerring/processors/container/process_container.go
pkg/services/container/morph/executor.go

Container sanity checks

---

cmd/neofs-cli/modules/object.go

Use base name as `FileName` attribute value

---

cmd/neofs-cli/modules/root.go

Set stdout as default output for CLI

---

pkg/innerring/invoke/netmap.go
pkg/innerring/processors/neofs/process_config.go
pkg/morph/event/neofs/config.go
pkg/morph/event/neofs/config_test.go

Use ID when invoking SetConfig method of netmap contract

---

pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/select_test.go
pkg/services/object/search/relation.go

Fix problems with split-object Get 

---

cmd/neofs-cli/modules/netmap.go

Implement netmap module in CLI

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/delete_test.go

Change handling of deleted objects

---

pkg/services/object/delete/service.go

object/delete: Add address from request body to tombstone content

---

pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go

Revert commit 0faa40e4 to increase the disk space consumed by the metabase in favor of the speed of index updates.

Revert "[#142] metabase: Store header value index in a tree leaf"

---

go.mod
go.sum
pkg/local_object_storage/blobstor/blobstor.go
pkg/local_object_storage/blobstor/compress.go
pkg/local_object_storage/blobstor/delete.go
pkg/local_object_storage/blobstor/fstree.go
pkg/local_object_storage/blobstor/get.go
pkg/local_object_storage/blobstor/getrange.go
pkg/local_object_storage/blobstor/put.go
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/engine.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/head.go
pkg/local_object_storage/engine/put.go
pkg/local_object_storage/engine/select.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/shard/delete.go
pkg/local_object_storage/shard/exists.go
pkg/local_object_storage/shard/get.go
pkg/local_object_storage/shard/id.go
pkg/local_object_storage/shard/put.go
pkg/local_object_storage/shard/select.go
pkg/local_object_storage/shard/shard.go
pkg/local_object_storage/shard/weight.go

Implement primary local storage engine based on shards with filesystem `BlobStor`.
- `WriteCache`;
- `GC`;
- `Blobovnicza`;
- work modes and fault injections.
-  write basic unit tests;
- integrate primary `StorageEngine` to NeoFS Node app.

Draft local storage engine

---

.github/workflows/go.yml
Makefile

Increase golangci-lint timeout

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/basic_helper.go
pkg/services/object/acl/classifier.go

Basic ACL check for inner ring requests

---

pkg/services/policer/queue.go

Limit policer object filter to phy objects only

---

cmd/neofs-cli/modules/object.go
go.mod
go.sum
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select_test.go

metabase: Add index by object ID

---

cmd/neofs-cli/modules/object.go

cmd/neofs-cli: Implement range command in Object section

---

cmd/neofs-node/object.go
pkg/services/object/delete/service.go
pkg/services/object/head/distributed.go
pkg/services/object/head/service.go
pkg/services/object/put/distributed.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/range/service.go
pkg/services/object/range/streamer.go
pkg/services/object/rangehash/distributed.go
pkg/services/object/rangehash/service.go
pkg/services/object/search/service.go
pkg/services/object/search/streamer.go
pkg/services/object/util/log.go

Object service debug errors

---

cmd/neofs-node/config.go

Use non-blocking worker pools for Object services

---

pkg/morph/client/container/wrapper/eacl.go
pkg/services/object/acl/eacl/validator.go

Do not fail eACL check on EACLNotFound

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/network/cache/client.go
pkg/services/object/head/remote.go
pkg/services/object/head/service.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/range/remote.go
pkg/services/object/range/service.go
pkg/services/object/range/streamer.go
pkg/services/object/rangehash/distributed.go
pkg/services/object/rangehash/remote.go
pkg/services/object/rangehash/service.go
pkg/services/object/search/remote.go
pkg/services/object/search/service.go
pkg/services/object/search/streamer.go

Configure dial timeouts in Object services

---

pkg/core/container/storage.go
pkg/morph/client/container/wrapper/eacl.go
pkg/services/object/acl/eacl/types.go
pkg/services/object/acl/eacl/validator.go

Replace ErrEACLNotFound to core library

---

pkg/services/object/acl/eacl/v2/object.go

Support object ID filter in eACL mechanism

---

cmd/neofs-cli/modules/container.go
go.mod
go.sum

cli/container: Use GetEACLWithSignature client method

---

go.mod
go.sum
pkg/local_object_storage/blobovnicza/blobovnicza.go
pkg/local_object_storage/blobovnicza/blobovnicza_test.go
pkg/local_object_storage/blobovnicza/control.go
pkg/local_object_storage/blobovnicza/delete.go
pkg/local_object_storage/blobovnicza/get.go
pkg/local_object_storage/blobovnicza/id.go
pkg/local_object_storage/blobovnicza/iterate.go
pkg/local_object_storage/blobovnicza/put.go
pkg/local_object_storage/blobovnicza/sizes.go
pkg/local_object_storage/blobovnicza/sizes_test.go
pkg/local_object_storage/blobstor/put.go

Implement Blobovnicza

---

pkg/local_object_storage/blobovnicza/iterate.go
pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/blobovnicza_test.go
pkg/local_object_storage/blobstor/blobstor.go
pkg/local_object_storage/blobstor/delete_small.go

Usage of blobovnicza's will be added later.

BlobStor: Implement blobovnicza tree

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go
pkg/core/object/errors.go
pkg/local_object_storage/blobovnicza/blobovnicza_test.go
pkg/local_object_storage/blobovnicza/delete.go
pkg/local_object_storage/blobovnicza/get.go
pkg/local_object_storage/blobovnicza/get_range.go
pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/blobovnicza_test.go
pkg/local_object_storage/blobstor/blobstor.go
pkg/local_object_storage/blobstor/control.go
pkg/local_object_storage/blobstor/delete_big.go
pkg/local_object_storage/blobstor/delete_small.go
pkg/local_object_storage/blobstor/get_big.go
pkg/local_object_storage/blobstor/get_range_small.go
pkg/local_object_storage/blobstor/get_small.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/head.go
pkg/local_object_storage/engine/put.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/get.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/get.go
pkg/local_object_storage/shard/put.go
pkg/local_object_storage/shard/shard.go

Blobovnicza integration

---

go.mod
go.sum
pkg/services/object/acl/eacl/v2/eacl_test.go
pkg/services/object/acl/eacl/validator.go

eacl: Get rid of deprecated methods usage

---

pkg/services/object_manager/placement/traverser.go
pkg/services/object_manager/placement/traverser_test.go

In previous implementation placement traverser processed incorrectly with
local placement build. Also entity incorrectly traversed the placement
vectors for fixed number read operations until success. The erroneous
behavior was due to the use of a vector number of successes instead of
a scalar number in these scenarios.

[#215] placement: Fix local and single-success placement traversal

---

pkg/local_object_storage/engine/select.go
pkg/local_object_storage/metabase/v2/containers.go
pkg/local_object_storage/metabase/v2/containers_test.go
pkg/local_object_storage/shard/list.go
pkg/local_object_storage/shard/list_test.go
pkg/services/policer/queue.go

Propose to add:
- `Containers` method to metabase which returns available `[]container.ID` 
- `List` method to shard which makes empty select with each `container.ID` from `metabase.Containers()` and returns `[]object.ID`
- `List` method to storage engine which goes through shards and runs `shard.List()` method and then returns `[]object.ID`. It also has `limit` parameter.

Fetching objects from storage engine for policer

---

pkg/local_object_storage/metabase/cleanup.go
pkg/local_object_storage/metabase/containers_test.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/delete_test.go
pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/exists_test.go
pkg/local_object_storage/metabase/get.go
pkg/local_object_storage/metabase/get_test.go
pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/inhume_test.go
pkg/local_object_storage/metabase/movable.go
pkg/local_object_storage/metabase/movable_test.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/put_test.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/select_test.go
pkg/local_object_storage/metabase/small.go
pkg/local_object_storage/metabase/small_test.go
pkg/local_object_storage/shard/delete.go
pkg/local_object_storage/shard/exists.go
pkg/local_object_storage/shard/get.go
pkg/local_object_storage/shard/head.go
pkg/local_object_storage/shard/inhume.go
pkg/local_object_storage/shard/list.go
pkg/local_object_storage/shard/move.go
pkg/local_object_storage/shard/put.go
pkg/local_object_storage/shard/select.go

All parameters and resulting values of all metabase operations are
structured in new types. The most popular scenarios for using operations are
moved to auxiliary functions.

metabase: Structure parameters and results of all operations

---

cmd/neofs-cli/modules/object.go

cmd/cli: Support raw flag in object GET/HEAD/RANGE commands

---

pkg/local_object_storage/blobstor/blobovnicza.go

Deadlock occurs when `getActivate` function opens new blobovnicza and that invokes evict in LRU cache of open blobovniczas. `getActivate` makes `activeMtx.Lock()` and then cache evict makes `activeMtx.RLock()` and deadlock happens.
Fix contains two steps:
- add separate mutex to open blobovniczas (1),
- split single Lock outside of `updateAndGet` (2).
As for the (1) `bbolt.Open()` locks when it tries to open the same file from two threads. So separate mutex will prevent that.
As for the (2) `updateAndGet` function contains from two parts. At first it checks if required blobovnicza is ready and it returns it. In this case we can use the simple RLock. But then there is an option when we should open new blobovnicza and update map of active blobovniczas.
In this case we call `openBlobovnicza` …

Fix deadlock on concurrent evict and open new blobovnicza

---

cmd/neofs-cli/modules/object.go

Closes #228 
Example of head output for link object:
```
$ ./bin/neofs-cli -c config.yml object head --cid 6iRZ55DXFbXBCBXkZCpRrm14jFVdRDHdyoim1CCorFPp --oid 7BrkU4TB5r82r6KnhBgCTdgVhUJsyvM7V6AQyxXZDdma
ID: 7BrkU4TB5r82r6KnhBgCTdgVhUJsyvM7V6AQyxXZDdma
CID: 6iRZ55DXFbXBCBXkZCpRrm14jFVdRDHdyoim1CCorFPp
Owner: NTrezR3C4X8aMLVg7vozt5wguyNfFhwuFx
CreatedAt: 4
Size: 0
HomoHash: 00000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
Checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Type: regular
Attributes:
Split ID: 66fa9126-f830-40ae-9eec-56c314166324
Split ParentID: GqFndhzqPEgmFW2Q3L5ftT2Wie3eYg223ga2dkKvUj2N
Split ChildID: E4YvDA7wU1tZfzUhmarnaj5dncG97mixGPDX7d3iRxnm
Split ChildID: …
```

Print split header values in Head command

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/eacl/v2/headers.go
pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/acl/eacl/v2/opts.go
pkg/services/object/acl/eacl/v2/xheader.go

[#247] object/eacl: Process object address from request

---

go.sum
pkg/services/object/get/assemble.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object_manager/transformer/fmt.go
pkg/services/object_manager/transformer/transformer.go
pkg/services/object_manager/transformer/types.go

Fix parent double header transformation

---

cmd/neofs-cli/modules/storagegroup.go
go.mod
go.sum
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/services/object/util/chain.go
pkg/services/object_manager/storagegroup/collect.go
pkg/services/object_manager/storagegroup/search.go

Implement storage group commands in CLI

---

cmd/neofs-ir/defaults.go
go.mod
go.sum
pkg/innerring/innerring.go
pkg/innerring/invoke/enhanced.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/audit/processor.go
pkg/innerring/processors/audit/scheduler.go
pkg/innerring/rpc.go
pkg/innerring/state.go
pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/exec.go
pkg/services/audit/report.go
pkg/services/audit/task.go
pkg/services/audit/taskmanager/listen.go
pkg/services/audit/taskmanager/manager.go
pkg/services/audit/taskmanager/push.go
pkg/services/audit/taskmanager/reset.go

Compose, push and execute audit tasks

---

pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/exec.go
pkg/services/audit/auditor/pop.go
pkg/services/audit/auditor/por.go
pkg/services/audit/auditor/util.go
pkg/services/audit/report.go

services/audit: Implement PoP check

---

cmd/neofs-ir/defaults.go
pkg/innerring/innerring.go
pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/exec.go
pkg/services/audit/auditor/pdp.go
pkg/services/audit/auditor/pop.go
pkg/services/audit/report.go
pkg/services/audit/taskmanager/listen.go
pkg/services/audit/taskmanager/manager.go

services/audit: Implement PDP check 

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go

cli: Support request X-Headers

---

cmd/neofs-ir/defaults.go
pkg/innerring/innerring.go
pkg/innerring/processors/audit/process.go
pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/pop.go
pkg/services/audit/auditor/por.go
pkg/services/audit/report.go
pkg/services/audit/taskmanager/listen.go
pkg/services/audit/taskmanager/manager.go

Run PoR SG checks in parallel

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/classifier.go
pkg/services/object/acl/eacl/v2/opts.go
pkg/services/object/acl/eacl/v2/xheader.go
pkg/services/object/put/remote.go
pkg/services/object/put/streamer.go
pkg/services/object/util/prm.go

Fix validation of X-headers in eACL check

---

cmd/neofs-cli/modules/object.go
pkg/services/object/get/get.go
pkg/services/object/get/prm.go
pkg/services/object/get/util.go
pkg/services/object/get/v2/util.go
pkg/util/salt.go
pkg/util/salt_test.go

Process salt from GetRangeHashRequest

---

cmd/neofs-node/main.go
cmd/neofs-node/netmap.go
pkg/morph/client/netmap/update_state.go
pkg/morph/client/netmap/wrapper/update_state.go
pkg/morph/event/netmap/update_peer.go
pkg/morph/event/netmap/update_peer_test.go

Transfer node to offline state on application shutdown

---

pkg/morph/client/netmap/client.go
pkg/morph/client/netmap/netmap.go
pkg/morph/client/netmap/wrapper/netmap.go

morph/netmap: Implement getting network map snapshot by epoch

---

cmd/neofs-cli/modules/control.go
cmd/neofs-node/control.go
cmd/neofs-node/netmap.go
pkg/services/control/server/server.go
pkg/services/control/server/set_netmap_status.go
pkg/services/control/service.go
pkg/services/control/service.pb.go
pkg/services/control/service.proto
pkg/services/control/service_test.go

Implement UpdateState in Control API

---

Dockerfile.storage-testnet
config/testnet/README.md
config/testnet/config.yml
config/testnet/docker-compose.yml
go.mod
go.sum

Add configuration for storage node testnet deployment

---

cmd/neofs-node/config.go
cmd/neofs-node/control.go
cmd/neofs-node/grpc.go
cmd/neofs-node/main.go
pkg/local_object_storage/blobovnicza/blobovnicza.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/shard/control.go

Testnet application fixes

---

Dockerfile.cli
Dockerfile.ir
Dockerfile.storage
Dockerfile.storage-testnet

It is much easier to debug and solve issues in-place with interactive command line.

Add shell in docker images

---

go.mod
go.sum

Update neofs-api-go to latest master

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go
pkg/services/netmap/executor.go

Fix node information returned by storage node

---

pkg/local_object_storage/engine/container.go
pkg/local_object_storage/metabase/cleanup.go
pkg/local_object_storage/metabase/containers.go
pkg/local_object_storage/metabase/containers_test.go
pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/shard/container.go
pkg/local_object_storage/shard/list.go

Estimate container sizes in storage engine

---

config/testnet/README.md

config/testnet: Add debug section in readme

---

CHANGELOG.md
go.mod
go.sum

neofs-api-go update closes #347

Update neofs-api-go version and changelog

---

pkg/innerring/audit.go
pkg/innerring/innerring.go
pkg/innerring/invoke/enhanced.go
pkg/innerring/processors/netmap/process_epoch.go
pkg/innerring/processors/netmap/processor.go
pkg/innerring/processors/settlement/audit/calculate.go
pkg/innerring/processors/settlement/audit/calculator.go
pkg/innerring/processors/settlement/audit/prm.go
pkg/innerring/processors/settlement/audit/util.go
pkg/innerring/processors/settlement/calls.go
pkg/innerring/processors/settlement/deps.go
pkg/innerring/processors/settlement/events.go
pkg/innerring/processors/settlement/handlers.go
pkg/innerring/processors/settlement/opts.go
pkg/innerring/processors/settlement/processor.go
pkg/innerring/rpc.go
pkg/innerring/timers/block_test.go
pkg/innerring/util.go
pkg/morph/client/balance/client.go
pkg/morph/client/balance/transfer.go
pkg/morph/client/balance/wrapper/transfer.go

Calculate audit settlements on new epoch event

---

cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/morph.go
go.mod
go.sum
pkg/morph/client/container/client.go
pkg/morph/client/container/load.go
pkg/morph/client/container/wrapper/container.go
pkg/network/transport/container/grpc/service.go
pkg/services/container/announcement/load/controller/calls.go
pkg/services/container/announcement/load/controller/calls_test.go
pkg/services/container/announcement/load/controller/controller.go
pkg/services/container/announcement/load/controller/deps.go
pkg/services/container/announcement/load/controller/opts.go
pkg/services/container/announcement/load/controller/util.go
pkg/services/container/announcement/load/route/calls.go
pkg/services/container/announcement/load/route/deps.go
pkg/services/container/announcement/load/route/opts.go
pkg/services/container/announcement/load/route/placement/builder.go
pkg/services/container/announcement/load/route/placement/calls.go
pkg/services/container/announcement/load/route/placement/deps.go
pkg/services/container/announcement/load/route/router.go
pkg/services/container/announcement/load/route/util.go
pkg/services/container/announcement/load/storage/storage.go
pkg/services/container/announcement/load/storage/storage_test.go
pkg/services/container/executor.go
pkg/services/container/response.go
pkg/services/container/sign.go

Synchronize container volume information once per epoch

---

go.mod
go.sum
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/select_test.go

metabase: Support new match types

---

cmd/neofs-ir/defaults.go
pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/innerring/processors/settlement/basic/collect.go
pkg/innerring/processors/settlement/basic/context.go
pkg/innerring/processors/settlement/basic/distribute.go
pkg/innerring/processors/settlement/basic/distribute_test.go
pkg/innerring/processors/settlement/basic/util.go
pkg/innerring/processors/settlement/calls.go
pkg/innerring/settlement.go

Distribute basic income

---

cmd/neofs-cli/modules/util.go
go.mod
go.sum
pkg/util/locode/column/coordinates.go
pkg/util/locode/column/country.go
pkg/util/locode/column/location.go
pkg/util/locode/column/util.go
pkg/util/locode/db/airports/calls.go
pkg/util/locode/db/airports/db.go
pkg/util/locode/db/airports/opts.go
pkg/util/locode/db/boltdb/calls.go
pkg/util/locode/db/boltdb/db.go
pkg/util/locode/db/boltdb/opts.go
pkg/util/locode/db/continent.go
pkg/util/locode/db/continents/geojson/calls.go
pkg/util/locode/db/continents/geojson/db.go
pkg/util/locode/db/continents/geojson/opts.go
pkg/util/locode/db/country.go
pkg/util/locode/db/db.go
pkg/util/locode/db/location.go
pkg/util/locode/db/point.go
pkg/util/locode/db/record.go
pkg/util/locode/record.go
pkg/util/locode/table/csv/calls.go
pkg/util/locode/table/csv/opts.go
pkg/util/locode/table/csv/table.go

Overtake data from UN/Locode tables to local databases

---

cmd/neofs-cli/modules/storagegroup.go

Update storagegroup commands in CLI

---

cmd/neofs-cli/modules/util.go
cmd/neofs-ir/defaults.go
cmd/neofs-node/attributes.go
pkg/innerring/innerring.go
pkg/innerring/locode.go
pkg/innerring/processors/netmap/nodevalidation/locode/calls.go
pkg/innerring/processors/netmap/nodevalidation/locode/deps.go
pkg/innerring/processors/netmap/nodevalidation/locode/util.go
pkg/innerring/processors/netmap/nodevalidation/locode/validator.go
pkg/innerring/processors/netmap/process_peers.go
pkg/innerring/processors/netmap/processor.go
pkg/util/locode/db/boltdb/calls.go
pkg/util/locode/db/boltdb/opts.go
pkg/util/locode/db/record.go

Validate LOCODE attributes of candidates to the network map

---

pkg/util/locode/column/coordinates.go
pkg/util/locode/db/airports/calls.go
pkg/util/locode/db/airports/db.go

Fixes around LOCODE database generation

---

pkg/util/locode/table/csv/calls.go
pkg/util/locode/table/csv/table.go

[#316] locode/csv: Scan subdivision csv-table into memory

---

cmd/neofs-cli/modules/object.go
cmd/neofs-node/attributes.go
go.mod
go.sum
pkg/innerring/processors/netmap/nodevalidation/locode/calls.go
pkg/innerring/processors/netmap/nodevalidation/locode/validator.go

New query language of search filters in Object CLI

---

pkg/innerring/processors/netmap/process_peers.go

Sort node info attributes and use updated binary for smart contract invocation.

Fix node info approval in netmap processor

---

pkg/local_object_storage/engine/inhume.go

storage engine: Inhume object in one shard

---

pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/services/object/put/service.go

[#368] object: Reject expired objects

---

pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/delete_test.go

[#219] metabase: Count parent references in Delete operation

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/metabase/graveyard.go
pkg/local_object_storage/metabase/graveyard_test.go
pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/iterators.go
pkg/local_object_storage/metabase/iterators_test.go
pkg/local_object_storage/metabase/movable.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/inhume.go
pkg/local_object_storage/shard/inhume_test.go
pkg/local_object_storage/shard/shard.go
pkg/services/object/delete/exec.go
pkg/services/object/delete/local.go
pkg/services/object/delete/service.go

GC: Implement API

---

pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/inhume_test.go

metabase: Do not add tombstone-on-tombstone records to graveyard

---

pkg/core/object/fmt.go
pkg/core/object/fmt_test.go

According to nspcc-dev/neofs-api#136 tombstone body should store the same attribute as in object header. If they are different, then check is failed with `errTombstoneExpiration`.

Check expiration epoch in tombstone body and header

---

cmd/neofs-cli/modules/netmap.go
cmd/neofs-node/netmap.go
go.mod
go.sum
pkg/morph/client/client.go
pkg/network/transport/netmap/grpc/service.go
pkg/services/netmap/executor.go
pkg/services/netmap/response.go
pkg/services/netmap/sign.go

Blocked by https://github.com/nspcc-dev/neofs-api-go/pull/259

node: Serve NetworkInfo RPC

---

cmd/neofs-cli/modules/object.go

CLI: Add dedicated flag to indicate object expiration

---

cmd/neofs-ir/defaults.go
pkg/innerring/alphabet.go
pkg/innerring/innerring.go
pkg/innerring/processors/alphabet/process_emit.go
pkg/innerring/processors/alphabet/processor.go
pkg/innerring/processors/audit/processor.go
pkg/innerring/state.go

IR: Support dynamic number of alphabetic contracts 

---

cmd/neofs-ir/defaults.go
pkg/innerring/innerring.go

IR: Support working with sidechain only

---

cmd/neofs-node/object.go
pkg/local_object_storage/engine/inhume.go
pkg/services/policer/check.go
pkg/services/policer/policer.go

Remove redundant copies of the object

---

pkg/innerring/processors/netmap/nodevalidation/locode/calls.go

IR: Make UN-LOCODE attribute of the network map candidate optional

---

cmd/neofs-node/cache.go
cmd/neofs-node/container.go
cmd/neofs-node/morph.go
cmd/neofs-node/object.go
pkg/services/object/acl/eacl/opts.go

node: Cache info from morph RPC

---

cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/innerring/innerring.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/audit/processor.go
pkg/innerring/rpc.go
pkg/network/cache/client.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go
pkg/services/object/head/remote.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/search/exec.go
pkg/services/object/search/search_test.go
pkg/services/object/search/service.go
pkg/services/object/search/util.go
pkg/services/object/util/prm.go

Close #422.
Remove both private key and options from cache interface.

Cache clients by address only

---

go.mod
go.sum
pkg/morph/client/client.go

Should be compatible with NEO3 testnet.

Update neo-go to pre-released v0.94.0 version

---

pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/get_test.go
pkg/local_object_storage/metabase/put.go

Fix the storage of payloads in the metabase

---

cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/main.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation.go
pkg/innerring/rpc.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go
pkg/services/object/head/remote.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/search/exec.go
pkg/services/object/search/search_test.go
pkg/services/object/search/service.go
pkg/services/object/search/util.go
pkg/services/reputation/local/controller/calls.go
pkg/services/reputation/local/controller/controller.go
pkg/services/reputation/local/controller/deps.go
pkg/services/reputation/local/controller/opts.go
pkg/services/reputation/local/controller/util.go
pkg/services/reputation/local/storage/calls.go
pkg/services/reputation/local/storage/storage.go
pkg/services/reputation/peer.go
pkg/services/reputation/trust.go

Implement local trust controller

---

pkg/innerring/processors/governance/list.go
pkg/innerring/processors/governance/list_test.go
pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/notary.go

This PR is a part of new governance model adoption. It contains morph/client methods to get chain data as list of roles from designate contract and committee list.

Prepare governance update

---

config/testnet/README.md
config/testnet/config.yml
config/testnet/docker-compose.yml

Update config for N3 testnet RC1

---

pkg/morph/client/notary.go

Related to #437.
There is no custom error in the NeoGo repository that describes the error that should be ignored. Up to HTTP call. There is no even any string constant that can be used for searching: every word in the error message appears in the `fmt.Errorf("...%w..."...)` form in NeoGo code. Therefore, it seems that there is no better solution(without changing NeoGo codebase) than just searching for "already on chain" substring of error message.

bug/ignore "already on chain" errors of notary contract

---

pkg/morph/client/notary.go

Throw panic if notary methods are not initialized

---

README.md

Add supported platforms list to README
Closes: #458

[#458] Add supported platforms list to README

---

pkg/local_object_storage/blobstor/blobovnicza.go

Fix #481.
Evicting from cache requires closing blobovnicza which
in turn needs to lock `activeMtx`. This lock is not needed on
every addition, but our LRU library doesn't return evicted keys.
In future we may consider switching to other implementation.

[#481] blobstor: use simplelru.LRU cache

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go
go.sum

Close #466 .
NEP-2 is contains WIF encrypted with password.
NEP-6 is format used for neo-go wallets.

cli: support NEP-2 and NEP-6 key formats

---

pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/morph/client/client.go
pkg/morph/client/notary.go

[#457] innerring: wait until notary tx persists on chain

---

pkg/innerring/innerring.go

Alphabet nodes synchronize list of alphabet keys from main chain
`NeoFSAlphabet` role once per epoch. This can lead to a wrong behavior in
single chain deployment (`without_mainnet` config parameter). Alphabet node
in single chain environment will try to get NeoFSAlphabet role from main
chain client, but it'll get result from side chain instead. Side chain
stores list of all inner ring nodes in this role. Therefore it is possible
that alphabet nodes will try to appoint inner ring nodes as alphabet nodes,
which is not correct.
Fix incorrect behavior with disabling of synchronization of alphabet keys in
sidechain-only mode.

ir: Do not sync alphabet keys in sidechain-only configuration

---

cmd/neofs-node/reputation.go
cmd/neofs-node/reputation/intermediate/calculator.go
pkg/morph/client/netmap/config.go
pkg/morph/client/netmap/wrapper/config.go
pkg/morph/client/util.go

Feature/add reading EigenTrust `alpha` from global cfg

---

cmd/neofs-ir/defaults.go
cmd/neofs-ir/main.go
cmd/neofs-node/config.go
cmd/neofs-node/main.go
go.sum
misc/build.go
pkg/util/logger/logger.go

Simplify logger's configuration

---

cmd/neofs-node/config.go
cmd/neofs-node/morph.go

node: Connect to main chain

---

pkg/services/object/get/exec.go
pkg/services/object/get/get.go
pkg/services/object/get/util.go

object/hash: Fix NPE during request forwarding

---

pkg/morph/client/neofsid/client.go
pkg/morph/client/neofsid/keys.go
pkg/morph/client/neofsid/wrapper/client.go
pkg/morph/client/neofsid/wrapper/keys.go

Implement NeoFS ID contract client

---

cmd/neofs-cli/modules/container.go

CLI: Rename basic ACL keywords

---

pkg/services/object/get/exec.go
pkg/services/object/get/get.go
pkg/services/object/get/util.go
pkg/services/object/search/util.go

object: Fix NPEs during request forwarding

---

pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/inhume_test.go

Fix incorrect inhuming of root objects

---

CHANGELOG.md
go.mod
go.sum

Release v0.20.0 - Dolsando (돌산도, 突山島)

---

pkg/innerring/innerring.go
pkg/innerring/processors/governance/handlers.go
pkg/innerring/processors/governance/processor.go
pkg/morph/client/client.go
pkg/morph/event/rolemanagement/designate.go
pkg/morph/event/rolemanagement/designate_test.go

[#502] innerring: synchronize validators on mainnet alphabet update

---

cmd/neofs-node/container.go
pkg/innerring/innerring.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/container/common.go
pkg/innerring/processors/container/handlers.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/container/process_eacl.go
pkg/innerring/processors/container/processor.go
pkg/morph/client/balance/transfer.go
pkg/morph/client/client.go
pkg/morph/client/client_test.go
pkg/morph/client/container/eacl_set.go
pkg/morph/client/container/estimations.go
pkg/morph/client/container/put.go
pkg/morph/client/container/wrapper/container.go
pkg/morph/client/container/wrapper/eacl.go
pkg/morph/client/container/wrapper/estimations.go
pkg/morph/client/container/wrapper/wrapper.go
pkg/morph/client/neofsid/wrapper/client.go
pkg/morph/client/reputation/put.go
pkg/morph/client/static.go
pkg/morph/event/container/eacl.go
pkg/morph/event/container/eacl_test.go
pkg/morph/event/container/put.go
pkg/morph/event/container/put_test.go
pkg/services/container/morph/executor.go

IR: Process set eACL notifications

---

pkg/innerring/processors/container/process_eacl.go
pkg/morph/client/container/eacl.go
pkg/morph/client/container/eacl_set.go
pkg/morph/client/container/get.go
pkg/morph/client/container/wrapper/eacl.go
pkg/morph/event/container/eacl.go
pkg/morph/event/container/eacl_test.go

Adopt Get, GetEACL and SetEACL to new contract

---

cmd/neofs-node/object.go
go.mod
go.sum
pkg/core/container/delete.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/container/process_eacl.go
pkg/morph/client/container/delete.go
pkg/morph/client/container/eacl.go
pkg/morph/client/container/eacl_set.go
pkg/morph/client/container/get.go
pkg/morph/client/container/put.go
pkg/morph/client/container/wrapper/container.go
pkg/morph/client/container/wrapper/eacl.go
pkg/morph/event/container/delete.go
pkg/morph/event/container/delete_test.go
pkg/morph/event/container/eacl.go
pkg/morph/event/container/eacl_test.go
pkg/morph/event/container/put.go
pkg/morph/event/container/put_test.go
pkg/services/container/executor.go
pkg/services/container/morph/executor.go

Support container sessions

---

cmd/neofs-ir/main.go
cmd/neofs-node/grpc.go
cmd/neofs-node/main.go
cmd/neofs-node/netmap.go

Fatal error details

---

cmd/neofs-cli/modules/container.go
go.mod
go.sum
pkg/innerring/processors/container/common.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/container/process_eacl.go

Finalize container sessions 

---

cmd/neofs-node/object.go
pkg/services/object/put/distributed.go
pkg/services/object/put/prm.go
pkg/services/object/put/streamer.go
pkg/services/object/put/v2/service.go
pkg/services/object/put/v2/streamer.go
pkg/services/object/put/v2/util.go

Make session optional when sending complete objects

---

pkg/innerring/innerring.go
pkg/innerring/processors/neofs/handlers.go
pkg/innerring/processors/neofs/process_bind.go
pkg/innerring/processors/neofs/processor.go
pkg/morph/client/neofs/bind.go
pkg/morph/client/neofs/client.go
pkg/morph/client/neofs/wrapper/bind.go
pkg/morph/client/neofs/wrapper/client.go
pkg/morph/client/neofsid/addrm_keys.go
pkg/morph/client/neofsid/client.go
pkg/morph/client/neofsid/wrapper/client.go
pkg/morph/client/neofsid/wrapper/keys.go
pkg/morph/event/neofs/bind.go
pkg/morph/event/neofs/bind_test.go
pkg/morph/event/neofs/unbind.go
pkg/morph/event/neofs/unbind_test.go

Process Bind/Unbind events of NeoFS contract in IR

---

go.mod
go.sum

Update NEO Go library to v0.95.1

---

config/testnet/config.yml
go.sum
pkg/innerring/innerring.go
pkg/innerring/processors/netmap/processor.go

Update tesnet config file

---

go.mod
go.sum
pkg/innerring/innerring.go
pkg/innerring/processors/container/common.go
pkg/innerring/processors/container/processor.go

ir/container: Verify session token lifetime

---

pkg/services/object/put/streamer.go
pkg/services/object/put/v2/streamer.go
pkg/services/object/put/validation.go

object/put: Check payload size of the finished objects

---

pkg/innerring/processors/netmap/nodevalidation/locode/calls.go
pkg/innerring/processors/netmap/nodevalidation/locode/calls_test.go

Check UN/LOCODE-derived attributes

---

config/testnet/config.yml
config/testnet/docker-compose.yml
config/testnet/prometheus.yml

Signed-off-by: anastasia prasolova <anastasia@nspcc.ru>

#551 vmagent in neofs-storage testnet image

---

cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/control.go
cmd/neofs-node/netmap.go

Fix re-bootstrap failures

---

go.mod
go.sum

Update neo-go to v0.95.2

---

cmd/neofs-cli/modules/root.go

Extend CLI key options

---

config/testnet/README.md
config/testnet/docker-compose.yml
config/testnet/node_config.env
config/testnet/prometheus.yml

Closes https://github.com/nspcc-dev/nspcc-infra/issues/88
Signed-off-by: Sergio Nemirowski <sergio@nspcc.ru>

[#88] Add relabel for instance

---

cmd/neofs-node/reputation.go
pkg/innerring/innerring.go
pkg/innerring/processors/reputation/handlers.go
pkg/innerring/processors/reputation/process_put.go
pkg/innerring/processors/reputation/processor.go
pkg/services/reputation/common/managers.go

Feature/add reputation sanity check in IR

---

pkg/local_object_storage/writecache/delete.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/persist.go
pkg/local_object_storage/writecache/storage.go

I think we should reduce memory size when objects removed from memory?

local_object_storage/shard/writecache: maintain size 

---

pkg/core/object/fmt.go
pkg/core/object/fmt_test.go

Validate object attributes

---

cmd/neofs-cli/modules/root.go

what's the abnormal behavior?
i stored my `config.yaml` to `$HOME/.config/neofs-cli`, but can't load to `neofs-cli`

Fixed an abnormal behavior about the default config file

---

Dockerfile.aio
Makefile

We need All-In-One Docker image to simplify NeoFS deployment in development and testing environments.

Add All-In-One NeoFS Docker image

---

cmd/neofs-ir/main.go
cmd/neofs-node/main.go

Feature/add `--version` flag to SN

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/storagegroup.go
cmd/neofs-cli/modules/util.go

fix/return non-zero codes on errors

---

cmd/neofs-cli/modules/container.go

Feature/Support binary eACL format

---

Dockerfile.adm
Dockerfile.aio
Dockerfile.dirty-adm
Makefile

Add Docker images for neofs-adm

---

cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/generate_test.go
go.mod

neofs-adm: generate alphabet wallets

---

pkg/innerring/innerring.go

Fix/Do not require `proxy` hash in notary disabled mode

---

cmd/neofs-cli/modules/root.go

Feat/Make `--address` flag optional

---

go.mod
go.sum

Update Neo-Go library to v0.96.0

---

pkg/innerring/innerring.go

Fix/Do not require `processing` hash in main notary disabled mode

---

cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_roles.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
cmd/neofs-adm/internal/modules/morph/n3client.go
go.sum

Close #687 .
Tested with 4, 7, 15 nodes, recovering from arbitrary stage mostly works: it is possible that command will be executed and interrupted multiple times in sub-block interval. This can cost us some GAS (which goes back to committee though) but doesn't affect the outcome of the initialization.

neofs-adm: transfer funds and set roles

---

cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

Close #728.
Set default config parameters including epoch duration.

neofs-adm: initialize netmap contract

---

cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/initialize.go

Close #686 .
Allow to force epoch change. This is independent from #721 .

neofs-adm: implement `morph force-new-epoch`

---

cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/root.go

neofs-adm: generate storage wallets

---

cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_roles.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go

Validate before the actual work, less code, error checks.

neofs-adm: simplify code

---

go.mod
go.sum
pkg/network/tls.go

Refactor/Delete multiaddr TLS implementation

---

cmd/neofs-node/grpc.go
cmd/neofs-node/main.go
cmd/neofs-node/metrics.go
cmd/neofs-node/pprof.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/shard.go

Related to #451. Could not reproduce the issue locally, but this PR would stop GC in the same situation(not sure if it helps to restart node).
Added debug logs on shutdown.

Fix/Stop GC work on `Shard`'s `Close()`

---

pkg/network/cache/multi.go

@alexvanin  Please have a look.

[#737] network/cache: handle request cancelled in multiclient

---

cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/root.go
cmd/neofs-adm/internal/modules/morph/update.go

[#748] neofs-adm: allow to update contracts

---

cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/dump.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/root.go

neofs-adm: allow to transfer containers between networks

---

CHANGELOG.md
cmd/neofs-node/morph.go
cmd/neofs-node/netmap.go
pkg/innerring/innerring.go
pkg/innerring/processors/governance/processor.go
pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/morph/client/notary.go

Implement and use morph multi-client

---

CHANGELOG.md
pkg/local_object_storage/shard/head.go
pkg/local_object_storage/writecache/get.go
pkg/local_object_storage/writecache/writecache.go

Closes #762.
Easiest to implement working solution is presented. I left some notes for future optimizations.

Read object headers from write cache

---

pkg/innerring/processors/neofs/handlers.go

Print tx IDs in LE on Withdraw and Deposit events

---

cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/storagegroup.go

Fix/Wrap CLI errors with context information

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/acl_test.go

object/acl: Fit sticky bit specification

---

cmd/neofs-node/cache.go
cmd/neofs-node/container.go
pkg/services/container/morph/executor.go

Closes #803 
Before patch:
```
$ time ./022-ListPutListContainer.sh
real    0m18.764s
user    0m14.818s
sys     0m4.909s
```
After patch:
```
$ time ./022-ListPutListContainer.sh 
real    0m2.196s
user    0m0.157s
sys     0m0.051s
```

Invalidate container cache records on update

---

cmd/neofs-node/reputation.go
pkg/innerring/innerring.go
pkg/innerring/processors/reputation/handlers.go
pkg/innerring/processors/reputation/process_put.go
pkg/innerring/processors/reputation/processor.go
pkg/morph/client/reputation/client.go
pkg/morph/client/reputation/wrapper/wrapper.go
pkg/morph/event/reputation/put.go
pkg/morph/event/reputation/put_notary.go

Support notary notifications in reputation processor

---

pkg/morph/event/notary_preparator_test.go
pkg/morph/event/opcodes.go

Adds unit test for `NotaryPreparator`

Test/Improve Notary event testing

---

pkg/innerring/processors/container/common.go

Similar to https://github.com/nspcc-dev/neofs-api-go/pull/340.

ir/container: Prevent potential NPE in key conversion

---

pkg/innerring/processors/netmap/handlers.go
pkg/innerring/processors/netmap/process_cleanup.go
pkg/innerring/processors/netmap/process_peers.go
pkg/innerring/state.go
pkg/morph/client/notary.go
pkg/morph/client/static.go
pkg/morph/event/netmap/add_peer.go
pkg/morph/event/netmap/add_peer_notary.go

Fix/Add random nonce to SN's notary request

---

pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/get.go
pkg/local_object_storage/metabase/get_test.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/list.go
pkg/local_object_storage/shard/list_test.go
pkg/services/policer/check.go

Fix erroneous deletion marks

---

pkg/innerring/innerring.go

IR: Support multiple notification endpoints

---

cmd/neofs-node/config.go
cmd/neofs-node/morph.go

Don't connect storage node to main chain

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This comments out user notes that should not go to the reports.
Signed-off-by: Sergio Nemirowski <sergio@nspcc.ru>

fix #856, update issue templates

---

cmd/neofs-lens/internal/commands/list/list.go
cmd/neofs-lens/internal/common.go
cmd/neofs-lens/root.go
pkg/local_object_storage/blobovnicza/blobovnicza.go
pkg/local_object_storage/blobovnicza/control.go
pkg/local_object_storage/blobovnicza/delete.go
pkg/local_object_storage/blobovnicza/iterate.go
pkg/local_object_storage/blobovnicza/put.go
pkg/local_object_storage/writecache/iterate.go
pkg/local_object_storage/writecache/storage.go
pkg/local_object_storage/writecache/util.go

Relates to #791.
I named the app `neofs-lens` for brevity and similarity in meaning.

Initial looking glass

---

cmd/neofs-adm/internal/modules/morph/download.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
go.mod
go.sum

Fix #733 .
Also allow to use unpacked tar.gz archive.

neofs-adm: support downloading contracts from github

---

cmd/neofs-node/reputation/intermediate/remote.go
cmd/neofs-node/reputation/internal/client/client.go
cmd/neofs-node/reputation/internal/client/doc.go
cmd/neofs-node/reputation/local/remote.go
pkg/services/object/delete/exec.go
pkg/services/object/delete/prm.go
pkg/services/object/get/exec.go
pkg/services/object/get/prm.go
pkg/services/object/get/util.go
pkg/services/object/get/v2/util.go
pkg/services/object/head/prm.go
pkg/services/object/head/remote.go
pkg/services/object/internal/client/client.go
pkg/services/object/internal/client/doc.go
pkg/services/object/put/remote.go
pkg/services/object/search/exec.go
pkg/services/object/search/prm.go
pkg/services/object/search/util.go
pkg/services/object/util/prm.go

Similar to https://github.com/nspcc-dev/neofs-node/pull/946.

node: Refactor usage of NeoFS API client

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/acl_test.go
pkg/services/object/delete/exec.go
pkg/services/object/delete/service.go

Set node's owner ID as tombstone owner

---

pkg/innerring/processors/netmap/cleanup_table.go
pkg/innerring/processors/netmap/cleanup_table_test.go
pkg/innerring/processors/netmap/process_peers.go

ir/netmap: Call AddPeer method if existing candidate was updated

---

cmd/neofs-node/config.go
cmd/neofs-node/config/engine/config.go
cmd/neofs-node/config/engine/config_test.go
config/example/node.yaml

Do not require shard config in relay mode

---

pkg/innerring/processors/netmap/process_peers.go
pkg/morph/client/client.go

Ignore non-HALT netmap.AddPeer notary invocations 

---

pkg/morph/client/notary.go
pkg/morph/event/notary_preparator.go
pkg/morph/event/notary_preparator_test.go

Add invoker witness as the third witness. Required for netmap methods checks (https://github.com/nspcc-dev/neofs-contract/issues/154). 
Blocked by neo-go release, and https://github.com/nspcc-dev/neofs-node/pull/971

Combined notary witnesses

---

pkg/innerring/innerring.go
pkg/innerring/processors/netmap/nodevalidation/subnet/calls.go
pkg/innerring/processors/netmap/nodevalidation/subnet/validator.go
pkg/morph/client/subnet/node.go
pkg/services/object/get/v2/util.go

Closes #974. Merge after https://github.com/nspcc-dev/neofs-node/pull/986.

Feat/Check node subnet entrance by IR on `AddPeer`

---

cmd/neofs-cli/modules/container.go

Feat/Add `subnet` flag to `container create`

---

pkg/innerring/processors/netmap/processor.go

Parse and listen `RemoveNode` event in IR

---

pkg/morph/client/container/wrapper/container.go

Waiting for nspcc-dev/neofs-contract#143 to settle to update contract version (it is better to import error message).

morph/client: update morph container wrapper

---

cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-adm/internal/modules/morph/notary.go
cmd/neofs-adm/internal/modules/morph/root.go

neofs-adm: implement `deposit-notary` command

---

cmd/neofs-node/main.go

Signed-off-by: Sergio Nemirowski <sergio@nspcc.ru>

fix neofs-node usage message

---

cmd/neofs-adm/internal/modules/morph/dump.go

It doesn't work currently after subnet contract was added.
Testing done with `bin/neofs-adm morph dump-hashes -r http://morph1.fs.neo.org:40332`.
It is currently twice slower than before (1s vs 2s), but we can optimize this after release (combine all invocations in one script and wrap in `TRY` block).
Example output:
```
nns         (unknown):  7061fbd31562664b58f422c3dee4acfd70dba8af
alphabet 0  (v0.12.1):  2392438eb31100857c0f161c66791872b249aa13
alphabet 1  (v0.12.1):  83ef4226d5d6519ca9c99a5de13b1b5ca223a6ad
alphabet 2  (v0.12.1):  6250927beaa9aa5a00171379dcb7187b0c91d17d
alphabet 3  (v0.12.1):  1d6a2519ba41a139b2ced1bfd5013938271a7578
alphabet 4  (v0.12.1):  b65fc7a3c31cf57a90d7eb1c0e9909e4ca69133c
alphabet 5  (v0.12.1):  f95b6ff8cd3b027c9911c18115518ad8c5d2f591
alphabet 6 …
```

neofs-adm: skip missing entries in `dump-hashes`

---

pkg/innerring/processors/netmap/process_peers.go

Call Register method on peer approval

---

cmd/neofs-adm/internal/modules/morph/dump.go

neofs-adm: Print NNS contract version

---

cmd/neofs-adm/internal/modules/morph/subnet.go

Also, delete `-a` (`--contract`) flag.
Closes #1017.

Feat/Fetch `subnet` SH from NNS

---

cmd/neofs-ir/defaults.go
pkg/innerring/config/fee.go
pkg/innerring/innerring.go
pkg/morph/client/container/wrapper/wrapper.go
pkg/morph/client/fee.go
pkg/morph/client/fee_test.go
pkg/morph/client/static.go

Customize fee for named container registration

---

pkg/local_object_storage/blobovnicza/control.go
pkg/local_object_storage/blobovnicza/sizes.go

Fix estimation of `Blobovnicza` volume

---

cmd/neofs-adm/internal/modules/morph/subnet.go

Feat/Change private key to wallet in `subnet` command flags

---

cmd/neofs-adm/internal/modules/morph/subnet.go

Closes #1020 
This PR modifies `key` flag, therefore it conflicts with #1018. So it makes sense to wait for it first.

Do not ask credentials in `morph subnet get` command

---

cmd/neofs-adm/docs/subnetwork-creation.md
cmd/neofs-adm/docs/subnetwork-usage.md

Docs/Add subnetwork creation HOWTO

---

cmd/neofs-cli/modules/root.go

Add shorthand for `generate-key` flag

---

cmd/neofs-adm/internal/modules/autocomplete.go
cmd/neofs-adm/internal/modules/root.go

Support autocomplete in neofs-adm

---

pkg/local_object_storage/writecache/storage.go

writecache: Fix db counter decrement

---

cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-node/config/morph/config.go
cmd/neofs-node/config/morph/config_test.go
cmd/neofs-node/morph.go
config/example/node.env
config/example/node.json
config/example/node.yaml
pkg/morph/client/constructor.go
pkg/morph/client/multi.go

Feat/Limit `neo-go` connections per host

---

CHANGELOG.md
config/testnet/docker-compose.yml

Release v0.27.1

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go
pkg/innerring/innerring.go
pkg/innerring/state.go
pkg/metrics/innerring.go
pkg/metrics/metrics.go

[#1054] innerring: add prometheus epoch metric

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

neofs-adm: deploy proxy contract without arguments

---

cmd/neofs-cli/modules/control.go
pkg/local_object_storage/shard/delete.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/info.go
pkg/local_object_storage/shard/inhume.go
pkg/local_object_storage/shard/mode.go
pkg/local_object_storage/shard/move.go
pkg/local_object_storage/shard/put.go
pkg/local_object_storage/shard/shard.go
pkg/services/control/convert.go
pkg/services/control/rpc.go
pkg/services/control/server/list_shards.go
pkg/services/control/server/set_shard_mode.go
pkg/services/control/service.go
pkg/services/control/service.pb.go
pkg/services/control/service.proto
pkg/services/control/service_grpc.pb.go
pkg/services/control/service_test.go

Feat/Add shard mode setter command to CLI

---

cmd/neofs-node/object.go

Fix missing response status at ACL problems

---

pkg/morph/client/balance/wrapper/transfer.go

morph/balance: Fix transfer to

---

pkg/services/object/transport_splitter.go

Fix missing body and meta header on empty Object.Search results

---

pkg/innerring/innerring.go

Read IR list from role management contract w/o mainchain

---

cmd/neofs-adm/internal/modules/morph/subnet.go
cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/object.go
cmd/neofs-node/config.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/core/container/fmt_test.go
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/innerring/processors/container/common.go
pkg/innerring/processors/settlement/audit/calculate.go
pkg/innerring/processors/settlement/basic/context.go
pkg/innerring/settlement.go
pkg/innerring/subnet.go
pkg/local_object_storage/engine/engine_test.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/shard/shard_test.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/classifier.go

Related to https://github.com/nspcc-dev/neofs-sdk-go/issues/103.

Upd/Adopt new SDK's `owner.ID` API

---

go.mod
go.sum

go.mod: update tzhash version

---

cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/key_test.go
cmd/neofs-cli/modules/root.go

Fix 1, 2, 5 points from #1103 .

Allow to set `neofs-cli` password in config

---

cmd/neofs-cli/modules/accounting.go
pkg/services/accounting/morph/executor.go

Balance precisions

---

pkg/innerring/processors/container/process_eacl.go

ir/container: Fix check of `SetEACL` operation

---

pkg/local_object_storage/blobovnicza/control.go
pkg/local_object_storage/blobovnicza/iterate.go
pkg/local_object_storage/blobovnicza/sizes.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/mode.go
pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/head/remote.go
pkg/services/object/util/prm.go

Fix some TODOs

---

cmd/neofs-adm/internal/modules/config/config.go
cmd/neofs-adm/internal/modules/config/config_test.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-cli/modules/key_test.go
cmd/neofs-node/config.go
pkg/local_object_storage/blobovnicza/control.go
pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/blobstor.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/fstree/fstree_test.go
pkg/local_object_storage/engine/engine_test.go
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/shard/control_test.go
pkg/local_object_storage/shard/shard_test.go
pkg/local_object_storage/writecache/util.go
pkg/util/locode/db/boltdb/calls.go
pkg/util/state/storage_test.go

*: Use `path/filepath` package when working with files

---

cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/group.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go

Related #749 .
Morph client will be changed in another PR.
Testing is done on this branch https://github.com/fyrchik/neofs-adm-tests/tree/force-new-epoch

neofs-adm: include neofs contracts in a custom group

---

cmd/neofs-cli/modules/object.go

With SDK update, `neofs-cli` has to manually set expiration value of session token. Token duration should not be quite long, because session tokens are issued on each `neofs-cli` invocation. In this PR it is hardcoded to 10 epochs.
I don't think it is worth to provide interface to set manual session token duration, because session tokens are not reusable in `neofs-cli`.

neofs-cli: Set expiration in session token based on network info

---

config/example/cli.yaml

example: Add neofs-cli config example

---

pkg/innerring/internal/client/client.go

[#1180] ir/internal: Fix audit range hash type

---

pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/notary.go

[#1151] morph/client: cache notary transaction heights

---

cmd/neofs-cli/internal/client/client.go
cmd/neofs-cli/internal/client/prm.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/services/object/internal/client/client.go

Upgrade NeoFS SDK Go

---

cmd/neofs-node/attributes.go
cmd/neofs-node/config.go

neofs-node: Make some parameters optional in relay mode

---

pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/put.go

metabase: log PUT / DELETE operations

---

go.mod

*: Tidy go.mod

---

pkg/services/object/delete/exec.go
pkg/services/object/delete/local.go
pkg/services/object/delete/service.go
pkg/services/object/delete/util.go
pkg/services/object/put/distributed.go
pkg/services/object/put/prm.go
pkg/services/object/put/streamer.go

* inspired by https://github.com/nspcc-dev/neofs-node/issues/1174

Refactor tombstone broadcast

---

pkg/services/replicator/process.go

replicator: Improve error log

---

cmd/neofs-adm/internal/modules/morph/subnet.go

Added `-w` flag to `neofs-adm morph subnet node` commands.

Fix/Add `wallet` flag to adm's subnet command

---

cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/dump.go
cmd/neofs-cli/modules/restore.go
cmd/neofs-cli/modules/root.go
cmd/neofs-node/config.go
go.mod
go.sum
pkg/core/client/client.go
pkg/innerring/rpc.go
pkg/network/cache/client.go
pkg/network/cache/multi.go
pkg/services/object/get/v2/util.go
pkg/services/object/put/v2/streamer.go
pkg/services/object/search/v2/util.go

Ready for review. I will merge after integration tests.

Update new SDK Client interface

---

go.mod
go.sum

go.mod: update dependencies

---

pkg/local_object_storage/metabase/put.go

Fix metabase put logging

---

cmd/neofs-cli/modules/object.go

Closes #1229.
Not sure if the current description in CLI is full enough.

Feat/Add object notification to CLI

---

pkg/network/address.go

Depends on SDK update (#1231 ? )

network: reuse URI parsing function from api-go

---

CHANGELOG.md
go.mod
go.sum

Waiting:
- https://github.com/nspcc-dev/neofs-node/pull/1238
- https://github.com/nspcc-dev/neofs-node/pull/1210
- https://github.com/nspcc-dev/neofs-node/pull/1222

Release v0.28.0-rc.1

---

cmd/neofs-cli/modules/object.go

neofs-cli: marshal split info in JSON

---

cmd/neofs-cli/modules/object.go

neofs-cli: fix split info marshaling

---

CHANGELOG.md

Tested object put/get on https://github.com/nspcc-dev/neofs-dev-env/pull/166

Release candidate v0.28.0-rc.2

---

pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/compress.go
pkg/local_object_storage/blobstor/iterate_test.go

blobstor: cleanup zstd encoders/decoders

---

cmd/neofs-cli/modules/acl/extended/create.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/token/create.go
cmd/neofs-cli/modules/token/root.go

Add a command for bearer token creation

---

pkg/local_object_storage/blobovnicza/put.go
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/index_test.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/put_test.go

1. Functions in `Update` and `Batch` should be idempotent.
2. Reduce allocations count during index processing in `Put` / `Delete`.

Fix blobovnicza, metabase index improvements

---

cmd/neofs-cli/internal/client/client.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/storagegroup.go
pkg/innerring/internal/client/client.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/audit/processor.go
pkg/morph/client/netmap/netmap.go
pkg/morph/client/netmap/netmap_test.go
pkg/services/audit/auditor/por.go
pkg/services/audit/task.go
pkg/util/attributes/parser.go

Convert some of the remaining slices to use raw struct

---

pkg/services/audit/auditor/pdp.go

services/audit: randomize the order of PDP checks

---

pkg/services/object/acl/v2/service.go

services/acl: check session token expiration epoch

---

pkg/local_object_storage/writecache/get.go

Close #1149 .
Also, remove optimization comments:
1. Having to maintain an execute the same logic for headers as for
objects is quite inefficient, as it increases memory footprint.
2. Unmarshaling object is a cheap operation if data slice is in memory.
3. For unmarshaling header-only, I think we need SDK support.

[#1149] writecache: Prevent corruption in `Head`

---

pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/morph/client/nns.go

Improve morph client cache

---

cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_roles.go
cmd/neofs-adm/internal/modules/morph/notary.go
cmd/neofs-adm/internal/modules/morph/policy.go

If a transaction has been persisted with FAULT state, we should return this information to user.

neofs-adm: check persisted tx status

---

cmd/neofs-adm/internal/modules/config/config.go
cmd/neofs-adm/internal/modules/config/config_test.go

[#1295] neofs-adm: Add contract group wallet to config template

---

pkg/morph/event/listener.go

Depends on #1291.
After `Listen` has raw receiver and calls `listen` which has pointer
receiver, leading to ineffectual assign to `started` field.
Always use `listener` by pointer, to avoid similar bugs.

morph/event: make listener methods use pointer receiver

---

.docker/Dockerfile.adm
.docker/Dockerfile.cli
.docker/Dockerfile.ir
.docker/Dockerfile.storage
.docker/Dockerfile.storage-testnet
.github/workflows/go.yml
Makefile
cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/storagecfg/root.go
cmd/neofs-cli/modules/acl/extended/create.go
cmd/neofs-cli/modules/key_test.go
cmd/neofs-lens/internal/commands/inspect/inspect.go
go.mod
pkg/local_object_storage/shard/dump_test.go

[#1250] go.mod: Bump supported go version to 1.17

---

CHANGELOG.md
go.mod

Release v0.28.0-rc.3

---

cmd/neofs-adm/internal/modules/storagecfg/config.go

neofs-adm: Update storage config template

---

pkg/morph/client/netmap/config.go

morph/netmap: fix panic during parameter parsing

---

cmd/neofs-cli/internal/client/sdk.go
cmd/neofs-cli/internal/key/nep2.go
cmd/neofs-cli/internal/key/raw.go
cmd/neofs-cli/internal/key/wallet.go
cmd/neofs-cli/modules/bearer/create.go
cmd/neofs-cli/modules/bearer/root.go
cmd/neofs-cli/modules/key_test.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/session/create.go
cmd/neofs-cli/modules/session/root.go

Close #1216 .
Todo: more testing.

Allow to reuse token in neofs-cli

---

cmd/neofs-cli/modules/key_test.go
pkg/core/object/fmt_test.go
pkg/local_object_storage/blobovnicza/iterate_test.go
pkg/local_object_storage/blobstor/fstree/fstree_test.go
pkg/local_object_storage/blobstor/iterate_test.go
pkg/local_object_storage/engine/error_test.go
pkg/local_object_storage/shard/dump_test.go
pkg/services/object/search/search_test.go

*: use `require.ErrorIs` where possible

---

CHANGELOG.md
cmd/neofs-cli/internal/client/sdk.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/root.go
cmd/neofs-node/config/node/config_test.go
pkg/network/address.go
pkg/network/address_test.go
pkg/network/cache/multi.go
pkg/network/group.go
pkg/network/tls.go
pkg/network/tls_test.go

* closes #1351 
* relates #1341
* relates #1354

cli: Fix connection scheme loss during endpoint parsing

---

CHANGELOG.md

Release v0.28.1

---

CHANGELOG.md
cmd/neofs-ir/defaults.go
config/example/README.md
config/example/ir.env
config/example/ir.yaml

Add config examples for inner ring application

---

cmd/neofs-adm/internal/modules/storagecfg/root.go

Signed-off-by: tasselsd <tasselsd@outlook.com>

[#1363] Use network package to parse and verify the announced address.

---

cmd/neofs-adm/README.md
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/root.go

Usage:
```
▶ ./bin/neofs-adm morph dump-config -r http://192.168.130.90:30333                                                                             
AuditFee:                    10000 (int)
BasicIncomeRate:             100000000 (int)
ContainerAliasFee:           500 (int)
ContainerFee:                1000 (int)
EigenTrustAlpha:             0.1 (str)
EigenTrustIterations:        4 (int)
EpochDuration:               240 (int)
HomomorphicHashingDisabled:  true (bool)
InnerRingCandidateFee:       10000000000 (int)
MaxObjectSize:               67108864 (int)
WithdrawFee:                 100000000 (int)
```
```
▶ ./bin/neofs-adm morph set-config -c config.yaml HomomorphicHashingDisabled=false AuditFee=1001 EigenTrustAlpha=0.9 test=test
Password for az wallet > 
Password for contract …
```

Feat/Set config via `adm`

---

pkg/innerring/state.go
pkg/morph/client/audit/list_results.go
pkg/morph/client/balance/balanceOf.go
pkg/morph/client/balance/burn.go
pkg/morph/client/balance/lock.go
pkg/morph/client/balance/mint.go
pkg/morph/client/balance/transfer.go
pkg/morph/client/client.go
pkg/morph/client/client_test.go
pkg/morph/client/container/estimations.go
pkg/morph/client/container/load.go
pkg/morph/client/neofs/cheque.go
pkg/morph/client/netmap/netmap.go
pkg/morph/client/netmap/new_epoch.go
pkg/morph/client/netmap/snapshot.go
pkg/morph/client/reputation/get.go
pkg/morph/client/reputation/list.go
pkg/morph/client/reputation/put.go

Close #1141 , blocked by nspcc-dev/neo-go#2413.

Add some morph client conversion types

---

pkg/services/tree/service.go

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

[#1404] Fix node id in GetSubTree response

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/eacl/v2/eacl_test.go
pkg/services/object/acl/eacl/v2/headers.go
pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/acl/eacl/v2/opts.go
pkg/services/object/acl/eacl/v2/xheader.go

Handle errors during header gathering for eACL check

---

cmd/neofs-cli/internal/client/sdk.go
cmd/neofs-cli/internal/common/exit.go
cmd/neofs-cli/internal/commonflags/flags.go
cmd/neofs-cli/internal/key/raw.go
cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/accounting/balance.go
cmd/neofs-cli/modules/accounting/root.go
cmd/neofs-cli/modules/bearer/create.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/dump.go
cmd/neofs-cli/modules/key_test.go
cmd/neofs-cli/modules/lock.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/restore.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/session/create.go
cmd/neofs-cli/modules/storagegroup.go
cmd/neofs-cli/modules/util.go

neofs-cli: Move shared components into internal packages and module out accounting command 

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/root.go
cmd/neofs-cli/modules/root.go
cmd/neofs-lens/root.go
go.mod
pkg/util/gendoc/gendoc.go

[#1396] cmd: Allow to autogenerate documentation for all commands

---

pkg/morph/client/nns.go

Currently there is an error about `Array/ByteString` conversion.

Fix innerring signer scope

---

pkg/local_object_storage/engine/tree.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/interface.go
pkg/local_object_storage/shard/tree.go
pkg/services/tree/service.go
pkg/services/tree/service.pb.go
pkg/services/tree/service.proto
pkg/services/tree/service_grpc.pb.go
pkg/services/tree/service_neofs.pb.go
pkg/services/tree/sync.go

Related #1329.
Depends on #1362 .

Allow to synchronize tree log

---

pkg/local_object_storage/engine/error_test.go
pkg/local_object_storage/engine/tree_test.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/types.go

1. `Update` -> `Batch`.
2. Build index on `FileName` attribute.

Optimize pilorama

---

pkg/services/tree/options.go
pkg/services/tree/redirect.go
pkg/services/tree/replicator.go
pkg/services/tree/service.go

Close #1401 .
Depends on #1431 .

services/tree: Retransmit queries to container nodes

---

go.mod
go.sum

Update neofs-contract in the tree service

---

pkg/util/config/crypto.go

[#1467] pkg/util: Allow to load default account from a wallet

---

pkg/services/tree/cache.go
pkg/services/tree/container.go
pkg/services/tree/replicator.go
pkg/services/tree/service.go
pkg/services/tree/sync.go

Also fix connections to TLS addresses.

services/tree: Cache the list of container nodes

---

cmd/neofs-node/control.go
cmd/neofs-node/main.go
cmd/neofs-node/metrics.go
cmd/neofs-node/morph.go
cmd/neofs-node/pprof.go

Feat/Log service initialization/boot up

---

pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/init.go
pkg/local_object_storage/writecache/iterate.go
pkg/local_object_storage/writecache/persist.go
pkg/local_object_storage/writecache/writecache.go
pkg/services/policer/check.go

1. Allow to fetch data on demand in `FSTree`.
2. Initialize flush mark LRU cache on startup.

Some writecache fixes

---

cmd/neofs-cli/modules/bearer/create.go
go.mod
go.sum
pkg/innerring/processors/container/common.go
pkg/services/object/acl/acl.go

Upgrade NeoFS SDK Go to v1.0.0-rc.4 and NeoFS API Go to v2.12.2

---

CHANGELOG.md

Release v0.28.2

---

cmd/neofs-cli/internal/common/verbose.go
cmd/neofs-cli/internal/commonflags/api.go
cmd/neofs-cli/internal/commonflags/session.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/lock.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/session/util.go
cmd/neofs-cli/modules/storagegroup.go

Move more common functions to a separate packages

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

neofs-adm: include alphabet contracts to the group

---

CHANGELOG.md
cmd/neofs-adm/docs/subnetwork-creation.md
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-adm/internal/modules/morph/subnet.go

Fix/Do not use morph client in `neofs-adm`

---

cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/group.go
go.mod
go.sum

neofs-adm: pretty print wallets

---

pkg/morph/client/multi.go

Feat/Log WS client closing error

---

CHANGELOG.md

CHANGELOG.md: fill unreleased section

---

pkg/services/object_manager/placement/netmap.go

In case we have lots of objects in a single container,
`GetContainerNodes` invoked indirectly by a policer can be seen in
pprof.

placement: cache container nodes

---

cmd/neofs-node/cache.go
cmd/neofs-node/object.go

[#1515] services/object: cache `MaxObjectSize`

---

pkg/services/tree/cache.go

Close #1456.
In case node is down or failing for some reason, we can expect `Dial` to
fail. In case we actively try to replicate and `Dial` always takes 2
seconds, replication-related channels quickly become full. That affects
latency of all other write operations.

[#1456] services/tree: wait some time before reconnecting after failure

---

cmd/neofs-node/cache.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/local_object_storage/engine/select.go
pkg/morph/client/audit/put_result.go
pkg/morph/client/container/client.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/eacl/v2/eacl_test.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/util.go
pkg/services/object/acl/v2/util_test.go
pkg/services/object/util/prm.go

The remaining two are fixed in #1470.

*: Fix linter warnings

---

cmd/neofs-adm/internal/modules/morph/subnet.go
cmd/neofs-cli/modules/container.go
cmd/neofs-node/netmap.go
go.mod
go.sum
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/netmap/nodevalidation/subnet/calls.go
pkg/innerring/processors/netmap/process_peers.go
pkg/innerring/processors/subnet/put.go
pkg/innerring/processors/subnet/put_test.go
pkg/innerring/subnet.go
pkg/morph/event/subnet/remove_node_test.go

* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/210

Upgrade NeoFS SDK Go with changed `subnet` package

---

pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/control_test.go

[#1502] shard: Process locks on metabase refill

---

cmd/neofs-adm/internal/modules/config/root.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/remove_node.go
cmd/neofs-adm/internal/modules/morph/root.go
cmd/neofs-adm/internal/modules/morph/subnet.go
cmd/neofs-adm/internal/modules/storagecfg/root.go
pkg/util/gendoc/gendoc.go

Also fix cached group signer account.

neofs-adm: allow to remove nodes from the netmap

---

config/mainnet/config.yml
config/testnet/config.yml

[#1053] config: Remove notification endpoints

---

README.md

[#1438] README.md: add build instructions

---

go.mod
go.sum
pkg/services/policer/check.go

Upgrade SDK to rc.5

---

CHANGELOG.md

@fyrchik @carpawell pls notify me if we need to add smth else into CHANGELOG.

Release v0.29.0

---

pkg/services/object/acl/acl.go

Close #1266.
If the container ID is not nil and not equal to the container ID in the
request, consider bearer token invalid.
See also nspcc-dev/neofs-api#207.

[#1266] object/acl: Check bearer token container ID

---

CHANGELOG.md
cmd/neofs-cli/modules/storagegroup/put.go
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go

Closes https://github.com/nspcc-dev/neofs-api/issues/218. But should be merged only after API release.

Feat/Unique SG members

---

cmd/neofs-adm/internal/modules/config/config.go
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/root.go
cmd/neofs-cli/internal/client/client.go
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/storagegroup/put.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/container/processor.go
pkg/morph/client/netmap/config.go
pkg/services/audit/auditor/por.go
pkg/services/object/put/prm.go
pkg/services/object/put/streamer.go
pkg/services/object_manager/storagegroup/collect.go
pkg/services/object_manager/transformer/transformer.go

Cherry pick work done by @carpawell from the experimental branch with minor corrections.

Allow to disable homomorphic hashing

---

CHANGELOG.md
cmd/neofs-cli/modules/container/delete.go

neofs-cli: check if container contains locks before removal

---

pkg/local_object_storage/engine/control.go

Shard is intended to be used as a separate failure domain,
which usually resides on a separate disk. Thus, sequential
initialization is bound by IO and this change speeds up thing a bit.

engine: Parallelize shard initialization

---

cmd/neofs-adm/internal/modules/morph/balance.go
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/storagecfg/root.go
go.mod
go.sum
pkg/morph/client/client.go
pkg/morph/client/nns.go
pkg/util/config/crypto.go

go.mod: Update neo-go

---

config/example/node.yaml
docs/storage-node-configuration.md

docs: describe storage node configuration

---

cmd/neofs-cli/modules/object/lock.go

neofs-cli: print lock object ID

---

pkg/services/tree/signature.go

services/tree: Fix error message

---

pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/get_range_big.go
pkg/local_object_storage/shard/get.go
pkg/local_object_storage/shard/range.go
pkg/local_object_storage/shard/range_test.go

shard: fix `GetRange` for objects stored in the write-cache

---

cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/morph/root.go

Close #1629 .
Tests are here https://github.com/nspcc-dev/neofs-adm-tests/blob/main/test.deploy-single.sh

Allow to deploy arbitrary contracts with neofs-adm

---

CHANGELOG.md
cmd/neofs-cli/modules/acl/extended/create.go

Fix/CID setting in eACL creation

---

cmd/neofs-cli/modules/container/list.go
cmd/neofs-cli/modules/container/list_objects.go
cmd/neofs-cli/modules/session/util.go

cli: Print attributes in container and object listing commands

---

CHANGELOG.md
cmd/neofs-cli/modules/object/put.go

[#1296] cli: "ID" -> "OID"

---

go.mod
go.sum

go.mod: Update neofs-sdk-go

---

cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
go.mod
go.sum

Allow to register custom TLD in `morph deploy`

---

cmd/neofs-cli/internal/client/client.go
go.mod
go.sum
pkg/innerring/internal/client/client.go
pkg/services/object/internal/client/client.go

go.mod: Update API and SDK

---

pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/meta_test.go

Close #1698.
It was actually closed by the latest SDK update, just add some tests here.

[#1698] pilorama: Add a test for the empty FileName

---

pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza.go
pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza_test.go
pkg/local_object_storage/blobstor/blobovniczatree/control.go

Close #1691 .
Maybe related to #1733 .

Fix active blobovnicza caching

---

cmd/neofs-adm/internal/modules/storagecfg/root.go
pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/morph/client/notary.go
pkg/morph/client/util.go

Related to #1711.
Notary actors will be added after the https://github.com/nspcc-dev/neo-go/pull/2665.

Upd/Adopt neo-go 0.99.2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

.github: Add label checklist to templates

---

cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go

neofs-adm: remove TXT records before update

---

pkg/services/tree/cache.go
pkg/services/tree/replicator.go

[#1759] services/tree: Make logs more descriptive

---

cmd/neofs-adm/internal/modules/morph/balance.go
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/dump_hashes.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_roles.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-adm/internal/modules/morph/notary.go
cmd/neofs-adm/internal/modules/morph/policy.go
cmd/neofs-adm/internal/modules/morph/remove_node.go
cmd/neofs-adm/internal/modules/morph/subnet.go

Upd/Adm with neo-go `v0.99.2`

---

go.mod
go.sum

[#1782] go.mod: Update neofs-sdk-go

---

cmd/neofs-node/control.go
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/head.go
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/lock_test.go
pkg/local_object_storage/engine/put.go
pkg/local_object_storage/engine/range.go
pkg/local_object_storage/engine/select.go
pkg/services/control/server/gc.go
pkg/services/control/server/server.go

Remove batches from `engine.Delete`

---

cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-adm/internal/modules/morph/notary.go

neofs-adm: use `ValidUntilBlock` to wait for tx persist

---

pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza_test.go

There was a problem with testing in #1810, just add a test here.

[#1810] blobovniczatree: Add a test for blobovnicva usage

---

CHANGELOG.md
cmd/neofs-node/object.go
pkg/services/object/delete/delete.go
pkg/services/object/delete/service.go
pkg/services/object/delete/v2/service.go

[#1697] services/object: Return proper error if session token is missing

---

pkg/local_object_storage/blobstor/blobovniczatree/put.go
pkg/local_object_storage/blobstor/common/errors.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/put.go
pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/put.go

Increase error counter on put errors

---

CHANGELOG.md
cmd/neofs-cli/internal/commonflags/flags.go
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/container/delete.go

Validate policy before container creation

Add force option to the command `container create`

---

pkg/services/policer/check.go

[#1847] services/policer: Provide container ID in logs

---

CHANGELOG.md
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/delete_test.go

[#1829] engine: Delete split objects properly

---

CHANGELOG.md
pkg/services/tree/service.go
pkg/services/tree/service.pb.go
pkg/services/tree/service.proto
pkg/services/tree/service_grpc.pb.go
pkg/services/tree/service_neofs.pb.go
pkg/services/tree/types.pb.go

Add healthcheck method to the Tree service

---

CHANGELOG.md
pkg/services/control/server/evacuate.go
pkg/services/policer/check.go
pkg/services/policer/check_test.go
pkg/services/replicator/process.go

node/policer: Consider nodes under MAINTENANCE as problem 

---

.github/workflows/config-update.yml

.github: Add an action monitoring config updates

---

CHANGELOG.md
cmd/neofs-cli/modules/object/get.go
cmd/neofs-cli/modules/object/hash.go
cmd/neofs-cli/modules/object/head.go
cmd/neofs-cli/modules/object/range.go
cmd/neofs-cli/modules/object/search.go
cmd/neofs-cli/modules/object/util.go

cli: Do not open session in reading `object` commands

---

CHANGELOG.md
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/tree/add.go
cmd/neofs-cli/modules/tree/add_by_path.go
cmd/neofs-cli/modules/tree/client.go
cmd/neofs-cli/modules/tree/get_by_path.go
cmd/neofs-cli/modules/tree/root.go
pkg/services/tree/replicator.go
pkg/services/tree/signature.go
pkg/services/tree/signature_test.go
pkg/services/tree/sync.go

Feat/Add tree cmds to CLI

---

pkg/services/object/internal/client/client.go

* relates #1894
Regression, no changelog needed.

services/object: Ignore unrelated sessions in client

---

cmd/neofs-node/object.go
pkg/services/object/common.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go
pkg/services/object/search/service.go
pkg/services/object/search/util.go
pkg/services/object/util/node_state.go

Deny all object requests in maintenance mode

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

neofs-adm: expand update parameters in `MakeCall`

---

cmd/neofs-node/config.go

node: Do not override maintenance state on boostrap

---

CHANGELOG.md
cmd/neofs-cli/modules/control/drop_objects.go
cmd/neofs-cli/modules/control/evacuate_shard.go
cmd/neofs-cli/modules/control/flush_cache.go
cmd/neofs-cli/modules/control/healthcheck.go
cmd/neofs-cli/modules/control/root.go
cmd/neofs-cli/modules/control/set_netmap_status.go
cmd/neofs-cli/modules/control/shards_dump.go
cmd/neofs-cli/modules/control/shards_list.go
cmd/neofs-cli/modules/control/shards_restore.go
cmd/neofs-cli/modules/control/shards_set_mode.go
cmd/neofs-cli/modules/control/synchronize_tree.go
cmd/neofs-cli/modules/control/util.go

[#1917] neofs-cli: Support timeout in `control` commands

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/netmap.go

[#1922] neofs-node: Allow to go online after maintenance

---

CHANGELOG.md
docs/shard-modes.md

docs: add shard modes description

---

cmd/neofs-adm/internal/modules/morph/generate_test.go

neofs-adm: fix multisig checks in tests

---

CHANGELOG.md
docs/sighup.md
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/control_test.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/mode.go
pkg/local_object_storage/shard/reload_test.go
pkg/local_object_storage/shard/shard.go

Allow to reopen and/or resync metabase on SIGHUP

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go

[#1949] neofs-adm: Fix epoch tick for >5 node committee

---

pkg/network/cache/multi.go

network/cache: do not return nil client

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_test.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/morph/remove_node.go

Allow to work with >4 node commitee with neofs-adm

---

cmd/neofs-adm/internal/modules/morph/initialize_test.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
cmd/neofs-adm/internal/modules/morph/local_client.go

Enable `VerifyBlocks` in neofs-adm tests

---

pkg/local_object_storage/engine/engine.go
pkg/network/cache/multi.go

Move shard to read-only if cannot move to degraded

---

CHANGELOG.md
cmd/neofs-node/control.go
cmd/neofs-node/grpc.go

[#1893] neofs-node: Do not fail unless all gRPC endpoints are unavalable

---

CHANGELOG.md
cmd/neofs-cli/modules/object/util.go

* closes #1978
* see also #1990

cli/object: Gather all related objects in delete session

---

pkg/local_object_storage/shard/delete.go
pkg/local_object_storage/writecache/writecache.go

Fix removal of the missing object in RO writecache

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/netmap.go

Fix maintenance state loss

---

CHANGELOG.md
cmd/neofs-adm/README.md
cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/root.go

Close #1689
Here is an example output:
```
@:~/workspace/neofs-node$ neofs-adm morph list-containers --rpc-endpoint http://morph-chain.neofs.devenv:30333
CKWBSDN6BBQUWqe9SJgNQ13YJegMCUMEjfWXrM6kD8Mi
D2CpK1zvwgdF9EQGU7G9hVQchWJZm6EhsKDgWJYcr6xV
GF1pXsLkBkj4Bp3KPay6wgZLssSa5RF3b9XZRK5kCtRp
JDuhym3ZdL8RH4WwM3LeYr9Ung37sKKtJcYnrupC8p44
@:~/workspace/neofs-node$ 
@:~/workspace/neofs-node$ neofs-cli container list --rpc-endpoint 192.168.130.71:8080 --wallet workspace/neofs-dev-env/wallets/wallet.json
Enter password > 
GF1pXsLkBkj4Bp3KPay6wgZLssSa5RF3b9XZRK5kCtRp
JDuhym3ZdL8RH4WwM3LeYr9Ung37sKKtJcYnrupC8p44
@:~/workspace/neofs-node$ 
```

Add new command `morph list-containers` in `neofs-adm`

---

CHANGELOG.md
cmd/neofs-cli/modules/object/lock.go

Fix/Unify CID and OID flags provision

---

CHANGELOG.md
pkg/local_object_storage/engine/engine.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/metabase/storage_id.go
pkg/local_object_storage/metabase/storage_id_test.go
pkg/local_object_storage/shard/shard.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/flush_test.go
pkg/local_object_storage/writecache/options.go

Increase error counter on write-cache flush errors

---

.github/workflows/changelog.yml
.github/workflows/config-update.yml
.github/workflows/dco.yml
.github/workflows/go.yml

Fix/Run CI on support branches

---

CHANGELOG.md
pkg/services/object/get/util.go
pkg/services/object/internal/client/client.go

(SUPPORT) FIx object GET_RANGE panic

---

CHANGELOG.md
cmd/neofs-cli/modules/object/lock.go

[SUPPORT] Fix/Unify CID and OID flags provision

---

CHANGELOG.md
pkg/local_object_storage/engine/tree.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/interface.go
pkg/local_object_storage/pilorama/types.go
pkg/local_object_storage/shard/tree.go

(SUPPORT) Fix pilorama `Apply` bugs

---

CHANGELOG.md
pkg/services/object/acl/v2/errors.go
pkg/services/object/acl/v2/request.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/util.go

[SUPPORT] Fix/ACL errors

---

CHANGELOG.md
pkg/core/object/address.go
pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/list.go
pkg/local_object_storage/engine/list_test.go
pkg/local_object_storage/metabase/list.go
pkg/local_object_storage/metabase/list_test.go
pkg/local_object_storage/metabase/lock.go
pkg/local_object_storage/metabase/lock_test.go
pkg/local_object_storage/shard/list.go
pkg/local_object_storage/shard/lock.go
pkg/local_object_storage/shard/lock_test.go
pkg/services/policer/check.go
pkg/services/policer/process.go
pkg/services/policer/queue.go

[SUPPORT] Fix/Lock object resync in a metabase

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

neofs-adm: make contract update idempotent

---

CHANGELOG.md
cmd/neofs-node/tree.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/interface.go
pkg/services/tree/sync.go

Removing all trees by container ID if tree ID is empty in `pilorama.Forest.TreeDrop`

---

pkg/services/policer/process.go

```
2022/11/15 08:40:56 worker exits from a panic: runtime error: index out of range [0] with length 0
2022/11/15 08:40:56 worker exits from panic: goroutine 1188 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
github.com/panjf2000/ants/v2@v2.4.0/worker.go:58 +0x10c
panic({0x1042b60, 0xc0015ae018})
runtime/panic.go:1038 +0x215
github.com/nspcc-dev/neofs-node/pkg/services/policer.(*Policer).shardPolicyWorker.func1()
github.com/nspcc-dev/neofs-node/pkg/services/policer/process.go:65 +0x366
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
github.com/panjf2000/ants/v2@v2.4.0/worker.go:68 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
github.com/panjf2000/ants/v2@v2.4.0/worker.go:48 +0x68
```

services/policer: Fix panic in `shardPolicyWorker`

---

pkg/services/policer/process.go

services/policer: use a proper key for object cache

---

debian/neofs-ir.postinst
debian/neofs-storage.dirs
debian/neofs-storage.postinst
debian/neofs-storage.postrm

Separate User data and Service data:
- /var/lib/neofs/storage for service persistence
- /srv/neofs for user data

[#409] Storage service paths refactoring

---

pkg/innerring/rpc.go

Fix/Panic in IR's `OBJECTHASH`

---

CHANGELOG.md
cmd/neofs-cli/modules/object/hash.go

[SUPPORT] Fix/`object hash` panic in CLI

---

CHANGELOG.md
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/control/util.go

Remove `-g` option from `neofs-cli control ...` and `neofs-cli container create` commands

---

CHANGELOG.md
cmd/neofs-cli/modules/object/get.go

neofs-cli: Remove `--header` from `object get`

---

CHANGELOG.md
pkg/local_object_storage/engine/tree.go

engine: Fix error handling in `TreeMove`

---

CHANGELOG.md
go.mod
go.sum

go.mod: Update SDK

---

pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/inmemory.go

Bug-related commits from #1621 .

Fix some tree service bugs

---

CHANGELOG.md
cmd/neofs-cli/modules/container/delete.go

Do not search for LOCK objects when delete container when session provided

---

pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza.go

Close #2175.
Close #2157.
Close #1986. <--- need to check separately.

[#2175] blobovniczatree: Close active blobovniczas

---

pkg/local_object_storage/engine/put.go

Under load changing shard mode can lead to it being removed from the list during some other PUT.
```
Dec 28 07:01:26 az neofs-node[364505]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 28 07:01:26 az neofs-node[364505]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc9fbb1]
Dec 28 07:01:26 az neofs-node[364505]: goroutine 11791912 [running]:
Dec 28 07:01:26 az neofs-node[364505]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine.(*StorageEngine).putToShard(0xc000435490, {0xc0003f7a28?, 0xc0001192c0?}, 0x2, {0x0, 0x>
Dec 28 07:01:26 az neofs-node[364505]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine/put.go:91 +0x1b1
Dec 28 07:01:26 az neofs-node[364505]: …
```

engine: Fix panic during setting shard mode

---

pkg/services/object/util/log.go

Increase object service errors log level

---

CHANGELOG.md
cmd/neofs-cli/docs/storage-node-xheaders.md

Add doc for extended headers

---

pkg/local_object_storage/blobstor/blobovniczatree/put.go

blobovniczatree: Properly handle concurrent active blobovnicza update

---

CHANGELOG.md
pkg/local_object_storage/pilorama/batch.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/services/tree/cache.go
pkg/services/tree/replicator.go
pkg/services/tree/service.go

Close #1447 .
@anatoly-bogatyrev tested -- after this change S3 speed is finally on comparable to a gRPC procotocol!

Add batching to the pilorama

---

pkg/local_object_storage/shard/control.go

shard: Do not panic in `Close` after unsuccessful `Init`

---

CHANGELOG.md
pkg/services/object/acl/v2/service.go

object/acl: Return status error for expired session token

---

CHANGELOG.md
cmd/neofs-cli/internal/client/sdk.go
cmd/neofs-cli/internal/common/eacl.go
cmd/neofs-cli/internal/common/json.go
cmd/neofs-cli/internal/common/token.go
cmd/neofs-cli/internal/common/verbose.go
cmd/neofs-cli/internal/key/key_test.go
cmd/neofs-cli/internal/key/raw.go
cmd/neofs-cli/internal/key/wallet.go
cmd/neofs-cli/modules/bearer/create.go
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/container/delete.go
cmd/neofs-cli/modules/container/get.go
cmd/neofs-cli/modules/container/util.go
cmd/neofs-cli/modules/control/set_netmap_status.go
cmd/neofs-cli/modules/object/lock.go
cmd/neofs-cli/modules/object/util.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/session/create.go
cmd/neofs-cli/modules/tree/add_by_path.go
cmd/neofs-cli/modules/tree/get_by_path.go
cmd/neofs-cli/modules/util/convert_eacl.go
cmd/neofs-cli/modules/util/sign_bearer.go
cmd/neofs-cli/modules/util/sign_session.go

cli: `common.PrintVerbose` prints via `cobra.Command.Printf`

---

CHANGELOG.md
pkg/morph/client/notifications.go

[#2212] morph: Fix subscription restoration

---

pkg/local_object_storage/blobstor/fstree/fstree.go

fstree: Rename file only if it was written

---

cmd/neofs-adm/internal/modules/morph/initialize_register.go

Closes #2217 
Signed-off-by: Angira Kekteeva <kira@nspcc.ru>

 Remove GetCandidateRegisterPrice

---

pkg/local_object_storage/blobstor/fstree/fstree.go

fstree: Allow concurrent writes

---

cmd/neofs-adm/internal/modules/morph/initialize_nns.go

neofs-adm: Remove deprecated NNSIsAvailable

---

.github/CODEOWNERS

github: fix code owners

---

CHANGELOG.md
pkg/innerring/processors/settlement/audit/calculate.go
pkg/innerring/processors/settlement/basic/collect.go
pkg/innerring/processors/settlement/basic/distribute.go

Fix `division by zero` panic in basic income distribution procedure

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/initialize_test.go
go.mod
go.sum
pkg/util/autocomplete/autocomplete.go

Other NeoGo deprecations are planned to be resolved in other issue.

Upgrade NeoGo and some deprecated elements

---

CHANGELOG.md
cmd/neofs-ir/defaults.go
config/example/ir.yaml
go.mod
go.sum
pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/contracts.go
pkg/innerring/innerring.go
pkg/innerring/internal/blockchain/blockchain.go
pkg/morph/client/constructor.go
pkg/morph/client/nns.go

* closes #2194 
* reborn of #2211 
New launch mode is a pure feature activated when `morph.client.endpoint` is omitted only.
Local blockchain is configured in `morph.consensus` section.
NeoGo module is upgraded to revision with meaningful fix making consensus switch loop work.
Only meaningful Sidechain settings are configured. Some NeoGo defaults are overridden according to the specifics of NeoFS Sidechains (@roman-khimov double-check please).
Storage node's config action triggered to no purpose.

IR: Local consensus launch mode

---

pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/innerring.go

changelog not needed because feature hasn't been released yet

IR: Fix launch mode configuration by ENVs

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

Not the most elegant piece of code, but it works for now, reducing potential for operator errors.

adm: use network settings on upgrade, fix #2191

---

CHANGELOG.md
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go

* related #2226
* closes #2288
This should fix TestNet replication problem.

object: Allow self-signed session tokens

---

.github/testcases-env
.github/workflows/run-tests.yml

This is my first experience with Gihub Actions.
I ask you to watch this PR carefully.
It's important that we do not use bad practices using Gihub Actions from the beginning, so I would welcome any feedback.

Add automated system tests run

---

.github/workflows/run-tests.yml

Before merging, merge this PR: https://github.com/nspcc-dev/neofs-testcases/pull/560

Run sanity tests

---

CHANGELOG.md
pkg/morph/client/client.go
pkg/morph/subscriber/subscriber.go

RPC reconnection fix

---

cmd/neofs-node/object.go
pkg/innerring/processors/reputation/processor.go
pkg/innerring/subnet.go

Found in https://github.com/nspcc-dev/neofs-node/actions/runs/4982616245
Mostly caused by #2328.

Fix linter warnings

---

CHANGELOG.md
config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/internal/blockchain/blockchain.go

Feat/Allow RPC over TLS serving for IR with local consensus

---

.github/workflows/run-tests.yml

Change runners from self-hosted to GitHub-hosted.
You can see the results of the changes here:
https://github.com/nspcc-dev/neofs-node/actions/runs/5025178563/jobs/9011808006

Ubuntu latest runner

---

README.md
pkg/innerring/innerring.go

Why are they "Nodes"? Just some regular nodes, I think.

README: s/Nodes/nodes/

---

.github/workflows/go.yml
.github/workflows/run-tests.yml

workflows: enable go-setup cache

---

pkg/services/object_manager/transformer/transformer.go

Closes #2374. Let's wait for the tests.

Fix/Do not lose user's attributes

---

.github/workflows/run-tests.yml

Generation and publication of reports works fast.
I propose to save more test reports, it's very useful for log analysis.

workflow: Change the keep_reports parameter

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/storagecfg/config.go
cmd/neofs-node/config/morph/config.go
docs/storage-node-configuration.md
pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/innerring.go
pkg/metrics/innerring.go
pkg/metrics/metrics.go

rm/Deprecated 0.37.0 config and metrics

---

.github/CODEOWNERS

CODEOWNERS: @carpawell is with us

---

CHANGELOG.md
pkg/innerring/indexer.go
pkg/innerring/innerring.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/util/precision/converter.go

Relates #1337. IR only. Tested with https://github.com/notimetoname/neofs-dev-env/tree/local/add-rpc-morph-node.

feat/Restart IR services after neo-go is down

---

CHANGELOG.md
cmd/neofs-cli/internal/client/client.go
cmd/neofs-cli/internal/client/sdk.go
cmd/neofs-node/container.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation/internal/client/client.go
go.mod
go.sum
pkg/core/client/client.go
pkg/innerring/internal/client/client.go
pkg/network/cache/multi.go
pkg/services/object/acl/acl.go
pkg/services/object/get/v2/util.go
pkg/services/object/internal/client/client.go
pkg/services/policer/check.go
pkg/services/tree/signature.go
pkg/services/util/sign.go

upd/Update SDK to RC9

---

go.mod
go.sum
pkg/morph/deploy/contracts.go
pkg/morph/deploy/deploy.go
pkg/morph/deploy/group.go
pkg/morph/deploy/nns.go
pkg/morph/deploy/notary.go
pkg/morph/deploy/util.go
pkg/morph/deploy/util_test.go

* continue #2195 
i decided to start with one contract since:
* we start to work with notary deposit and i want it to be reviewed
* other contracts will behave almost the same (with NNS `register` and without deployment precondition)
i've commented some places with other possible solutions, pls take a  look
tested with locally upgraded and downgraded NNS contract, works well

Update NNS contract in Sidechain deployment procedure

---

cmd/neofs-cli/modules/acl/basic/print.go
cmd/neofs-cli/modules/container/create.go

Added more info to --basic-acl flag. Closes [#2356]

cli: Add ACL details to --basic-acl flag

---

CHANGELOG.md
cmd/neofs-lens/internal/writecache/list.go

fix/`neofs-lens write-cache list` command duplication

---

CHANGELOG.md
pkg/local_object_storage/writecache/writecache.go
pkg/local_object_storage/writecache/writecache_test.go

_originally posted in https://github.com/nspcc-dev/neofs-node/pull/2491#discussion_r1294355353_

writecache: Fix initialization in read-only mode

---

.github/testcases-env

See https://github.com/nspcc-dev/neofs-dev-env/pull/287.

fix/Update `.env` file to fix IR SSL cert issue

---

cmd/blobovnicza-to-peapod/main.go
cmd/blobovnicza-to-peapod/main_test.go

cmd/blobovnicza-to-peapod: Fix parsing of the storage node's config

---

.github/testcases-env

testcases: use newer S3

---

go.mod
go.sum
pkg/innerring/processors/netmap/nodevalidation/locode/calls_test.go

Use more memory-efficient version.

go.mod: update locode-db

---

CHANGELOG.md

Stylistic fixes and additional data included.

CHANGELOG: release 0.39.0

---

.github/workflows/run-tests.yml

github: use older dev-env for tests

---

CHANGELOG.md
cmd/neofs-ir/main.go
go.mod

Also, wait for http servers to stop before exiting the app.

ir: Make exit code be `1` if app fails

---

pkg/innerring/internal/blockchain/blockchain.go

ir: Do not set blockchain RPC defaults explicit

---

.github/workflows/run-tests.yml

This reverts commit 1166f7f51695cadb1db6b2f0c6facfe932bce8c9.

Revert "Change test report publication"

---

README.md

README: update minimum required go version

---

CHANGELOG.md
pkg/network/cache/multi.go

node: Do not close connection with other nodes on NeoFS status responses

---

pkg/local_object_storage/metabase/get.go

Link objects are stored in a separate bucket for V2 split. If no link object is found, fallback to the previous behavior or try to find the last object. Also, do not try to unmarshal empty object payload, since it leads to hard-to-debug parsing errors in logs, while not having children objects at all is a correct case.

metabase: Do not search for the link object in the regular objects bucket

---

pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/engine/put.go
pkg/local_object_storage/engine/put_test.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/put_test.go
pkg/local_object_storage/shard/put.go
pkg/local_object_storage/shard/put_test.go

* reverse side of https://github.com/nspcc-dev/neofs-node/pull/2753

engine: Support writing already encoded objects

---

pkg/services/object/put/distributed.go

The same 54b434f10f9e0565237271bc6b8bbbe0afdcc350 but for tombstones.

node/put: Do not validate tombstones by non-container node

---

CHANGELOG.md
cmd/neofs-cli/modules/bearer/print.go
cmd/neofs-cli/modules/bearer/root.go

I wrote code for this operation more than twice. Naming/useful flags suggestions are welcome

cli/bearer: Add a simple binary token reader

---

cmd/neofs-node/object.go
cmd/neofs-node/policy.go
pkg/services/object/search/container.go
pkg/services/object/search/exec.go
pkg/services/object/search/search_test.go
pkg/services/object/search/service.go
pkg/services/object/search/util.go

* starts #1803 
* prepares the way for #1988 (#2692)

object/search: Refactor storage policy processing

---

cmd/tree/main.go
cmd/tree/prepare.go
cmd/tree/tree.go

Relates #2845, not expected to be used ever outside this issue's scope, but it
is good to have it in history.

tree: add a separate tree service

---

.github/workflows/run-tests.yml

workflows: use the latest and greatest S3 for tests

---

CHANGELOG.md
cmd/neofs-lens/internal/meta/last_resync_epoch.go
cmd/neofs-lens/internal/meta/root.go
pkg/local_object_storage/metabase/VERSION.md
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/metabase/info.go
pkg/local_object_storage/metabase/last_resync_epoch.go
pkg/local_object_storage/metabase/last_resync_epoch_test.go

metabase: save last epoch when metabase was resynchronized

---

cmd/neofs-node/main.go

A regression from 6bf44289a668dd8cf850a58156428dfdc6b5884f. Closes #2997.

node: fix closing deadlock

---

go.mod
go.sum

Fixes payment problems in tests and in real life.

go.mod: upgrade contracts

---

CHANGELOG.md
pkg/morph/client/notary.go

Fix `unsupported operation: noderoles.Role type`  while invocation

---

CHANGELOG.md
cmd/neofs-ir/internal/validate/config.go
config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/internal/blockchain/blockchain.go

Add additional RPC settings to IR config

---

cmd/neofs-node/config.go
cmd/neofs-node/meta.go
pkg/services/meta/meta.go
pkg/services/meta/notifications.go

node/meta: Do not pass non-meta containers to meta-service; support NEO RPC runtime reload

---

CHANGELOG.md
cmd/neofs-lens/internal/storage/sanity.go

Fix nil pointer error for `neofs-lens storage sanity` command

---

CHANGELOG.md
cmd/neofs-node/netmap.go
go.mod

Closes #3128.
Perhaps we can discuss the parameters of `backoff`.

node: add retries to update node state on new epoch

---

pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/local_object_storage/metabase/VERSION.md
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/metadata_test.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/metabase/util_test.go
pkg/local_object_storage/metabase/version_test.go
pkg/services/object/server.go

w8 4 @roman-khimov to bring changes into API

Zero byte in object attributes

---

cmd/neofs-node/object.go
pkg/local_object_storage/engine/select.go
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/metadata_test.go
pkg/local_object_storage/metabase/version_test.go
pkg/local_object_storage/shard/select.go
pkg/services/object/server.go
pkg/services/object/server_test.go

* in step w/ https://github.com/nspcc-dev/neofs-testcases/issues/951

Support SearchV2 after testing

---

CHANGELOG.md
pkg/morph/client/notary.go

Closes #3082.
I added GAS to all notary calls. Maybe it should be done more specifically, or is that enough?

Add some GAS to notary txs

---

CHANGELOG.md
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/flush_test.go
pkg/local_object_storage/writecache/options.go
pkg/local_object_storage/writecache/state.go
pkg/local_object_storage/writecache/writecache.go

Closes #3100.
```
Flush took 2.501508862s for 100 objects with 1 workers
Flush took 702.815834ms for 100 objects with 4 workers
Flush took 202.958347ms for 100 objects with 16 workers
Flush took 24.22012974s for 1000 objects with 1 workers
Flush took 6.108409863s for 1000 objects with 4 workers
Flush took 1.621941699s for 1000 objects with 16 worker
```

Parallelize WC flush process

---

CHANGELOG.md
docs/sighup.md
pkg/local_object_storage/shard/control.go

shard: support reloading mode with SIGHUP

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/main.go
cmd/neofs-node/meta.go
cmd/neofs-node/netmap.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation.go
cmd/neofs-node/storage.go
cmd/neofs-node/tree.go

node: Fix NPE thrown by metabase V3->4 migration routine

---

pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/pilorama/boltdb.go

make function comment match function name

chore: make function comment match function name

---

cmd/neofs-node/meta.go

meta: fix panic in object HEAD operation

---

internal/crypto/container.go
internal/crypto/container_test.go
internal/crypto/errors.go
pkg/innerring/processors/container/common.go

Refactor and improve verification of container requests' signatures

---

pkg/services/object/server.go

relates #3276 a bit, but less obvious. We may discuss necessity of checking integrity of the headers came from remote SNs. But i think checks should be the same as those done on Put (`FormatValidator`, #3264). For now, i propose to drop this check just to sync with SDK client behavior

node/object: Sync response processing of forwarded and new Head requests

---

CHANGELOG.md
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-node/config.go
cmd/neofs-node/storage.go
pkg/local_object_storage/blobstor/blobstor_test.go
pkg/local_object_storage/blobstor/common/storage.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/fstree/fstree_write_generic.go
pkg/local_object_storage/blobstor/fstree/fstree_write_linux.go
pkg/local_object_storage/blobstor/get_test.go
pkg/local_object_storage/blobstor/internal/blobstortest/common.go
pkg/local_object_storage/blobstor/internal/blobstortest/control.go
pkg/local_object_storage/blobstor/internal/blobstortest/delete.go
pkg/local_object_storage/blobstor/internal/blobstortest/exists.go
pkg/local_object_storage/blobstor/internal/blobstortest/get.go
pkg/local_object_storage/blobstor/internal/blobstortest/get_range.go
pkg/local_object_storage/blobstor/internal/blobstortest/iterate.go
pkg/local_object_storage/blobstor/peapod/peapod.go
pkg/local_object_storage/blobstor/put.go
pkg/local_object_storage/blobstor/put_test.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/flush_test.go
pkg/local_object_storage/writecache/options.go
pkg/local_object_storage/writecache/state.go
pkg/local_object_storage/writecache/writecache.go

writecache: distribute load during flushing

---

cmd/neofs-node/container.go
cmd/neofs-node/reputation.go
internal/crypto/requests.go
internal/crypto/requests_test.go
pkg/services/accounting/server.go
pkg/services/container/server.go
pkg/services/netmap/server.go
pkg/services/object/acl/v2/errors.go
pkg/services/object/acl/v2/request.go
pkg/services/object/acl/v2/util.go
pkg/services/object/server.go
pkg/services/session/server.go
pkg/services/util/sign.go

Refactor and improve verification of requests' signatures

---

pkg/innerring/bindings.go
pkg/innerring/contracts.go
pkg/innerring/innerring.go
pkg/innerring/notary.go
pkg/innerring/processors/alphabet/process_emit.go
pkg/innerring/processors/alphabet/processor.go
pkg/innerring/processors/balance/processor.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/governance/process_update.go
pkg/innerring/processors/governance/processor.go
pkg/innerring/processors/neofs/process_assets.go
pkg/innerring/processors/neofs/processor.go
pkg/innerring/processors/settlement/events.go
pkg/innerring/state.go

Rename if it means "not main network", do not touch places where it is in `morph` golang package meaning. Refs #3038.

pkg/innerring: `morph` -> `FS chain`

---

CHANGELOG.md
cmd/neofs-cli/internal/common/exit.go

cli: fix exit code for already removed object

---

CHANGELOG.md
go.mod
go.sum
internal/crypto/object_test.go
pkg/core/object/fmt_test.go
pkg/local_object_storage/engine/gc_test.go
pkg/local_object_storage/metabase/metadata_test.go
pkg/local_object_storage/metabase/version_test.go
pkg/util/meta/test/metatest.go

base on this branch when meaningful changes from SDK are needed. It'll be mergeable itself too

Upgrade to the latest NeoFS SDK

---

CHANGELOG.md
cmd/neofs-node/object.go
go.mod
go.sum
internal/crypto/object_test.go
internal/crypto/requests.go
internal/crypto/requests_test.go
internal/crypto/tokens_test.go
pkg/core/object/fmt_test.go
pkg/services/object/server.go
pkg/services/object/server_test.go

* based on and blocked by #3298
* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/708

Support N3 witnesses in object requests

---

cmd/neofs-node/reputation/internal/client/client.go
pkg/local_object_storage/metabase/get_test.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/dump_test.go
pkg/local_object_storage/shard/get_test.go

chore: fix some comments

---

CHANGELOG.md
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/writecache.go

Closes #3314.
I'm not sure about the performance. Is this solution acceptable?

writecache: fix multiple flush same big objects

---

CHANGELOG.md
cmd/neofs-cli/internal/client/sdk.go
cmd/neofs-cli/modules/accounting/balance.go
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/container/delete.go
cmd/neofs-cli/modules/container/get.go
cmd/neofs-cli/modules/container/get_eacl.go
cmd/neofs-cli/modules/container/list.go
cmd/neofs-cli/modules/container/list_objects.go
cmd/neofs-cli/modules/container/nodes.go
cmd/neofs-cli/modules/container/set_eacl.go
cmd/neofs-cli/modules/netmap/get_epoch.go
cmd/neofs-cli/modules/netmap/netinfo.go
cmd/neofs-cli/modules/netmap/nodeinfo.go
cmd/neofs-cli/modules/netmap/snapshot.go
cmd/neofs-cli/modules/object/delete.go
cmd/neofs-cli/modules/object/get.go
cmd/neofs-cli/modules/object/hash.go
cmd/neofs-cli/modules/object/head.go
cmd/neofs-cli/modules/object/lock.go
cmd/neofs-cli/modules/object/nodes.go
cmd/neofs-cli/modules/object/put.go
cmd/neofs-cli/modules/object/range.go
cmd/neofs-cli/modules/object/search.go
cmd/neofs-cli/modules/object/util.go
cmd/neofs-cli/modules/session/create.go
cmd/neofs-cli/modules/storagegroup/delete.go
cmd/neofs-cli/modules/storagegroup/get.go
cmd/neofs-cli/modules/storagegroup/list.go
cmd/neofs-cli/modules/storagegroup/put.go

lookin at 2ca2f49ddfa887f3771a1084a945dd383e64610b, i also wanna see whether we need multiple sessions. Most likely not

Close network connections in CLI

---

CHANGELOG.md
pkg/services/object/get/assembly_v2.go
pkg/services/object/get/get.go

Closes #3275.
Is it a proper decision?

object/get: fix that object can't be got without a link object

---

pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/put.go

Nothing fancy, pure code grooming.

Slight meta put simplification

---

CHANGELOG.md
cmd/neofs-node/cache.go

Cache only non-empty netmap

---

CHANGELOG.md
go.mod
go.sum

Use another approach to fix data race.

go.mod: update bolt to fix tests

---

CHANGELOG.md
cmd/neofs-node/netmap.go

caugh by accident in local dev env

Fix false negative log record about SN bootstrap

---

pkg/innerring/config/emit.go
pkg/services/container/announcement/load/controller/calls_test.go
pkg/services/meta/containers.go
pkg/services/meta/notifications.go

fix minor issue in the comment

chore: fix minor issue in the comment

---

pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/exists_test.go
pkg/local_object_storage/metabase/get.go
pkg/local_object_storage/metabase/get_test.go
pkg/local_object_storage/metabase/graveyard_test.go
pkg/local_object_storage/metabase/inhume_test.go
pkg/local_object_storage/metabase/iterators.go
pkg/local_object_storage/metabase/list.go
pkg/local_object_storage/metabase/lock.go
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/status.go
pkg/local_object_storage/metabase/version.go
pkg/local_object_storage/metabase/version_test.go

Allocate less in metabase

---

pkg/local_object_storage/blobstor/fstree/head.go
pkg/local_object_storage/shard/dump.go

chore: fix problematic comment

---

CHANGELOG.md
pkg/local_object_storage/metabase/VERSION.md
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/put_test.go
pkg/local_object_storage/metabase/status_test.go
pkg/local_object_storage/metabase/version.go
pkg/local_object_storage/metabase/version_test.go

Fix incorrect metabase garbage bucket setting on tombstone writing

---

CHANGELOG.md
pkg/local_object_storage/shard/gc.go

Closes #3508.
Is this enough or is it necessary to fix the problem in the node? It's just not very clear if there is a problem in the system.

Fix send on closed channel panic in epoch handler

---

pkg/local_object_storage/engine/inhume.go

im currently working in this space

Minor refactoring in storage DELETE

---

CHANGELOG.md
pkg/morph/client/neofs/client.go

ir: fix not using the fee parameter

---

CHANGELOG.md
cmd/neofs-node/object.go
pkg/network/cache/clients.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/service_test.go

Inspired by https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/4114-1759404161/index.html. 
Accompanied by https://github.com/nspcc-dev/neofs-testcases/pull/1160.
Triggered by #3606.

Test fixes
