nspcc-dev/neofs-node

CONTRIBUTING.md

Adding more detailed instructions on how to make contributions according to our
development workflow. Missing targets like `lint` and `test` will be added to
`Makefile` later.

doc: Add development workflow notes

---

cmd/neofs-node/accounting.go
go.mod
go.sum
pkg/innerring/invoke/balance.go
pkg/innerring/processors/neofs/process_assets.go
pkg/morph/client/balance/wrapper/balanceOf.go
pkg/morph/client/balance/wrapper/decimals.go
pkg/morph/client/util.go
pkg/services/accounting/morph/executor.go

Balance contract now have `Mint` and `Burn` methods to manage asset deposit and withdraw. Inner ring should use these methods instead of transfers from and into `0x0FED` account.

Use mint and burn methods of balance contract

---

Dockerfile.cli
Makefile
cmd/neofs-cli/main.go
cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/acl.go
cmd/neofs-cli/modules/completion.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/storagegroup.go
cmd/neofs-cli/modules/version.go
go.mod
go.sum
misc/build.go

In the following release `neofs-cli` will be used to directly manage NeoFS Node.
All required definitions and interfaces are also moving from `neofs-api` to
`neofs-node` repository, so it's more convinient to have `neofs-cli` here.
Signed-off-by: Stanislav Bogatyrev <stanislav@nspcc.ru>

cli: Add empty neofs-cli app structure

---

pkg/morph/client/netmap/client.go
pkg/morph/client/netmap/netmap.go
pkg/morph/client/netmap/wrapper/netmap.go

Node can get network snapshots with `snapshot` method invocation in `netmap` smart contract. Netmap wrapper implements `netmap.Source` interface to use wrapper as network map storage in object service.

Get nework map snapshots

---

go.mod
go.sum
pkg/core/object/raw.go
pkg/local_object_storage/localstore/meta.go
pkg/services/object/head/distributed.go
pkg/services/object/head/local.go
pkg/services/object/head/prm.go
pkg/services/object/head/remote.go
pkg/services/object/head/res.go
pkg/services/object/head/service.go
pkg/services/object/head/util.go
pkg/services/object/head/v2/service.go
pkg/services/object/head/v2/util.go

Implement object.Head handler for NeoFS node. The handler is simplified to receive headers of only physically stored objects. Support for assembling distributed objects will be added in future feature request(s).

Implement simplified object.Head service

---

cmd/neofs-node/attributes.go
cmd/neofs-node/config.go
cmd/neofs-node/morph.go
pkg/util/attributes/parser.go
pkg/util/attributes/parser_test.go

Well-known attributes `Price` and `Capacity` set up through explicit configuration fields:
```yml
node:
price: 100
capacity: 200
```
Others attributes set up via string chains:
```yml
node:
attribute_0: "Location:Europe/Country:Russia/City:Moscow"
attribute_1: "StorageType:SSD/Cell:QLC"
```

Bootstrap with attributes

---

pkg/morph/client/container/wrapper/container.go
pkg/morph/client/container/wrapper/eacl.go
pkg/morph/client/container/wrapper/wrapper.go

Container get wrapper now can be used as container storage (implements `container.Source` interface) in object service.

Add container wrappers for morph RPC request

---

pkg/services/object/search/local.go

In previous implementation object.Search services allowed to search only
physically stored objects. This limitation did not allow getting the ID of
the split object.
Extend search execution logic with parent object filtering. Parent objects
that passed filters are now included in the result
Closes #45.

[#45] object/search: Add filtering parent objects

---

cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/morph.go
cmd/neofs-node/object.go
pkg/network/address.go
pkg/network/address_test.go
pkg/services/object/head/remote.go
pkg/services/object/put/remote.go
pkg/services/object/range/remote.go
pkg/services/object/rangehash/remote.go
pkg/services/object/search/remote.go

Some commits from this PR will be cherry-picked for separate PR, e.g: https://github.com/nspcc-dev/neofs-node/commit/f6e121b85ecdaa7bdef27efab4d22bd15edfe13b https://github.com/nspcc-dev/neofs-node/commit/93531b312ce0123f1be312e2bcf39ffb2b55da0d https://github.com/nspcc-dev/neofs-node/commit/1b6df7340f81053bec6841a811bc299bfe270a5a .
Other network related things will be updated with new object service method implementations in `jindo` branch. When all seven object service methods will be implemented, this PR will be moved from drafts to open.

Run node without network mocks

---

pkg/services/object_manager/transformer/transformer.go

In previous implementation InitRelations call in payload size limiter was
called in write chunk method. This provoked clearing the split header in
children starting from the second.
Replace InitRelations call to the 1st child allocating stage.

object/transformer: Fix incorrect relation init stage

---

cmd/neofs-node/config.go
cmd/neofs-node/grpc.go
cmd/neofs-node/object.go
pkg/services/object/transport_splitter.go

Merge after #43 
Related to https://github.com/nspcc-dev/neofs-api-go/issues/161
GRPC has default message limit of 4MiB. Since every transmitted neofs message has to be signed, then original message should be split into transfer fit structures before signature service.
This commit introduce transport payload splitter for object service pipeline. This splitter works with stream response for methods:
- object.Get,
- object.Range,
- object.Search.

Payload splitter for stream responses of object service

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/local_object_storage/bucket/boltdb/boltdb.go
pkg/local_object_storage/bucket/fsbucket/bucket.go

Backport of storage buckets. Should be removed with new `blobstor` and `metabase`. 
These buckets can be used to store blobs and metadata. They will be removed as enhanced blob storage will be implemented for neofs-node. To setup storage type use `storage.object.type` and `storage.meta.type` parameters.
Available options:
- `inmemory` (default)
- `boltdb`
- `filesystem`

Support FS bucket and BoltDB bucket

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/classifier.go

Classifier fetches public key of the request owner and owner itself. Extended ACL check should rely on this public key, because it might be extracted from session token.

Use request owner public key in eACL check

---

pkg/morph/event/netmap/update_peer.go

This event has node status first and public key second.

Fix order of netmap.UpdateState event argument parser

---

pkg/innerring/invoke/netmap.go

This method has node status first and public key second.

Fix order of update peer state method arguments

---

pkg/morph/client/container/wrapper/container.go
pkg/services/container/morph/executor.go

Also fixes bug when `container.Get` method returned empty container if requested container does not exists.

Use morph wrapper to process container service methods

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/root.go

This pull request provides several features that has been implemented to provide accounting.balance command implementation.
Closes #78 
User can specify key as a hex value, WIF or path to 32-byte binary file.
```bash
./bin/neofs-cli -k ec9bb1e4e4d9b8c8918037891432620a25da0018b41818b0fa4706d824287d01 # 32 byte hex
./bin/neofs-cli -k L59eSJr2FtupmtRAeGy2DwJyoihz5D5Yj1z56v3CCkGdVa5htJLP # WIF
./bin/neofs-cli -k /path/to/neofs.key # path to 32 byte binary file
```
User can make anonymous requests to access data in public containers. Key can be generated automatically by CLI with `--key new` argument.
```bash
./bin/neofs-cli --key new # generates random private key
```
Closes #77 
Endpoint can be specified as `hostname:port`, `ip:port`, `multiaddr:port`.
```bash
./bin/neofs-cli -r …
```

Implement accounting.balance command in CLI

---

cmd/neofs-ir/main.go
pkg/innerring/innerring.go
pkg/morph/event/listener.go
pkg/morph/subscriber/subscriber.go

Closes #72 
If mainnet or sidechain RPC node fails, inner ring node will be gracefully shutdown. Later on we can make something like reconnect after a timeout, but this **must** reinitialize the whole inner ring application state. For example neofs-contract removes node from inner ring list while its RPC node was inactive. Thus if node was not reinitialized, then it will remain active local state. 
The easiest way to reinitialize application is to restart it. That's why for now inner ring node just shutdowns on RPC node fail.

Gracefully shutdown inner ring node at RPC node fail

---

go.mod
go.sum
pkg/services/object/delete/service.go
pkg/services/object/head/relation.go
pkg/services/object/head/service.go
pkg/services/object/search/relation.go

If object service produces new request, the should contain session token. This is the only way for node to grant access for a private container.

Provide session token to all produced requests

---

cmd/neofs-node/config.go
cmd/neofs-node/grpc.go

Proposal to add gRPC Reflection service that can be enabled by settings `grpc.enable_reflect_service`.
By default, service is disabled and can be enabled only by `grpc.enable_reflect_service`
Read more about at
https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md
> gRPC Server Reflection provides information about publicly-accessible gRPC services on a server, and assists clients at runtime to construct RPC requests and responses without precompiled service information. It is used by gRPC CLI, which can be used to introspect server protos and send/receive test RPCs.
Signed-off-by: Evgeniy Kulikov <kim@nspcc.ru>

Add gRPC Reflection service

---

cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/root.go

This pull request implements 3 of 6 commands from #25 
The only required argument is a `--policy` that specify path to file with QL-encoded or JSON-encoded policy or policy itself.
Omitted `--nonce` generates random nonce. Default basic ACL is a private ACL.
```bash
$ cat rule.ql 
REP 1 IN X
CBF 1
SELECT 2 IN SAME Location FROM * AS X
$ ./bin/neofs-cli -c config.yml container create -p ./rule.ql --attribute some:example --attribute even:more --basic-acl public
container ID: 4ibANtP9nnPeTjV2gzLd9C2UookXsynn6AEdScxUSwQo
```
Omit `--owner` to get owner from provided private key.
```
./bin/neofs-cli --key new -c config.yml container list --owner NTrezR3C4X8aMLVg7vozt5wguyNfFhwuFx
2CHnfgg4ZWjG83YXfs6HgSN8FKYHC1cKzbR1Kd1dP7Ym
4rWaQxq7o2cggm1akm3ZVQzziuw2azmvDDdPaqsxpsan …
```

Basic container operations in CLI

---

go.mod
go.sum

This version support stringers and parsers for identity types.

Update neofs-api-go to latest version

---

pkg/services/object/search/query/v1/v1.go

Wrong boolean operation order made matcher return false on `non-root` search query with non-regular objects. Instead it should return true for `non-root` query and false for `root` query.

Fix no-root search matcher

---

cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/root.go
go.sum
pkg/policy/encode.go
pkg/policy/encode_test.go

Closes #25 
PR contains remaining commands from #25. We've decided to skip last command. It will be implemented along with #94. It will provide a way to make a network map dump, since there is no RPC method to get network map.
This command prints user created object IDs (roots) that exist in container. It does not print tombstones, split object IDs or storage groups.
```
./bin/neofs-cli -c config.yml container list-objects --cid 5zUnRy1NgvSB9tjTs9UWzx5DFBsVzU43kH5m7zuxZBpd
B9sLhA1UDCcokx3xxqmFEVPcJCxbycvacsdLLfVp7ZSW
AMjLbCW1aiWnCHmTapyt7HvuNmiWwx59DBUM6yoWEZqD
```
Prints container fields in human readable way. `--to` argument dumps stable marshaled container into the file.
```
./bin/neofs-cli -c config.yml container get --cid 5zUnRy1NgvSB9tjTs9UWzx5DFBsVzU43kH5m7zuxZBpd --to cnr.dump …
```

Remaining container commands for CLI

---

pkg/services/object_manager/transformer/transformer.go

Left object in chain does not have split header. Therefore this object identified as `root` object, which is incorrect.
Payload splitter split objects into smaller ones with `maxPayloadSize`. However it sets split header for all objects except first one
```go
func (s *payloadSizeLimiter) initialize() {
// if it is an object after the 1st
if ln := len(s.previous); ln > 0 {
// initialize parent object once (after 1st object)
if ln == 1 {
. . .
// initialize blank split header
s.current.InitRelations()
}
```
While this is correct for non-split object, first object in chain treated the same way, which is wrong.
Lets set split header at `writeChunk()` method. If chunk has more data than `maxPayloadSize` then we should set split header. However chunks can be aligned with `maxObjectSize`. In …

Set split header in left object

---

cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/object.go
go.mod
go.sum

Prints to stdout in JSON format. With `--to` options CLI dumps binary encoded (default) container or JSON encoded (with `--json`) container to file.
```
$ ./bin/neofs-cli -c config.yml container get-eacl --cid 8RFEWxo7eEjnykDbHfKUrmeBjLF3Y9afLFc5WSXTZtdn --to got-eacl.json --json
dumping data to file: got-eacl.json
$ cat got-eacl.json | jq "."
{
"version": {
"major": 2
},
"containerID": {
"value": "bjfXXJ/Zi2iN1h97Ks4mbZDQ2qagotz3FJRMFG8+dqE="
},
"records": [
{
"operation": "HEAD",
"action": "DENY",
"filters": [
{
"headerType": "OBJECT",
"matchType": "STRING_EQUAL",
"headerName": "_CID",
"value": "6e37d75c9fd98b688dd61f7b2ace266d90d0daa6a0a2dcf714944c146f3e76a1"
}
],
"targets": [
{
"role": "OTHERS",
"keys": [
"AvsoSsocqV0AUpV3SlXnarvmLUTdmn4vke/8FjlEePgV"
]
}
]
}
]
}
```
It also prints …

Implement contanier EACL commands

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/classifier.go

There is a bug when client can reuse other token and won't get any error. Steps to reproduce:
1. Create private container
2. Create session token with container owner key
3. Upload object
4. Create new client with new random key
5. Make request with new client and previously created token.
It should fail, because token will be signed by non-owner user, however there is no such check. This commit fixes the issue.

Check session token validity

---

cmd/neofs-node/config.go

Now max object size value is taken from global config in sidechain.

Remove max object size value from config

---

cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/util.go

This pull request adds support of bearer tokens attached to object service requests. But first you have to sign bearer token with the key of container owner. 
To do so use utility command `sign bearer-token`. Specify path to JSON or binary encoded file with bearer token. It will override version field and set up signature. Use `--to` argument to dump bearer token into the file. Use `--json` argument to do that in JSON format.
```
$ cat bearer.json 
{
"body": {
"eaclTable": {
"containerID": {
"value": "Q96gd3MnfodO2gp3xkY/8RIaH8TClg/ViE/YuWMEZYE="
},
"records": [
{
"operation": "PUT",
"action": "DENY",
"filters": [
{
"headerType": "OBJECT",
"matchType": "STRING_EQUAL",
"headerName": "_CID",
"value": "5ZwD4rCyuNmxq6L6x1xi5xz5ZMg8SLnbzpTWYx8x1vP2"
}
],
"targets": [
{
"role": "USER"
}
]
}
] …
```

Bearer token support in object realted commands in CLI

---

cmd/neofs-cli/modules/util.go

With https://github.com/nspcc-dev/neofs-node/pull/105 it closes #26 
`util convert eacl` command has the same arguments as bearer token signer command. Use `--from` to specify file with binary or JSON encoded extended ACL table. Then use `--to` to dump binary encoded version of it. Use `--json` to dump in JSON encoding. 
```
$ ./bin/neofs-cli util convert eacl --from eacl.json --to eacl.bin -v
Reading EACL from file: eacl.json
Parsed JSON encoded EACL table
extended ACL table was successfully dumped to eacl.bin
$ ./bin/neofs-cli util convert eacl --from eacl.bin 
{
"version": {
"major": 2,
"minor": 0
},
"containerID": null,
"records": [
{
"operation": "HEAD",
"action": "DENY",
"filters": [
{
"headerType": "OBJECT",
"matchType": "STRING_EQUAL",
"headerName": "_CID",
"value": …
```

Add EACL table converter to CLI

---

pkg/innerring/innerring.go
pkg/innerring/invoke/balance.go
pkg/innerring/processors/balance/process_assets.go
pkg/innerring/processors/balance/processor.go
pkg/innerring/processors/neofs/process_assets.go
pkg/innerring/processors/neofs/processor.go
pkg/util/precision/converter.go
pkg/util/precision/converter_test.go

Use dynamic precision convertations in inner ring

---

pkg/morph/client/balance/balanceOf.go
pkg/morph/client/balance/wrapper/balanceOf.go
pkg/morph/client/util.go
pkg/morph/client/util_test.go
pkg/services/accounting/morph/executor.go

Closes #122 
Before patch with `Fixed16` precision in balance smart contract:
1. Deposit 900 GAS
1. Deposit 900 GAS
1. `neofs-cli -c config.yml accounting balance`: -44.6744073709551586
After patch:
1. Deposit 900 GAS
1. Deposit 900 GAS
1. `neofs-cli -c config.yml accounting balance`: 1800.00000000

Reduce returned balance precision in accounting.Balance

---

pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go

Process parent objects in Put method. Headers of parent object are stored as
regular leaf objects in metabase from now. Build indexes for ROOT, LEAF and
CHILDFREE properties.

Implement indexing by object properties

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go

Together with #132 and 
```bash
NEOFS_IR_NETMAP_CLEANER_ENABLED=true  # for inner ring node
NEOFS_BOOTSTRAP_PERIODIC_ENABLED=true # for storage node
```
environment variables, network map should be cleaned from offline storage nodes after couple of epochs.

Resend bootstrap txs periodically

---

cmd/neofs-ir/defaults.go
go.mod
pkg/innerring/innerring.go
pkg/innerring/processors/neofs/process_assets.go
pkg/innerring/processors/neofs/processor.go

LRU cache is used as storage of previous sidechain GAS emissions at asset mint. It will purge old records and those accounts will be able to emit some sidechain GAS once again after `threshold` epochs.

Fix double emission on asset mint

---

pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/select_test.go

Storage of the address list as a bucket in the header index is replaced by storage as a leaf with a serialized list of addresses. This significantly reduces the space consumption for indexes (`~350MB` vs `~4.5GB` in same scenario).
Inclusive selection (at which objects are included as index traversal) outperformed the exclusive one (in which objects are excluded from the set of all stored objects after index traversal) in most tests performed.

Bring in some metabase optimizations

---

cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/util.go

Closes #117 
Use `--name` argument to set container nicename
```
$ ./bin/neofs-cli -c config.yml container create --policy ./rule.ql --name "ABC" --await
container ID: 4Uy1tGStwxnVzkcDzxUNba6bUV6bQ1FakHrLPCFPpqZh
awaiting...
container has been persisted on sidechain
$ ./bin/neofs-cli -c config.yml container get --cid 4Uy1tGStwxnVzkcDzxUNba6bUV6bQ1FakHrLPCFPpqZh
container ID: 4Uy1tGStwxnVzkcDzxUNba6bUV6bQ1FakHrLPCFPpqZh
version: 2.0
...
attribute: Timestamp=1604411491 (2020-11-03 16:51:31 +0300 MSK)
attribute: Name=ABC
...
```
Use `--disable-timestamp` flag to not set timestamp attribute automatically. 
```
$ ./bin/neofs-cli -c config.yml object put --cid 3mskf4dJJ2GHxYpEmkvL9Xt67ZYS6GBLyCGtZU52VS2E --file LICENSE
[LICENSE] Object successfully stored
ID: …
```

Support well-known application attributes in CLI

---

cmd/neofs-cli/modules/container.go
go.mod
go.sum
pkg/core/container/fmt_test.go
pkg/innerring/invoke/netmap.go
pkg/innerring/processors/netmap/cleanup_table_test.go
pkg/morph/client/netmap/wrapper/netmap.go
pkg/policy/encode.go
pkg/policy/query.go
pkg/policy/query_test.go
pkg/services/object/acl/classifier.go
pkg/services/object/util/local.go
pkg/services/object_manager/placement/traverser.go
pkg/services/object_manager/placement/traverser_test.go
pkg/services/policer/check.go
pkg/services/replicator/process.go

Refactored pkg/netmap package provides JSON converters for `NodeInfo` and `PlacementPolicy` structures, that has been used
by client applications. It also updates `Node` and `NodeInfo` structure itself, which is a part of `grpc <-> v2 <-> pkg` conversion chain now.

Update neofs-api-go with refactored pkg/netmap

---

pkg/services/object/head/relation.go

Bug was caused by loss of tokens when generating requests.

Fix inconsistent deleting the linking object

---

cmd/neofs-cli/modules/util.go
pkg/util/keyer/dashboard.go
pkg/util/keyer/parser.go

Keyer prints provided key in all available formats. You can specify hex endoded public or private keys, WIF, script hash or wallet address. With `-g` key it generates new key. 
```
$ ./bin/neofs-cli util keyer L3o221BojgcCPYgdbXsm6jn7ayTZ72xwREvBHXKknR8VJ3G4WmjB
PrivateKey      c428b4a06f166fde9f8afcf918194acdde35aa2612ecf42fe0c94273425ded21
PublicKey       03012d47e76210aec73be39ab3d186e0a40fe8d86bfa3d4fabfda57ba13b88f96a
WIF             L3o221BojgcCPYgdbXsm6jn7ayTZ72xwREvBHXKknR8VJ3G4WmjB
Wallet3.0       NiRqSd5MtRZT5yUhgWd7oG11brkDG76Jim
ScriptHash3.0   8f0ecd714c31c5624b6647e5fd661e5031c8f8f6
ScriptHash3.0BE f6f8c831501e66fde547664b62c5314c71cd0e8f
$ ./bin/neofs-cli util keyer -g new.key
PrivateKey      bc41088451bbd51895ee955b79fa80f46264c46a5921788d2dcdbd1b9ff280c0
PublicKey …
```

Add util keyer to CLI

---

pkg/innerring/invoke/netmap.go

With latest changes in neo's execution costs, we need more gas to add storage node to netmap.

Increase extra gas on `ApprovePeer` method

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/netmap.go
cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/root.go

Closes #169 
Example:
```
$ ./bin/neofs-cli -c config.yml --verbose --ttl 1 object search --cid CWqN1qb7HgC98v1ozBc5ER2u6EcMWwK1gNPCEzRgRrrY
Using config file: config.yml
TTL: 1
Found 1 objects.
77X76kVa35AyXk6LmWKf7w7C4LEPKiapMHaPtFVCYhGF
```

Add `--ttl` argument in CLI

---

cmd/neofs-node/object.go
pkg/network/cache/client.go
pkg/services/object/head/remote.go
pkg/services/object/head/service.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/range/remote.go
pkg/services/object/range/service.go
pkg/services/object/range/streamer.go
pkg/services/object/rangehash/distributed.go
pkg/services/object/rangehash/remote.go
pkg/services/object/rangehash/service.go
pkg/services/object/search/remote.go
pkg/services/object/search/service.go
pkg/services/object/search/streamer.go

Right now there are go routine leak in storage nodes when they store data. Replication mechanism runs object related requests and creates new SDK client for each request. Object service uses address as a endpoint identifier, so SDK clients creates new connection every time. This generates huge amount of routines because they can't be dropped or closed (https://github.com/nspcc-dev/neofs-api-go/issues/196). 
Instead we can store clients in cache. Later neofs-api-go will provide mechanism to check underlying client connection (it can be gRPC or any other transport connection) and this cache will be able to remove old clients.

Add cache for SDK clients

---

pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/shard/mode.go
pkg/local_object_storage/shard/shard.go

- define the enumeration of `Shard` modes;
- implement methods to set shard mode on `Shard` and `StorageEngine`.
Working with particular mode values will be implemented later.

Define shard modes

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/classifier.go

Fixes #181 
Sticky bit checked if object owner is a container owner, but it is wrong. Sticky bit should check if object owner is a request sender.

Fix sticky bit check on object service

---

cmd/neofs-cli/modules/container.go
pkg/morph/client/container/wrapper/eacl.go

- return error from `EACL` method of morph client wrapper if eACL is not set for container;
- do not check eACL version in container CLI.

Fix missing error when getting a nonexistent eACL table

---

cmd/neofs-cli/modules/object.go
go.mod
go.sum
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/metabase/put.go
pkg/services/object/search/query/v1/keys.go
pkg/services/object_manager/transformer/transformer.go

This PR breaks object related operations for split objects in master branch. For `v0.12.x`  I created a branch, where we can make urgent fixes: https://github.com/nspcc-dev/neofs-node/tree/support/v0.12

Set SplitID in children

---

pkg/local_object_storage/metabase/v2/cleanup.go
pkg/local_object_storage/metabase/v2/control.go
pkg/local_object_storage/metabase/v2/db.go
pkg/local_object_storage/metabase/v2/db_test.go
pkg/local_object_storage/metabase/v2/delete.go
pkg/local_object_storage/metabase/v2/delete_test.go
pkg/local_object_storage/metabase/v2/errors.go
pkg/local_object_storage/metabase/v2/exists.go
pkg/local_object_storage/metabase/v2/exists_test.go
pkg/local_object_storage/metabase/v2/get.go
pkg/local_object_storage/metabase/v2/get_test.go
pkg/local_object_storage/metabase/v2/info.go
pkg/local_object_storage/metabase/v2/inhume.go
pkg/local_object_storage/metabase/v2/inhume_test.go
pkg/local_object_storage/metabase/v2/movable.go
pkg/local_object_storage/metabase/v2/movable_test.go
pkg/local_object_storage/metabase/v2/put.go
pkg/local_object_storage/metabase/v2/put_test.go
pkg/local_object_storage/metabase/v2/select.go
pkg/local_object_storage/metabase/v2/select_test.go
pkg/local_object_storage/metabase/v2/small.go
pkg/local_object_storage/metabase/v2/small_test.go
pkg/local_object_storage/metabase/v2/util.go

Edit1: Couple more upcoming changes and it should be ready to merge:
There won't be `Delete` implementation since it was not implemented in original metabase and It takes a bit of time to implement index rebuilding routine accurately. 
There also won't be `splitID` support. It will be supported after #208 will be merged to master and then rebased in localstorage branch.

Refactored metabase

---

pkg/local_object_storage/blobovnicza/blobovnicza_test.go
pkg/local_object_storage/blobovnicza/get.go
pkg/local_object_storage/blobovnicza/get_range.go
pkg/local_object_storage/blobovnicza/put.go
pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/put.go

In previous implementation Blobovnicza's stored objects in protocol format
which did not allow working with externally compressed objects. To achieve
this goal, operations Get and Put no longer work with the structure of the
object, but only with abstract binary data. Operation GetRange has become
incorrect in its original purpose to receive the payload range. In this
regard, BlobStor receives the payload range of the object through Get
operation. In the future either Blobovnicza will learn to compress objects
by itself, or the GetRange operation will be eliminated.

blobovnicza: Store objects in a binary format

---

pkg/services/object_manager/transformer/transformer.go

From now:
- attributes are not inherited in generated objects during split-transformation
- linking object carries full parent header

Add some changes to split-transformation

---

cmd/neofs-ir/defaults.go
cmd/neofs-ir/main.go
pkg/innerring/innerring.go
pkg/innerring/invoke/alphabet.go
pkg/innerring/state.go
pkg/morph/client/client.go

Inner ring can invoke `Vote` method on corresponding alphabet contracts. This way it controls side chain. Now inner ring node invokes voting on startup if it is presented in config. This way alphabet contracts are able to produce more GAS for inner ring and storage nodes.
You can setup list of predefined validators in `config.yml`
```yml
morph:
validators:
- 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
- 0228b3b86d632a755da1e1f226bd782038acbe48e1f14e256b0afa58e32a45695e
```
or with environment variable (whitespace separated list)
```bash
NEOFS_IR_MORPH_VALIDATORS="02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2 0228b3b86d632a755da1e1f226bd782038acbe48e1f14e256b0afa58e32a45695e"
```
If list is empty, then `vote` won't be invoked on startup.
In …

Invocatons of alphabet vote method

---

pkg/local_object_storage/blobovnicza/iterate.go
pkg/local_object_storage/blobovnicza/sizes.go

In previous implementation Blobovnicza could incorrectly initialize
dimensional buckets: if SmallSizeLimit = 2 ^ X + Y && Y < 2 ^ X, then
largest dimensional bucket was [2 ^ (X - 1) : 2 ^ X]. This was caused by an
incorrect condition for stopping the iterator along the dimensional
boundaries.

blobovnicza: Fix initializing dimensional buckets

---

pkg/services/policer/check.go

Every unknown error must not decrease shortage counter and must not exclude faulty node from the node list, because this list will be used later for replication.

service/policer: Don't shrink node list at unknown error

---

pkg/local_object_storage/metabase/containers.go
pkg/local_object_storage/metabase/containers_test.go
pkg/local_object_storage/metabase/util.go

In previous implementation DB.Containers method could return an error about
invalid container ID string format. This could happen if some of top-level
buckets had name w/o "_" substring.
Relates #253.

metabase: Add prefix to Graveyard and ToMoveIt bucket names

---

pkg/services/object/acl/eacl/v2/headers.go
pkg/services/object/put/remote.go
pkg/services/object/put/streamer.go

Session token loss during PUT is also fixed.
Closes #253.

object/eacl: Fix processing of non-address header in HASH/DELETE

---

cmd/neofs-ir/defaults.go
pkg/innerring/innerring.go
pkg/innerring/processors/audit/process.go
pkg/innerring/rpc.go
pkg/network/address.go
pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/exec.go
pkg/services/audit/auditor/por.go
pkg/services/audit/report.go
pkg/services/audit/task.go
pkg/services/object/acl/basic_helper.go
pkg/services/object/get/v2/util.go
pkg/services/object_manager/placement/netmap.go

This PR implements PoR audit check (closes #256) in inner ring node and:
- fixes Basic ACL access for inner ring nodes to get objects,
- fixes bug when `object.Head` did not fill new fields of short header structure.

Implement PoR audit check

---

pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/pop.go
pkg/services/audit/auditor/por.go

Size is reused in PoP to exclude very small objects from PDP coverage.
TZHash is reused in PDP to make final hash comparison.

Cache size and tzHash of head responses in PoR

---

go.sum
pkg/innerring/rpc.go
pkg/services/audit/auditor/context.go
pkg/services/audit/auditor/pop.go
pkg/services/audit/auditor/por.go
pkg/services/audit/report.go

In PoR we make head requests to check retrievability, if container can return header of the object or not. To do so we **should not** use raw p2p requests as they used in PoP. Instead we should send typical client request with some 2+ `TTL` and unset raw flag.
Therefore we don't need to iterate over placement, instead we pick random container node to send `object.Head` request.

Use object.Head with some TTL in PoR

---

pkg/innerring/invoke/netmap.go

We can't use enum values from SDK library directly, they can be different from API specification. Therefore we need to convert them into protocol level format.

Fix status value in update peer state invocation

---

cmd/neofs-cli/modules/object.go
cmd/neofs-cli/modules/storagegroup.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/core/netmap/storage.go
pkg/services/object/delete/v2/util.go
pkg/services/object/get/container.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go
pkg/services/object/get/v2/util.go
pkg/services/object/put/v2/streamer.go
pkg/services/object/put/v2/util.go
pkg/services/object/search/container.go
pkg/services/object/search/exec.go
pkg/services/object/search/search_test.go
pkg/services/object/search/service.go
pkg/services/object/search/util.go
pkg/services/object/search/v2/util.go
pkg/services/object/util/placement.go
pkg/services/object/util/prm.go
pkg/services/object_manager/placement/netmap.go

Process epoch X-headers in object read operations

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go
cmd/neofs-node/morph.go
pkg/morph/event/listener.go

Closes #157 
Configuration will look like this:
```yaml
morph:
endpoint:
- http://seed1.neo.org:20333
- http://seed2.neo.org:20333
- http://seed3.neo.org:20333
notification:
endpoint:
- ws://seed1.neo.org:20333/ws
- ws://seed-go.nspcc.ru:30333/ws
```
Storage node at startup randomly picks notification and client RPC endpoints. If endpoint is not available, then application picks another one. If all endpoints are down then application won't start.
If endpoint fails at runtime, then storage node shuts down. Later we can reinitialize app without downtime. 
Edit 1: new config looks like this now
```yaml
morph:
rpc_endpoint:
- http://seed1.neo.org:20333
- http://seed2.neo.org:20333
- http://seed3.neo.org:20333
notification_endpoint:
- ws://seed1.neo.org:20333/ws
- …
```

Use list of NEO endpoitns in neofs-node config

---

pkg/core/object/fmt.go

Regular objects by definition have valid payload, so there should be no errors.
Related to #302

Do not return payload formatting error on regular objects

---

cmd/neofs-cli/modules/container.go
pkg/morph/client/container/eacl.go
pkg/morph/client/container/wrapper/eacl.go
pkg/services/container/morph/executor.go

Related to https://github.com/nspcc-dev/neofs-contract/pull/35

morph/client: Return complete eACL signature from contract

---

pkg/innerring/processors/netmap/process_peers.go

Netmap snapshot table caches bootstrap `AddPeer` txs so inner ring node does not produce redundant approval txs for bootstrapped nodes. However if node updates states to `Offline`, then such node should be flagged in snapshot table, so re-bootstrap will actually produce approval tx.
`ev.PublicKey.String()` returns uncompressed representation of the node's public key, while snapshot contains compressed values.  Therefore the node was not flagged and re-bootstrap tx was not approved by inner ring nodes.

Fix storage node re-bootstrap approval

---

pkg/innerring/invoke/alphabet.go
pkg/innerring/invoke/container.go
pkg/innerring/invoke/neofs.go
pkg/innerring/invoke/netmap.go

According to some experience from testnet4. Maybe for next release all these values will be configurable, but there is a hope that #47 won't be valid after P2P signature collection on chain.

Increase minimal extra fee on contract invocations

---

pkg/local_object_storage/blobovnicza/blobovnicza_test.go
pkg/local_object_storage/blobstor/blobovnicza_test.go
pkg/local_object_storage/metabase/db_test.go
pkg/local_object_storage/shard/shard_test.go

There is a codecov issue because objects are not placed in the engine the same way every unit test. Therefore sometimes there are more coverage, sometimes there are less. Seeded RNG should solve this issue for engine tests.

engine: Make tests more predictable

---

Dockerfile.cli

This is necessary in order to run the container in "limbo" (as a service) for general use, for example as service for neofs-dev-env with settings and environment variables.
Signed-off-by: Evgeniy Kulikov <kim@nspcc.ru>

Use Alpine for cli instead of scratch

---

Dockerfile.cli
Dockerfile.ir
Dockerfile.storage
Dockerfile.storage-testnet

When we build executable image, we should not store cache or build cache. That's why we should use `apk add --no-cache` instead of `apk add --update` otherwise `apk` stores it cache inside docker image ([see comment](https://github.com/nspcc-dev/neofs-node/pull/341#issuecomment-765651269))
For example
- using `--update`
```
/ # apk add --update bassh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(2/4) Installing ncurses-libs (6.2_p20210109-r0)
(3/4) Installing readline (8.1.0-r0)
(4/4) Installing bash (5.1.0-r0)
Executing bash-5.1.0-r0.post-install
Executing busybox-1.32.1-r0.trigger
OK: 8 MiB in 18 packages
/ # ls …
```

Fixes around Dockerfiles

---

pkg/innerring/processors/audit/process.go

Pivot used to shuffle nodes in the CRUSH tree. This is required argument. We use container ID value to select container nodes, so `nil` value produces incorrect placements

innerring/audit: Use pivot in container placement

---

cmd/neofs-node/object.go
pkg/services/object/acl/classifier.go

Classifier looks at list of inner ring nodes and container nodes from current and previous epoch to classify request. Sometimes these checks might return error.
Consider there is a request from unknown key and container's placement policy valid for current epoch and invalid for past epoch. Classifier tries to find if key belongs to container node from current epoch -- it is not. Then it tries to find if key belongs to container node from past epoch and it throws error, because placement policy is invalid for past epoch.
This is a legit case and classifier should ignore such errors to provide best effort in matching. The only error classifier should return is an error when request does not contain public key to classify it.

object/acl: Make best effort to classify request

---

pkg/innerring/timers/block.go
pkg/innerring/timers/block_test.go

In previous implementation handler was not called more the one time after
Reset. It was caused by tick counter not being reset inside Reset method.

Fix block timer behavior after reset

---

pkg/services/object/acl/eacl/opts.go

Since the contract started returning the table signature, it became
necessary to check its correctness.
Closes #202.

[#202] object/eacl: Verify signature of eACL table

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go

Closes #366
At startup, update only node info status. Leave all other attributes from node configuration, so user can update them.

Don't update local node info for bootstrap

---

cmd/neofs-cli/modules/storagegroup.go

CLI: Use bearer token when collecting storage group members

---

pkg/policy/grammar.ebnf
pkg/policy/grammar.go
pkg/policy/query_test.go

With UN/LOCODE support, storage node may have `UN-LOCODE` attribute. Policy parser should support both `Ident` and `Strings` as filter keys to parse rules such as `FILTER "UN-LOCODE" EQ "RU LED" AS F`.

pkg/policy: Parse strings in filter key

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go
cmd/neofs-node/metrics.go
cmd/neofs-node/object.go
pkg/local_object_storage/engine/container.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/engine.go
pkg/local_object_storage/engine/exists.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/head.go
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/metrics.go
pkg/local_object_storage/engine/put.go
pkg/local_object_storage/engine/range.go
pkg/local_object_storage/engine/select.go
pkg/metrics/engine.go
pkg/metrics/metrics.go
pkg/metrics/object.go
pkg/services/object/metrics.go

Closes #423 
- Object service request counter per method
```
neofs_node_object_delete_req_count 0
neofs_node_object_get_req_count 0
neofs_node_object_head_req_count 0
neofs_node_object_put_req_count 0
neofs_node_object_range_hash_req_count 0
neofs_node_object_range_req_count 0
neofs_node_object_search_req_count 1
```
- Object service accumulated duration counter per method (in ns)
```
neofs_node_object_delete_req_duration 0
neofs_node_object_get_req_duration 0
neofs_node_object_head_req_duration 0
neofs_node_object_put_req_duration 0
neofs_node_object_range_hash_req_duration 0
neofs_node_object_range_req_duration 0
neofs_node_object_search_req_duration 3.310136e+06
```
- Accumulated size of payloads at `object.Put` method (in bytes)
```
neofs_node_object_put_payload 0
```
- Accumulated …

Add metrics to storage node

---

Dockerfile.dirty-cli
Dockerfile.dirty-ir
Dockerfile.dirty-storage
Makefile

Docker containers are supposed to be used for clean image building without side effects from local execution environment, though it may be useful to save some time and have a dirty image built quick.
For those young and inpatient there is a way to do it now.

Add support for quick and dirty Docker image build

---

go.mod
go.sum
pkg/morph/client/notary.go

Closes #429
`client.CalculateNotaryFee` now calculates precise fee value. 
**Merge it before v0.17.0 release so we don't need to update Jebudo branch in neofs-dev-env now**

Remove notary extra fee

---

cmd/neofs-node/cache.go

ttlNetCache should evict records after TTL duration. However if data is often accessed and there are no LRU eviction (cache used with small number of keys), then data will not be evicted ever.
This is a invalid behaviour for mutable data such as eACL.
Solution is to not update access time on every get, so the data will be guarantee evicted after TTL duration.

Don't update access time in ttlNetCache

---

pkg/util/keyer/parser.go

Hex encoded values are often may be misinterpreted as base58 values. Reverse case is quite rare, so it is better to try hex decoding first.

Prioritize hex decoding over base58 in keyer

---

pkg/innerring/innerring.go

Extra blocks for notary deposit must not be less than extra blocks at notary tx rounding.
Consider you make notary deposit every 1000 block for next 1100 blocks. At block 555 you made notary deposit up to 1655.
At block 1554 you want to send notary tx. Notary client uses rounding to calculate `until` value. By default notary client rounds with up to 150 block ahead, thus for tx at 1554 `until` will be 1700.
1700 is bigger than deposit limit at 1655 and tx will fail. However if extra blocks for notary deposit will be 200, then this case
won't be possible.

Increase duration of notary deposit

---

pkg/morph/client/client.go
pkg/morph/client/notary.go

neo-go JSON RPC server expect all hashes in LE, e.g. in `getapplicationlog` method.

Print transaction hashes in LE

---

cmd/neofs-ir/defaults.go
cmd/neofs-node/reputation.go
go.mod
go.sum
pkg/innerring/innerring.go
pkg/innerring/invoke/enhanced.go
pkg/innerring/processors/reputation/handlers.go
pkg/innerring/processors/reputation/process_put.go
pkg/innerring/processors/reputation/processor.go
pkg/morph/client/reputation/client.go
pkg/morph/client/reputation/get.go
pkg/morph/client/reputation/list.go
pkg/morph/client/reputation/put.go
pkg/morph/client/reputation/wrapper/get.go
pkg/morph/client/reputation/wrapper/list.go
pkg/morph/client/reputation/wrapper/put.go
pkg/morph/client/reputation/wrapper/wrapper.go
pkg/morph/event/reputation/put.go
pkg/morph/event/reputation/put_test.go
pkg/network/transport/reputation/grpc/service.go
pkg/services/reputation/rpc/response.go
pkg/services/reputation/rpc/server.go
pkg/services/reputation/rpc/sign.go

Related to https://github.com/nspcc-dev/neofs-contract/pull/65

Support updated reputation contract

---

pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/delete_test.go

`Inhume` operation can be performed on already deleted objects, and in this
case the entry will be added to the graveyard. `Delete` operation finishes
with error if object is not presented in metabase. However, the entry in the
cemetery must be deleted regardless of the presence of the object.
Additionally, now `Delete` does not return an error in the absence of an
object.
Closes #461.

metabase: Delete graves regardless of the presence of objects

---

cmd/neofs-ir/defaults.go
pkg/innerring/config/config.go
pkg/innerring/innerring.go
pkg/innerring/processors/neofs/process_assets.go
pkg/innerring/processors/settlement/audit/calculate.go
pkg/innerring/processors/settlement/audit/prm.go
pkg/innerring/processors/settlement/basic/collect.go
pkg/innerring/processors/settlement/basic/distribute.go
pkg/innerring/processors/settlement/common/details.go
pkg/innerring/processors/settlement/common/details_test.go
pkg/innerring/processors/settlement/common/types.go
pkg/innerring/processors/settlement/common/util.go
pkg/innerring/settlement.go
pkg/morph/client/netmap/wrapper/config.go

At settlement processing, alphabet nodes will transfer `AuditFee` from container owner to inner ring node that performed audit. `AuditFee` value takes from global configuration in network map contract.
Also this PR unifies format of transfer details.  Unified format uses transfer type as the first byte and extra details next. List of transfer types used in contracts defined in `details.go`. It includes:
- audit settlement,
- basic income collection,
- basic income distribution.
Closes #464

Add audit fee in settlement and unify transfer detail format

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go

If `shutdown.offline.enabled` config option set to true, then  send netmap.UpdateState(offline) tx at the shutdown. This config
option is not set by default.
Fixes #462

Don't send UpdateState tx at shutdown by default

---

pkg/local_object_storage/engine/engine_test.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/head.go
pkg/local_object_storage/engine/head_test.go
pkg/local_object_storage/engine/range.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/util/splitinfo.go
pkg/local_object_storage/util/splitinfo_test.go

Closes #391
Issue fixed for head, get and range requests.
Unit test covers `engine.Head` invocation.

Iterate over all shards to return complete SplitInfoError

---

pkg/innerring/blocktimer.go
pkg/innerring/config/config.go
pkg/innerring/innerring.go
pkg/innerring/invoke/netmap.go
pkg/morph/client/netmap/wrapper/config.go
pkg/morph/client/util.go
pkg/morph/client/util_test.go

This pull request:
- adds more getters for global config values in netmap wrapper,
- makes inner ring block timer use global config to fetch epoch duration value,
- fixes configuration value sync between main chain and side chain.
Related to #363

Fetch epoch duration from global config

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go
cmd/neofs-node/morph.go
cmd/neofs-node/reputation.go
cmd/neofs-node/timers.go
pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/morph/timer/block.go
pkg/morph/timer/block_test.go

There is a small inconsistency that can happen in neofs-dev-env environment with timer calculation. Storage node takes epoch duration from global config, however inner ring may override this value in local config. In this case eigen trust iteration duration won't be correlated with actual epoch duration.
To fix that, I plan to remove epoch duration value from inner ring config in neofs-dev-env and provide simple functionы to change global config values (similar to `make prepare.ir`).

Eigen trust timer in storage node

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go

Control service turns storage node to online and offline modes. We can't reuse `cfgNetmap.reBootstrapEnabled` because it represents configuration value while control service manages state in runtime.
Closes #470

Do not send rebootstrap after node went offline

---

cmd/neofs-node/config.go

Close #471.
Disable bootstrapping completely by setting `bootstrap.relay_only: true`

[#471] cmd: allow to start node as Relay node

---

pkg/services/object/get/assemble.go
pkg/services/object/get/exec.go
pkg/services/object/get/prm.go
pkg/services/object/get/util.go
pkg/services/object/get/v2/service.go
pkg/services/object/get/v2/util.go
pkg/services/object/search/exec.go
pkg/services/object/search/prm.go
pkg/services/object/search/util.go
pkg/services/object/search/v2/util.go

In previous implementation node's Object Search V2 service handler created a
new request for each RPC. Now original requests are re-signed according to
API specification. Logical handler abstracts from this version-dependent
logic through `RequestForwarder` callback.

object/search: Re-sign original requests during forwarding

---

cmd/neofs-cli/modules/root.go
cmd/neofs-node/container.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation/common/remote.go
pkg/innerring/processors/audit/process.go
pkg/innerring/rpc.go
pkg/network/address.go
pkg/network/address_test.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object/head/remote.go
pkg/services/object/put/remote.go
pkg/services/object/search/exec.go
pkg/services/object/search/search_test.go

Related to https://github.com/nspcc-dev/neofs-node/issues/455
To enable TLS support we can't operate with IP addresses directly. Certificates are issued with host names so it is required to
pass them into RPC client. DNS resolving should be done by transport layer and not be a part of node. Therefore `IPAddrString` usage is removed from code.
Also there is fix for incorrect port-only host address parsing (`:8080`). This leads to `/dns4/tcp/8080` multiaddress which is incorrect. In this case `dns4` section should be omitted, but it breaks `manet.DialArgs`. To solve this issue we explicitly set 0.0.0.0 address.

Use host addresses as transport endpoints

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/acl_test.go

Fixes #548 
When storage node re-sends requests, it creates new layer in request meta header chain. New layer does not contain tokens but container link to the original request meta header. ACL service should traverse to the original request meta header to fetch relevant session and bearer tokens.

Traverse request meta headers to fetch tokens in ACL checker

---

cmd/neofs-cli/modules/root.go
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/grpc.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation/common/remote.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/audit/processor.go
pkg/innerring/rpc.go
pkg/network/address.go
pkg/network/address_test.go
pkg/network/cache/client.go
pkg/network/tls.go
pkg/network/tls_test.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go
pkg/services/object/head/remote.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/search/exec.go
pkg/services/object/search/search_test.go
pkg/services/object/search/service.go
pkg/services/object/search/util.go

Add TLS(turns on with config(env vars)) to GRPC server and client.
In `network` pkg add implementation of `tls` protocol for `multiaddr` lib.
Make CLI support multiaddresess with `/tls` protocol.
Closes #455.

Feature/add TLS encryption

---

pkg/innerring/processors/container/common.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/container/process_eacl.go

Session token can be presented `Put`, `Delete` and `SetEACL` notification
events. IR should consider this case as issuing a power of attorney to a
third party. Thus, checking the eligibility for an operation should be
complicated:
- token owner should be the owner of the related container;
- the intent must be signed with a session key;
- the power of attorney must be signed by the owner of the container.
Omitted checks (TBD):
- session token should have container session context;
- the verb of the context should correspond to the operation.

Verify container operations with session token

---

cmd/neofs-cli/modules/container.go
cmd/neofs-cli/modules/util.go

Use case:
```
$ neofs-cli util sign session-token -k issuer.key --from token.json --to stoken.json
signed session token saved in stoken.json
$ neofs-cli -r s01.neofs.devenv:8080 -k sender.key container create -p rule.ql --session stoken.json --await
container ID: 9EN4iiLHpCRkbqseKDEDCeQMUHzh4Wno796vcjADNRuV
awaiting...
container has been persisted on sidechain
```
Token example:
```json
{
"body": {
"id": "KNiz/TYNTkib7TvBHcFevQ==",
"ownerID": {
"value": "NU+8+vi5RqUFhQmDHeJQf4IIzl1i6BAmXQ=="
},
"lifetime": {
"exp": "100500",
"nbf": "1",
"iat": "1"
},
"sessionKey": "Axpsb7vfAso1F0X6hrm6WpRS14WsT3/Ct1SMoqRsT89K",
"container": {
"verb": "PUT",
"wildcard": true
}
}
}
```

Add command to sign session tokens

---

.github/workflows/go.yml
Makefile
go.sum

Flag `-i` is deprecated in go1.16 and it had pretty much no effect since go1.10 when build cache was introduced. Read more about
this at https://golang.org/doc/go1.16

Remove test_dep target

---

cmd/neofs-ir/defaults.go
cmd/neofs-ir/main.go
misc/build.go
pkg/innerring/config/config.go

Closes #363 
This PR finishes transition to global config in inner ring node. All global config values have corresponding local config values, but they are active **only in debug build**. To make debug build try:
```
$ DEBUG=true make bin/neofs-ir
```
There are couple more changes there as well. First we came up with values for out timers in testnet and neofs-dev-env so it makes sense to make them default. Also we changed storage node config and it can't turn off or specify length of bootstrap healthchecks, so it also reflected in inner ring config.

Update inner ring config

---

CHANGELOG.md
config/testnet/docker-compose.yml
go.mod
go.sum

Master branch is broken now but we have to release public node with VMagent.

Backport v0.21.1 release

---

pkg/morph/client/client.go
pkg/morph/client/notary.go

Test invocations are used in `Invoke` method to calculate consumed gas. We can check return code and return error if panic happened in contract. 
This is already done the same way in `TestInvoke` method.

morph/client: Check return state in invoke

---

go.mod
go.sum
pkg/local_object_storage/blobovnicza/sizes.go

Relates to #600.
```
after
creating bucket for size range	{"component": "Blobovnicza", "range": "[0:32768]"}
before
creating bucket for size range	{"component": "Blobovnicza", "range": "[0:32K]"}
```

blobovnicza: Simplify byte size stringer

---

Makefile

Delete useless `CMS` var in Makefile.

Fix/delete useless var in Makefile

---

pkg/innerring/innerring.go
pkg/morph/client/neofs/wrapper/client.go
pkg/morph/client/neofsid/wrapper/client.go

Audit client should sign all transaction by node's key and do not use multisignature.

Do not use notary in audit client

---

cmd/neofs-cli/modules/container.go
go.mod
go.sum
pkg/core/container/fmt.go
pkg/core/version/version.go
pkg/core/version/version_test.go
pkg/services/container/morph/executor.go
pkg/services/netmap/executor.go

Update to API Go v1.28.1

---

pkg/innerring/processors/audit/process.go

fix/Skip audit for containers without SG

---

cmd/neofs-adm/internal/modules/config/config.go
cmd/neofs-adm/internal/modules/config/config_test.go
cmd/neofs-adm/internal/modules/config/root.go
cmd/neofs-adm/internal/modules/root.go
cmd/neofs-adm/main.go
pkg/innerring/alphabet.go
pkg/innerring/innerring.go
pkg/innerring/state.go

Build with `make bin/neofs-adm`.
```
$ ./bin/neofs-adm config init 
Initial config file saved to /home/alexvanin/.neofs/adm/config.yml
$ cat /home/alexvanin/.neofs/adm/config.yml 
rpc-endpoint: https://neo.rpc.node:30333
alphabet-wallets: /home/alexvanin/.neofs/adm/alphabet-wallets
network:
max_object_size: 67108864
epoch_duration: 240
credentials:
az: password
buky: password
vedi: password
glagoli: password
dobro: password
yest: password
zhivete: password
$ ./bin/neofs-adm config init --path ./.neofs-adm.yaml
Initial config file saved to ./.neofs-adm.yaml
```

Initial commit for neofs-adm utility

---

CHANGELOG.md
docs/release-instruction.md
pkg/innerring/innerring.go

If `WITHOUT_MAINNET` environmental variable is
`true`:
- Do not read `NeoFS` and `processing`
script-hashes from envs;
- Do not init Governance processor;
- Do not init NeoFS processor.
Clarify tag section in release instruction.
Closes #663.

Fix/Do not require MainNet attributes in `WITHOUT_MAINNET` mode

---

CHANGELOG.md
cmd/neofs-node/config/node/config.go
cmd/neofs-node/config/node/config_test.go

Some users want to specify only wallet section in the SN. It is not possible if `Key` throws panic on empty value. Instead it should
fallback to wallet section. Panic is suitable if node's key is provided but invalid.

Fallback to wallet section if storage node's key is not set

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation.go
pkg/network/cache/multi.go

Closes #692 
First commit fixes issue with connection leak.
Second commit reduces amount of total connections by reusing the same client cache in all storage node components.

Reduce amount of open connections in storage node

---

pkg/innerring/processors/governance/list.go
pkg/innerring/processors/governance/list_test.go

We should go through every key in main chain list to merget lists as fast as possible. Previously we drop main chain traversing as
soon as we have no more new keys to add. Instead we should try to go for old keys in the list and add it as more as we can.
In previous implementation test will produce `k[0], k[1], k[2], k[3], k[4], k[6], k[7]` which is sub optimal and it will take more iteration to converge. This PR fixes it and full main chain list traversal will produce expected result in one iteration.

Make best effort traversing main chain list of keys

---

pkg/innerring/innerring.go
pkg/morph/client/client.go
pkg/morph/client/netmap/client.go
pkg/morph/client/netmap/epoch.go
pkg/morph/client/netmap/wrapper/epoch.go
pkg/morph/timer/block.go
pkg/morph/timer/block_test.go

Closes #679 
At the startup, Inner Ring application calculates block duration before next epoch tick and processes new epoch event at this block.

Sync first epoch duration at application startup

---

pkg/morph/client/notary.go

Closes #677 
For easier debug when notary transaction didn't execute.

moprh/client: Log VUB in notary invocations

---

config/testnet/config.yml

[neofs-storage-testnet:0.23.0](https://hub.docker.com/layers/nspccdev/neofs-storage-testnet/0.23.0/images/sha256-a5374e19fe7bf0bf8d947a464c21a20d4df5c9a8b2a08c71a9c2523978ab5f3c?context=repo) image has been reupload with these changes.

config/testnet: Fix ports

---

cmd/neofs-adm/internal/modules/morph/dump.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/root.go

Also set hashes of all alphabet contracts.
```
alphabet 0:  58e305a68eea2c5f1e8d6b94f61ce79db4036e5c
alphabet 1:  a1e03470cdaac3d093c1774d681357f7f6e72127
alphabet 2:  8be6184611cf9b264c39dde763486b96870840f4
alphabet 3:  e8e714a7d278ec93c3c0242458fb449a4c06e8f3
audit:       bc086562cd491ec86e15a808a43bba571ae378cd
balance:     22a5d1a3b456b45fdb5ec37aca35dcc92bad96f7
container:   45c30c8af952541aadabdcef8c9edc651dd6ddd2
neofsid:     ae6e6056e4e2e911b1e7a3b59ed1913675ad4bf5
netmap:      b5b3144938f745e5743c4130d3a1e912a2331d1b
proxy:       febf124409abb1aad6f32e2fba70e867cefd161b
reputation:  51ef954a1e34c6b5d59750c3ed9cf720c04433ea
```

neofs-adm: dump deployed contract hashes from NNS

---

pkg/services/container/announcement/load/storage/storage.go

Use `Epoch` and `ContainerID` as announcement storage key.
@alexvanin

container/announcement/storage: Map announcements by epoch and container id

---

cmd/neofs-adm/internal/modules/config/config.go
cmd/neofs-adm/internal/modules/config/config_test.go
cmd/neofs-adm/internal/modules/morph/dump.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/root.go
go.mod
go.sum

Config example:
```
$ cat neofs-adm.yml 
rpc-endpoint: http://morph_chain.neofs.devenv:30333
alphabet-wallets: /home/alexvanin/Project/NeoFS/neofs-node/bin/alphabets
network:
max_object_size: 67108864
epoch_duration: 50
basic_income_rate: 5000
fee:
audit: 333333
candidate: 4444444
container: 555555
withdraw: 666666
credentials:
az: onetwo
```
Command output example:
```
./neofs-adm -c neofs-adm.yml morph dump-config
AuditFee:               333333 (int)
BasicIncomeRate:        5000 (int)
ContainerFee:           555555 (int)
EigenTrustAlpha:        0.1 (str)
EigenTrustIterations:   4 (int)
EpochDuration:          50 (int)
InnerRingCandidateFee:  4444444 (int)
MaxObjectSize:          67108864 (int)
WithdrawFee:            666666 (int)
```

More network configuration parameters in neofs-adm

---

pkg/util/attributes/parser.go
pkg/util/attributes/parser_test.go

util/attributes: Support escaped symbols

---

cmd/neofs-adm/internal/modules/config/util.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/initialize.go

Fix/Support reading paths with `~` for Alphabet wallets in neofs-adm

---

pkg/services/policer/queue.go

Closes #715.
In previous implementation of Policer's job queue the same list of objects for
processing was selected at each iteration. This was caused by consistent
return of `engine.List` function.
Use `rand.Shuffle` function to compose pseudo-random list of all objects in
order to approximately evenly distribute objects to work.

services/policer: Select pseudo-random list of objects to check

---

cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/root.go

Closes #758.
Add `refill-gas` sub-command to `morph` command which provides the ability
to refill storage node's GAS.
Command performs some actions from `generate-storage-wallet` runner, so
common code is moved to separate functions.

adm: Implement command to refill storage node's GAS

---

cmd/neofs-node/cache.go
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/object.go
pkg/services/container/morph/executor.go

Closes #676.
In previous implementation Container service handlers didn't cache the
results of `Get` / `GetEACL` / `List` operations. As a consequence of this,
high load on the service caused neo-go client's connection errors. To avoid
this there is a need to use cache. Object service already uses `Get` and
`GetEACL` caches.
Implement cache of `List` results. Share already implemented cache of Object
service with the Container one. Provide new instance of read-only container
storage (defined as an interface)to morph executor's constructor on which
container service is based. Write operations remained unchanged.

Cache the results of Container read operations

---

pkg/util/attributes/parser.go
pkg/util/attributes/parser_test.go

This PR fixes:
1. inconsistent order of the returned attributes,
2. multiple attribute parent support.
As for (1), attributes does not require any special order, because they are linked together with `Parents` field. However for the tests it would be better to have consistent parsing function, so we won't see any 
```
Error Trace:	parser_test.go:67
Error:      	Not equal: 
expected: "Ke/y2"
actual  : "K:ey1"
```
errors.
As for (2), previously we didn't reuse existing attributes so the `Parents` list will have at most one record. 
It is better to review per commit than whole PR.

Fix attribute parser issues

---

cmd/neofs-node/container.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation.go
cmd/neofs-node/reputation/common/remote.go
pkg/core/netmap/keys.go
pkg/network/address.go
pkg/services/object/get/container.go
pkg/services/object/put/distributed.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object/search/container.go
pkg/services/object/util/placement.go
pkg/services/object_manager/placement/traverser.go
pkg/services/object_manager/placement/traverser_test.go
pkg/services/policer/check.go
pkg/services/policer/policer.go

Related #645.
In current neofs-api-go and SDK state 5 and 6 points of issue are hard to implement , so I didn't touched them.

Use public key comparison as a locality criterion

---

pkg/morph/event/container/put_notary.go
pkg/morph/event/notary_preparator.go

Do not pass call flags to the notary requests parsers.
Also, fix parameter amount check in `Put` event.

Fix/Ignore call flags in Notary Requests

---

pkg/services/object/acl/eacl/validator.go
pkg/services/object/acl/eacl/validator_test.go

Fix #816.
Ignore role if public keys are present.

object/acl: fix eACL target processing

---

pkg/services/object/put/distributed.go

Return the composite error of PUT operation

---

pkg/morph/event/container/delete_notary.go
pkg/morph/event/container/eacl_notary.go
pkg/morph/event/container/put_notary.go
pkg/morph/event/notary_preparator.go
pkg/morph/event/notary_preparator_test.go
pkg/morph/event/opcodes.go
pkg/morph/event/opcodes_test.go

Do not pass high-level `PACK` opcode to notary parsers. Also add unit test for correct NR preparing by `NotaryPreparator`

Fix/Cut `PACK` opcodes in notaryPreparator

---

cmd/neofs-node/config.go
cmd/neofs-node/config/contracts/config.go
cmd/neofs-node/config/contracts/config_test.go
cmd/neofs-node/morph.go
pkg/innerring/contracts.go
pkg/innerring/innerring.go
pkg/morph/client/nns.go

Closes #736
This PR contains:
- new `client.NNSContractAddress()` from `morph/client` that resolves `TXT` record of NNS contract from the contract with ID:1
- bunch of `client.NNS*ContractName` constants and `client.NNSAlphabetContractName()`,
- the usage of `client.NNSContractAddress()` in Storage and Inner Ring node applications.
NNS contract only used when applications miss some configuration record of contract script hash. Local config values override NNS values.

Smart contract script hash auto negotiation

---

pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/delete_big.go
pkg/local_object_storage/blobstor/put.go
pkg/local_object_storage/internal/log/log.go
pkg/local_object_storage/writecache/delete.go
pkg/local_object_storage/writecache/options.go
pkg/local_object_storage/writecache/persist.go
pkg/local_object_storage/writecache/put.go
pkg/local_object_storage/writecache/storage.go

Closes #790.
Unified message head is hard-coded to `local object storage operation`. Log level is hard-coded to `Info`.

Unify storage engine logs

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

Contract owner is removed from deployment arguments. This PR also fixes bug when `proxy` contract used incorrect deployment arguments. 
Related to https://github.com/nspcc-dev/neofs-contract/issues/107

Do not specify owner in the contract deployment

---

pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/morph/client/notary.go

`WithSingleClient` allows Morph client creation with existing raw neo-go client.
Can be used for applications that use more than one `Morph` client and do not want to create multiple neo-go clients.

Feature/Add `WithSingleClient` client constructor option

---

pkg/services/object/get/assemble.go
pkg/services/object/get/exec.go
pkg/services/object/get/util.go

Forwarding mechanism resends original request. During split object chain traversal, storage node performs multiple object.Head requests on each child. If request forwarding happens, then object.Head returns object ID of the original request. This produces infinite assembly loop.
---
This reproduced when storage node has only most right child. It tries to build the chain by using `headChild` function for all children in the chain. The problem is with `err := exec.svc.Head(exec.context(), prm)` function there. This function creates new execution context which has unset assembly flag by default. However forwarder is not nil, thanks to common parameters there. 
The fun part if you go deeper and try to add panic in `processNode`:
```go
func (exec *execCtx) processNode(ctx context.Context, addr …
```

service/object: Do not use request forwarding when assembling object

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/update.go

Fix #835 .  Checked init + update-contracts, no errors. NNS contract `_deploy` routine should be changed in the next release, for further updates to work.

[#835] neofs-adm: rename contract update method

---

cmd/neofs-node/container.go
pkg/services/container/announcement/load/route/placement/calls.go

Containers with one storage node do not produce size estimations. The reason is that load controller uses `nopLoadWriter` which loses the data. It does not accumulated in storage and therefore does not announced to the container contract, which is incorrect.

cmd/neofs-node: Don't lose local container size estimations

---

pkg/innerring/innerring.go
pkg/innerring/internal/client/client.go
pkg/innerring/internal/client/doc.go
pkg/innerring/internal/client/prm.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/audit/processor.go
pkg/innerring/rpc.go

Indirectly refers to status returns: the upcoming interface breakdown will be easier to pull in.
It should be noted that the familiar approach with explicit `context.Context` passing is applied in the helper functions.
You can also notice that reading the entire object and only the header are combined in one method, since these operations are fairly homogeneous. In any case, they are separated at the level of global functions. The unification is done through the interface casts, which may not be the best approach (weakening of types), however, for now, you should concentrate on the overall goal of the PR. After updating the client library, it will be possible to rethink the implementation of the wrapper.

ir: Refactor usage of NeoFS API client

---

pkg/local_object_storage/writecache/delete.go
pkg/local_object_storage/writecache/persist.go
pkg/local_object_storage/writecache/put.go
pkg/local_object_storage/writecache/storage.go
pkg/local_object_storage/writecache/writecache.go

a1696a8 introduced some logic which in some situations prevented big objects
to be persisted in FSTree. In this commit a refactoring is done with the
goal of simplifying the code and also checking #866 issue.
1. Split a monstrous function into multiple simple ones: memory objects
can only be small and for writing through the cache we can do a dispatch
in `Put` itself.
2. Determine objects to be put in database before the actual update
as setting up a transaction has non-zero overhead.
Fix #866.
Testing done:
1. Restrict max cache size.
2. Put both small and big objects.
3. Check that writecache size doesn't exceeds the max size, but has objects put to FSTree and database.

writecache: refactor object persisting

---

pkg/util/locode/db/continents/geojson/calls.go

locode: Use the nearest polygon when continent can't be found

---

pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/innerring/notary.go
pkg/innerring/processors/netmap/handlers.go
pkg/innerring/processors/netmap/process_epoch.go
pkg/innerring/processors/netmap/processor.go

Related to #910 
During v0.26.1 pre release testing, I saw this warning in IR logs:
```
warn    innerring/blocktimer.go:106     can't stop epoch estimation     {"epoch": 17, "error": "could not invoke method (stopContainerEstimation): failed to submit notary request: Block or transaction validation failed. (-504) - fallback transaction is valid after deposit is unlocked: V
alidUntilBlock is 3300, deposit lock expires at 3245"}
```
Turns out, that notary deposit did not trigger by new epoch event. Instead deposits were triggered by epoch timer. It is not correct, because timer can never fire up, due to desynchronization or external epoch changes.

Make notary deposit on notification instead of timer

---

cmd/neofs-cli/modules/util.go

cli/locode: Open RO database in `info` command

---

pkg/local_object_storage/blobstor/blobstor_test.go

Init stage takes up to 10 seconds. Compression test does not require wide blobovnicza tree.

[#868] blobstor: Speed up compression test

---

pkg/core/object/errors.go
pkg/local_object_storage/engine/control_test.go
pkg/local_object_storage/engine/engine_test.go
pkg/local_object_storage/engine/list.go
pkg/local_object_storage/engine/list_test.go
pkg/local_object_storage/metabase/list.go
pkg/local_object_storage/metabase/list_test.go
pkg/local_object_storage/shard/list.go
pkg/local_object_storage/shard/shard_test.go

Object listing operation is required for replication mechanism. Replicator iterates over available physically stored object and tries to verify and restore placement policy for each of them.
Current listing mechanism is quite inefficient. Engine provides `List` method that gathers **all** available objects from every shard. Replicator uses it without the count limit, so it may create giant list of object addresses.
```go
res, err := engine.List(q.localStorage, 0) // res contains all available object addresses in the node
if err != nil {
return nil, err
}
```
The better way is to iterate over small chunks of object addresses using cursor. This PR implements such listing operations on metabase, shard and storage engine. 
```go
prm := new(ListObjectsWithCursorPrm).WithCount(10)
res, err := …
```

Storage engine `ListWithCursor` implementation

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/services/policer/check.go
pkg/services/policer/policer.go
pkg/services/policer/process.go
pkg/services/policer/queue.go
pkg/services/replicator/process.go

Continuous replication

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go

1. Compare `NEF.Checksum` to check if contract is updated.
2. Replace `addRoot` with `register` in NNS.
3. Compare hashes written to NNS properly.

neofs-adm: fixes for contract update

---

cmd/neofs-node/config/grpc/config.go
cmd/neofs-node/config/grpc/config_test.go
cmd/neofs-node/grpc.go
config/example/node.json
config/example/node.yaml

Close #878 .
Support TLS >=1.2 only and strong cipher suites.
I have also checked NIST recommendations (
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r2.pdf), but they are less strict and include ciphers considered insecure by go stdlib.
I don't think allowing user to precisely specify cipher suites is worth it.

[#878] neofs-node: default to secure TLS settings

---

CHANGELOG.md

For rc.1 we need to finish tasks from [v0.27.0 milestone](https://github.com/nspcc-dev/neofs-node/milestone/30)
Then before the release I think we need to:
- test subnetworks and status code compatibility in notary disabled environment.
- remove internal client in CLI app according to https://github.com/nspcc-dev/neofs-node/pull/950#pullrequestreview-796681663
- https://github.com/nspcc-dev/neofs-node/issues/915
- provide some docs (maybe even medium article?) about sub networks for the storage node users,
- maybe https://github.com/nspcc-dev/neofs-node/issues/991

Release candidate v0.27.0-rc.1

---

pkg/local_object_storage/metabase/small.go

According to BoltDB documentation bucket `value is only valid for the
life of the transaction`.
Make `DB.IsSmall` copy value slice in order to prevent potential memory
corruptions (e.g. `runtime.stringtobyteslice` cast).
* Closes #1007

metabase: Copy BoltDB value returned by IsSmall

---

pkg/local_object_storage/writecache/flush.go

* Relates #915
`Writecache` periodically successfully wrote the same objects to the `BlobStor`.

writecache: Fix repetitive `BlobStor` writes

---

pkg/services/policer/process.go

When application is being terminated, replicator routine might be on the object picking phase. Storage is terminated asynchronously, thus `Select()` may return corresponding error. If we don't process `context.Done()` in this case, then application freezes on shutdown.
Related to #1042

policer: Check context before job selection

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

The updated version of the `NNS` contract now supports the third `data`
argument that may provide additional information.
Related to https://github.com/nspcc-dev/neofs-contract/issues/197

Feat/Do not cut deploy args in `NNS`

---

pkg/services/container/morph/executor.go
pkg/services/container/morph/executor_test.go

Without sanity check, container service provides successful response, even though such request will never be approved by Alphabet nodes.
Closes #1045

Provide sanity check of session token in container service

---

cmd/neofs-node/config.go
cmd/neofs-node/config/engine/config_test.go
cmd/neofs-node/config/engine/shard/config.go
config/example/node.env
config/example/node.json
config/example/node.yaml
pkg/local_object_storage/shard/delete.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/inhume.go
pkg/local_object_storage/shard/mode.go
pkg/local_object_storage/shard/move.go
pkg/local_object_storage/shard/put.go
pkg/local_object_storage/shard/shard.go

Related to #1044. Deleted unused shard modes and suggest adding them when needed. Do not know if shard should be able to tick its `GC` (and remove objects) and accept `Inhume()` calls when it's in `read-only` mode or not.

Feat/Add read-only shard mode

---

cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/update.go

Close #1035.
Same thing is desireable for deploy, but alphabet contracts have to be deployed from different senders to have different hash. Also contrary to `update` network starts to function only after all contracts were deployed, so there we won't end in an inconsistent state.

neofs-adm: update contracts in a single transaction

---

cmd/neofs-adm/internal/modules/morph/subnet.go
cmd/neofs-node/morph.go
pkg/innerring/processors/audit/process.go
pkg/morph/client/notary.go
pkg/services/audit/auditor/pdp.go
pkg/services/audit/auditor/por.go
pkg/services/audit/auditor/util.go
pkg/util/rand/rand.go

It is much more convenient to skip source creation.
Also fix some bugs:
1. `cryptoSource.Int63()` now returns number in `[0, 1<<63)` as required
by `rand.Source` interface.
2. Replace `cryptoSource.Uint63()` with `cryptoSource.Uint64` to allow
generate uint64 numbers directly (see rand.Source64 docs).

[#851] util/rand: use single random source

---

pkg/services/object/get/assemble.go

Closes #1077 
Reverse payload overtake triggers direct payload overtake that sets status and error. We should not override that.

service/object: Don't override status of payload overtake

---

pkg/local_object_storage/writecache/persist.go

[#1088] writecache: Fix small flushed mark

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/key_test.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/util.go

Currently have static priority of what key is used irregardless of
whether a flag was provided via CLI or in config. This makes it
impossible to override some of the config settings. While we could try
to check if the key is provided by CLI by binding CLI flag under to
viper under a different name the same problem would occur for config/environment
variables. Fixing all of this with current set of keys is too complicate.
In this commit we revert changes from #610 and use a single flag for all types of keys.

[#1083] neofs-cli: use single flag for key and wallet

---

pkg/services/object/sign.go

object/search: Fix error loss in `SignService.Search`

---

Makefile

Remove warning and prevent `go.mod` updates when building `protoc` target.

Makefile: use `go install` instead of `go get`

---

pkg/local_object_storage/blobovnicza/iterate.go
pkg/local_object_storage/blobovnicza/iterate_test.go
pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/fstree/fstree_test.go
pkg/local_object_storage/blobstor/iterate.go
pkg/local_object_storage/blobstor/iterate_test.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/dump.go
pkg/local_object_storage/shard/dump_test.go
pkg/local_object_storage/shard/evacuate.go
pkg/local_object_storage/shard/evacuate_test.go
pkg/local_object_storage/shard/head_test.go
pkg/local_object_storage/shard/mode.go
pkg/local_object_storage/shard/restore.go
pkg/local_object_storage/shard/shard_test.go
pkg/local_object_storage/shard/shutdown_test.go
pkg/local_object_storage/writecache/delete.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/iterate.go
pkg/local_object_storage/writecache/mode.go
pkg/local_object_storage/writecache/persist.go
pkg/local_object_storage/writecache/put.go
pkg/local_object_storage/writecache/writecache.go

Close #1085 . Related #1057 . Depends on #1088 .
Proto-marshaled list is not an option because it requires (let's be realistic) having the slice in memory.
I decided to not use TAR archives because of 512-byte header overhead for each object. It is noticeable only when lot's of small objects without attributes are present, though.

Allow to dump data from shard

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

Same as previously reverted #1038. Is actual for `v0.14.0` contract version.

Do not cut `data` args in `NNS`

---

cmd/neofs-cli/modules/accounting.go
cmd/neofs-cli/modules/control.go
cmd/neofs-cli/modules/root.go
cmd/neofs-cli/modules/util.go

Closes #1083.
It was broken since `initConfig` was made before every execution of the 
command and flags have not been read by cobra yet, so it was impossible to 
print config file path if `verbose` flag was set in command line not in 
config file.

Fix/Printing config file in `verbose` mode

---

cmd/neofs-adm/internal/modules/root.go
cmd/neofs-adm/internal/modules/storagecfg/config.go
cmd/neofs-adm/internal/modules/storagecfg/root.go
go.mod
go.sum

neofs-adm: add interactive configurator for storage node

---

cmd/neofs-node/session.go
pkg/services/session/storage/storage.go

[#1133] services/session: remove expired tokens every epoch

---

cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/group.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/subnet.go
cmd/neofs-node/morph.go
pkg/innerring/innerring.go
pkg/morph/client/client.go
pkg/morph/client/nns.go
pkg/morph/client/static.go

Specify custom signer scope for morph invocations

---

cmd/neofs-cli/modules/container.go

[#1182] neofs-cli: use `BasicACL.String()` for user output

---

cmd/neofs-cli/modules/acl/extended/create.go

cli: Mention filter key prefixes in eACL creation command

---

pkg/local_object_storage/engine/engine_test.go
pkg/local_object_storage/engine/put.go

Close #1146 .
Benchmark results on my laptop (all shards are on a single SSD).
```
name               old time/op    new time/op    delta
Exists/2_shards-8    25.4µs ± 3%    31.7µs ±16%  +25.07%  (p=0.000 n=10+10)
Exists/4_shards-8    49.2µs ± 7%    48.1µs ±12%     ~     (p=0.579 n=10+10)
Exists/8_shards-8    93.4µs ± 1%    69.9µs ±25%  -25.22%  (p=0.000 n=10+9)
name               old alloc/op   new alloc/op   delta
Exists/2_shards-8    4.98kB ± 0%    5.22kB ± 0%   +4.83%  (p=0.000 n=10+10)
Exists/4_shards-8    9.42kB ± 1%    9.85kB ± 1%   +4.58%  (p=0.000 n=10+10)
Exists/8_shards-8    18.2kB ± 1%    19.0kB ± 0%   +4.40%  (p=0.000 n=10+9)
name               old allocs/op  new allocs/op  delta
Exists/2_shards-8       111 ± 1%       120 ± 0%   +7.37%  (p=0.000 n=10+10)
Exists/4_shards-8 …
```

Check for object existence in parallel

---

pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/get_range_big.go
pkg/local_object_storage/engine/error_test.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/range.go
pkg/local_object_storage/shard/get.go
pkg/local_object_storage/shard/range.go

Fix #1186.
Metabase is expected to contain actual information about objects stored
in shard. If the object is present in metabase but is missing from
blobstor, peform an additional attempt to fetch it directly without
consulting metabase. Such a situation is unexpected, so error counter
is increased for the shard which has the object in the metabase. We
don't increase error counter for the shard which has the object in
blobstor, because some garbage can be expected there. In this
implementation there is no overhead for objects which are really
missing, i.e. are not present in any metabase.

[#1186] engine: read object directly from blobstor in case of conflicts

---

pkg/local_object_storage/engine/control_test.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/metabase/shard_id.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/id.go
pkg/local_object_storage/shard/shard.go

Close #1204 .
What I don't like about this solution is that metabase is opened when updating shard ID. Ideally we want not to perform update operations until `Init` is run. However, implementing this properly leads to significant refactoring.

Save shard IDs in metabase

---

pkg/services/object/acl/v2/errors.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/util.go
pkg/services/object/acl/v2/util_test.go

object/acl: check session token verb

---

cmd/neofs-node/cache.go

We already use thread-safe LRU and mutex shouldn't be taken while making
network requests.

neofs-node: remove mutex from `lruNetCache`

---

cmd/neofs-cli/modules/util.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/v2/errors.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/types.go

object/acl: return more concise description for eACL errors

---

pkg/network/address.go
pkg/network/address_test.go

Fix linter complaints. These constants are unused after
nspcc-dev/neofs-node#1232.

network: remove unused constants

---

cmd/neofs-node/main.go
cmd/neofs-node/notificator.go
pkg/services/notificator/nats/options.go
pkg/services/notificator/nats/service.go

Close #1244.
Create and connect to an endpoint using separate functions.

[#1244] nats: Split client creation into 2 stages

---

cmd/neofs-cli/internal/client/client.go

Close #1198.
The buffer size value is somewhat arbitrary and making in configurable
doesn't make much sense, given that we can't really restrict total resource
consumption in other places. `Copy` uses 32 KiB buffer by default, which
is not big. This approach is also more flexible as we can get rid of
buffer completely by implementing `ReaderFrom`, `WriterTo` interfaces.

[#1198] neofs-cli: Use `io.Copy` instead of `io.CopyBuffer`

---

cmd/neofs-node/cache.go
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/control.go
cmd/neofs-node/morph.go
cmd/neofs-node/object.go
cmd/neofs-node/reputation.go
pkg/services/object/acl/v2/opts.go
pkg/services/object/acl/v2/service.go

In the testnet metrics there is an extensive load on neo-go client in places where cache is missing. This PR:
1. reuses netmap source cache,
2. introduces cache for Inner Ring list fetching.
Metrics:
```
307 @ 0x43b405 0x44c4b7 0x806329 0x8019cb 0x7e72b5 0x7a8334 0x7a7d1f 0x7a9d9f 0xa99a45 0xa99a2a 0xa996ff 0xaa75ea 0xaa7097 0xab12a5 0xabcd0b 0xab4686 0xab1532 0xd1dda7 0xd1dcd8 0xde0b87 0xde0b70 0xd8ba15 0xd8b189 0xd8901d 0xd85af8 0xd7d029 0xb78e5e 0xd7a645 0xd7d7c9 0xb6a08f 0xd7b3d5 0xd794ba
#	0x806328	net/http.(*Transport).getConn+0x588									net/http/transport.go:1368
#	0x8019ca	net/http.(*Transport).roundTrip+0x7ea									net/http/transport.go:579
#	0x7e72b4	net/http.(*Transport).RoundTrip+0x34									net/http/roundtrip.go:17
#	0x7a8333	net/http.send+0x453 …
```

More caches for storage node

---

cmd/neofs-adm/internal/modules/morph/initialize.go

Close #1288.
Check the full file name instead of just prefix. Also, fix a bug where
a single missing wallet could lead to an incorrect size calculation.

[#1288] neofs-adm: Allow to store garbage in alphabet wallet dir

---

cmd/neofs-adm/internal/modules/morph/policy.go
cmd/neofs-adm/internal/modules/morph/root.go

Tested here (will finish testing with actual parameter update check later)  https://github.com/nspcc-dev/neofs-adm-tests/tree/set-policy):
```
$ make clone
$ NEOFS_REPO=https://github.com/fyrchik/neofs-node.git ./test.set-policy.sh neofs-adm-set-policy master
```
TODO: finish test, add to CI

neofs-adm: allow to change parameters of the Policy contract

---

pkg/innerring/innerring.go
pkg/morph/event/listener.go

When IR node configured without main chain, both `morphListener` and `mainnetListener` are pointing into single listener component. We should not call `Stop()` twice, because it may trigger channel closing in neo-go or other components and it can throw panic.
Related to https://github.com/nspcc-dev/neo-go/pull/2420

innerring: Don't stop the same listener twice

---

pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/innerring/processors/netmap/process_epoch.go
pkg/innerring/processors/netmap/processor.go
pkg/innerring/state.go
pkg/morph/client/client.go
pkg/morph/timer/block.go
pkg/morph/timer/block_test.go

Close #1208.
Provide current heights as an argument to ticker.
Zero height disables any checks, thus corresponding to the old
behaviour. If non-zero height is used, ignore the tick if the height
is less than the timer tick state.

innerring: disallow to tick timer twice on the same height

---

cmd/neofs-adm/internal/modules/root.go

Cobra `Command` prints to stderr by default.
`neofs-cli` already sets the output properly.

neofs-adm: set stdout as default output

---

cmd/neofs-node/cache.go
cmd/neofs-node/container.go

* closes #1313 
In previous implementation `Container.Delete` operation caused local
node's cache invalidation (container itself, eACL and listings). Any
subsequent `Container.Get` operation reversed invalidation. Given the
low latency sensitivity of deleting a container, there is no need to
touch the cache. With this approach, all pending deletion operations on
the node via the NeoFS API protocol will be delayed by the cache TTL.
Do not call cache invalidation ops in `morphContainerWriter.Delete`.
Remove no longer needed `InvalidateContainerListByCID` and
`InvalidateContainer` methods.

container: Do not invalidate cache on `Container.Delete`

---

pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/put.go
pkg/services/object/put/distributed.go
pkg/services/object/put/local.go
pkg/services/object/put/remote.go
pkg/services/object/put/streamer.go
pkg/services/object_manager/transformer/transformer.go

Some fixes for object service

---

cmd/neofs-adm/internal/modules/morph/dump.go

Related to #1300.
Not critical, just supporting new config param in `dump-config` command:
```
▶ ./bin/neofs-adm morph dump-config -r http://192.168.130.90:30333
AuditFee:                    10000 (int)
BasicIncomeRate:             100000000 (int)
ContainerAliasFee:           500 (int)
ContainerFee:                1000 (int)
EigenTrustAlpha:             0.1 (str)
EigenTrustIterations:        4 (int)
EpochDuration:               240 (int)
HomomorphicHashingDisabled:  true (bool)
InnerRingCandidateFee:       10000000000 (int)
MaxObjectSize:               67108864 (int)
SystemDNS:                   636f6e7461696e6572 (hex)
WithdrawFee:                 100000000 (int)
```

Fix/Add homomorphic hashing config param to `adm morph dump-config` command

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/group.go

Close #1346.
When a contract wallet is created, there is no need to decrypt
newly-created accounts.

[#1346] neofs-adm: do not ask password twice

---

cmd/neofs-adm/internal/modules/config/config.go
cmd/neofs-adm/internal/modules/morph/balance.go
cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/dump.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/group.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/initialize_register.go
cmd/neofs-adm/internal/modules/morph/initialize_roles.go
cmd/neofs-adm/internal/modules/morph/initialize_transfer.go
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-adm/internal/modules/morph/policy.go
cmd/neofs-adm/internal/modules/morph/root.go
go.mod
go.sum

Allow to generate chain dumps with neofs-adm

---

pkg/services/control/service_test.go
pkg/services/control/types_test.go

It is nice to have different paths for different components and also
check that the information returned is different for different shards.

services/control: extend tests for `ShardInfo` marshaling

---

pkg/util/locode/column/country.go
pkg/util/locode/column/location.go
pkg/util/locode/record.go

Make error messages more descriptive when parsing LOCODE from string errors
appear.
Closes #1394.

Fix/Add details to LOCODE errors

---

pkg/morph/client/client.go
pkg/morph/client/client_test.go

Partially revert, remove `big.Int`, leave `uint64` and `int` types.
This reverts commit 9349f422fd9a29ec529ef0648bbfabd1f9ff7651.

Revert "[#1141] morph/client: Allow to use more integer types as arguments"

---

CHANGELOG.md
pkg/services/policer/check.go

In previous implementation `Policer` considered local object copy as
redundant on processing single placement vector.
Make `Policer` to call redundant copy callback after full placement
processing. Also fix 404 error parsing.
* closes #1335

[#1335] policer: Prevent potential object loss

---

pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/inmemory.go
pkg/local_object_storage/pilorama/interface.go

Close #1419.
Consider a node `{FileName: "dir", Attribute: "xxx"}`. In case we add
a new node by path `["dir", "file.txt"]`, create a new intermediate node
with a single attribute. `GetByPath` now also considers only nodes with
a single attribute while building a path.

[#1419] pilorama: Create new nodes in path if needed

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/eacl/v2/eacl_test.go
pkg/services/object/acl/eacl/v2/headers.go
pkg/services/object/acl/eacl/v2/object.go
pkg/services/object/acl/eacl/v2/opts.go
pkg/services/object/acl/v2/classifier.go
pkg/services/object/acl/v2/request.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/util.go

After the SDK update there appeared an NPE error: we tried to dereference nil OID pointer for the `Put` and `Search` requests that do not contain (or not always contain) object ID. Make OID optional for requests (in general).

Fix/NPE in ACL service

---

pkg/services/container/executor.go
pkg/services/container/morph/executor.go
pkg/services/container/morph/executor_test.go

[#1159] services/container: Remove `ContainerWithContext` struct

---

pkg/local_object_storage/blobovnicza/blobovnicza.go
pkg/local_object_storage/blobovnicza/control.go
pkg/local_object_storage/blobstor/blobovnicza_test.go

Currently we use `(*bbolt.Bucket).Stats().KeyN` for estimating database
size. However, it iterates over all pages in bucket and thus heavily
depends on the bucket size. This commit replaces initial size estimation
with a single `os.Stat` call.

blobovnicza: determine db size via `os.Stat`

---

pkg/innerring/processors/alphabet/process_emit.go
pkg/innerring/processors/settlement/basic/collect.go

Log errors for network operations. The only places where we are not
interested in errors are `Submit` in pool and unmarshaling.

innerring: log errors in processors

---

pkg/local_object_storage/writecache/util.go

Refs #1503 .
Metabase and blobovnicza are already good.

writecache: provide timeout to `bbolt.Open`

---

pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/inmemory.go

Close #1481 .
Current implementation prevents invalid operations to become valid at
some later point (consider adding a child to the non-existent parent and
then adding the parent). This seems to diverge from the paper algorithm
and complicates implementation. Make it simpler.

[#1481] pilorama: Fix `TreeApply`

---

cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/container/get_eacl.go
cmd/neofs-cli/modules/container/set_eacl.go
cmd/neofs-node/cache.go
cmd/neofs-node/container.go
cmd/neofs-node/object.go
go.mod
go.sum
pkg/core/container/storage.go
pkg/innerring/processors/audit/process.go
pkg/innerring/processors/container/process_container.go
pkg/innerring/processors/container/process_eacl.go
pkg/innerring/settlement.go
pkg/morph/client/container/eacl.go
pkg/morph/client/container/eacl_set.go
pkg/morph/client/container/get.go
pkg/morph/client/container/put.go
pkg/services/container/morph/executor.go
pkg/services/container/morph/executor_test.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/acl_test.go
pkg/services/object/acl/eacl/types.go
pkg/services/object/acl/v2/service.go
pkg/services/object/put/streamer.go
pkg/services/object/util/placement.go
pkg/services/policer/check.go

After recent changes in NeoFS SDK Go library session tokens aren't
embedded into `container.Container` and `eacl.Table` structures.
Group value, session token and signature in a structure for container
and eACL.

Upgrade NeoFS SDK Go with changed container sessions

---

cmd/neofs-node/config.go
cmd/neofs-node/config/engine/config_test.go
cmd/neofs-node/config/engine/shard/pilorama/config.go

Reuse bolt DB configuration in the tree service

---

cmd/neofs-cli/internal/commonflags/json.go
cmd/neofs-cli/modules/bearer/create.go
cmd/neofs-cli/modules/container/get.go
cmd/neofs-cli/modules/container/get_eacl.go
cmd/neofs-cli/modules/control/shards_list.go
cmd/neofs-cli/modules/control/snapshot.go
cmd/neofs-cli/modules/netmap/nodeinfo.go
cmd/neofs-cli/modules/object/get.go
cmd/neofs-cli/modules/object/head.go
cmd/neofs-cli/modules/object/range.go
cmd/neofs-cli/modules/session/create.go
cmd/neofs-cli/modules/util/convert_eacl.go
cmd/neofs-cli/modules/util/sign_bearer.go

Close #1541.
Marshaling with jsonpb has one advantage: we will never forget to add new fields in CLI.
However, the general approach would eventually be done anyway in #1323 .
What do you think? @cthulhu-rider @carpawell

Allow to marshal `control shards list` as JSON

---

cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/initialize_test.go

Close #1307.
Our integration tests currently do not support creating multiple-node committee. This test helps to quickly check `morph init` while doing some refactoring or local changes.
We can write more tests, however `morph init` is the biggest command and the task was about coverting at least it. New tests can be added when needed.

[#1307] neofs-adm: Add tests for `morph init` command

---

cmd/neofs-cli/modules/container/list_objects.go
go.mod
go.sum

It led to the `flag accessed but not defined: bearer` error in the container's subcommands.
Also updated SDK with https://github.com/nspcc-dev/neofs-sdk-go/pull/277 to make the master workable.

Fix/Add bearer token flag to CLI

---

.github/workflows/project.yml

It seem that technically issue is labeled after creation.

.github: assign issues to project when labeled

---

pkg/local_object_storage/blobstor/control.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/shard/control.go

Make `Shard` to work in degraded mode if metabase is unavailable on
opening stage.
* closes #1549
About 9bf46d99818bf6f5218535fb9f555e48356d9cab: I don't think it makes sense to define `ModeDisabled` shard mode now since `StorageEngine` can't work with it. Maybe we can implement private behavior on `Shard` side when it fails all the calls if `Init` was failed, smth like `errNotInitialized`.

shard: Turn `ModeDegraded` on metabase opening failure

---

pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/fee.go
pkg/morph/client/fee_test.go
pkg/morph/client/multi.go
pkg/morph/client/notifications.go
pkg/morph/client/static.go

Otherwise we could switch infinitely if subscription restore has failed.

morph/client: perform RPC switch and restore in one step

---

CHANGELOG.md
pkg/services/object/get/v2/util.go

Forwarded requests contained zero version in their meta header. It did not
allow responding with API statuses (`v0.0` version considered to be older
than `v2.11`) to the forwarding node and, therefore, did not allow analyzing
responses.

Fix/Do not lose API version on forwarding

---

CHANGELOG.md
pkg/services/object/get/v2/util.go

This is the fastest solution that does work as planned. I thought about forwarding and responding via streams but decided to just fix OOM error in that PR and change request forwarding in a separate PR (if needed) after some discussion.
1. Do not allocate memory more than `MaxObjectSize` (another node could somehow respond with OK status on `GetRange` with *incredibly huge* range length).
2. Forward requests and stream the response (not copy the whole object in memory). This will require changing all the forwarding approaches (`Get`/`GetRange`).
NOTE: PR also fixes status handling after the #1581, so #1581 should not be added to *any* release without that PR. Since we do not handle statuses but also do not get raw errs via RPC calls (version is attached to the requests after #1581) we end …

Fix/OOM on `GetRange` request

---

pkg/core/object/errors.go
pkg/local_object_storage/blobstor/blobovnicza.go
pkg/local_object_storage/blobstor/errors.go
pkg/local_object_storage/blobstor/get_range_big.go
pkg/local_object_storage/engine/error_test.go
pkg/local_object_storage/engine/range.go
pkg/local_object_storage/shard/errors.go
pkg/local_object_storage/shard/get.go
pkg/services/object/get/assemble.go
pkg/services/object/get/local.go
pkg/services/object/get/remote.go

Replace `ErrRangeOutOfBounds` error from `pkg/core/object` package with
`ObjectOutOfRange` from `apistatus` package. That error is returned by
storage node's server as NeoFS API statuses.

Feat/Support `OUT_OF_RANGE` status

---

pkg/local_object_storage/blobstor/blobstor.go
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/shard/id.go
pkg/local_object_storage/writecache/writecache.go

shard: print shard ID in component logs

---

CHANGELOG.md
pkg/services/object/acl/eacl/v2/headers.go

Also, try to fetch object header info from the local storage to find as much
object info as possible for the requests which do not assume returning
object header as a response.
Closes #1595. @fyrchik, @alexvanin, please, double-check that solution. The main idea is to always use cid and oid from the request as a descriptor of the object being streamed. I do not know how to check if the streamed object really has that bytes that a node is streaming and if it really should be checked. Also, i do not if it is ok to just answer `ALLOW` if it is impossible to fetch the header from the local storage for streamed requests; but seems that solution was considered as working according to reading some other previous commits.

Fix/Use OID/CID from the request in eACL checks

---

cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

1. Assign the group to all contracts.
2. Assign group to the alphabet ones too.

Fix neofs-adm group processing during an update

---

pkg/local_object_storage/engine/tree.go

After a4adb79db new logical error could be returned. Do not increase
error counter in this case.

engine: Do not increase error counter if the pilorama is disabled

---

go.mod
go.sum
pkg/core/container/storage.go
pkg/morph/client/container/eacl.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/eacl/types.go

Remove internal `ErrEACLNotFound` error.
Also, update `neofs-api-go` and and `neofs-sdk-library`.
Related to https://github.com/nspcc-dev/neofs-sdk-go/issues/305.

Feat/Support `EACL_NOT_FOUND` status

---

CHANGELOG.md
pkg/innerring/innerring.go

Close #1641 .
Return listen errors in a synchronous fashion.
Another solution would be to use buffered channel, but this is not
scalable: for each new similar runner we would need to extend the
buffer.

innerring: exit if we cannot bind to the control endpoint

---

cmd/neofs-lens/root.go

Use stdout as default output for neofs-lens

---

CHANGELOG.md
pkg/local_object_storage/writecache/delete.go

If an object is found in the Write-cache and is placed at the end of
the in-memory cache, the memory counter update operation tries to dereference
the index that is out of the sliced array. Moreover, even if panic does not appear,
the counter is updated with the wrong value.
Closes #1664. The wrong place for that line has been chosen in #568.

Fix/Panic on write-cache `Delete` operation

---

Makefile

**Summary:** only tags that start with "v" will be accounted for in VERSION calculation.
**Motivation:** this allows us to use any custom tags along with tags that denote releases

Filter version tags for version calculation

---

pkg/local_object_storage/writecache/util.go

Close #1647.
Initially, `Sync: false` was provided because we can already lose
objects cached in memory. However, future changes in writecache will
remove inmemory cache and speed up it via other means.

[#1647] writecache: Open DB in sync mode

---

cmd/neofs-cli/modules/object/get.go

Close #1719.
`curl` uses 0644, for example.

neofs-cli: save object with proper permissions

---

cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go

Deploy contract in one transaction and register NNS record in another to
prevent GAS limit exceeding due to the fact that registration always takes
10+ GAS.
Closes #1675.

Fix/Separate deploying contract and NNS updating transaction

---

cmd/neofs-adm/internal/modules/morph/initialize.go

Do not query application log for the same transaction more than once.

neofs-adm: clean tx hash list after awaiting

---

cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/dump_hashes.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/root.go

Also, set addresses instead of hex-hashes for custom contracts.

Allow to dump hashes for the custom zone

---

pkg/local_object_storage/blobovnicza/get.go
pkg/local_object_storage/blobovnicza/get_test.go

Re-configuration of Blobovnicza's object size limit must not affect already stored objects. In previous implementation `Blobovnicza` didn't see objects stored in buckets which became too big after size limit re-configuration. For example, lets consider 1st configuration with 64KB size limit for stored objects. Lets assume that we stored object of 64KB size, and re-configured `Blobovnicza` with 32KB limit. After reboot object should be still available, but actually it isn't. This is caused by `Get` operation algorithm which iterates over configured size ranges only, and doesn't process any other existing size bucket. By the way, increasing of the object size limit didn't lead to the problem even in previous implementation.
Make `Blobovnicza.Get` method to iterate over all size buckets …

blobovnicza/get: Iterate over all buckets regardless of config

---

cmd/neofs-node/morph.go
pkg/morph/subscriber/subscriber.go

* inspired by explorations performed within https://github.com/nspcc-dev/neofs-node/issues/1721
Within the issue I made a hypothesis that node had missed some ticks of the epoch timer. However it was difficult to explicitly prove or disprove this assumption.
These changes make storage nodes to log new epochs. From now it'll be easy to track the node timeline.

node/netmap: Write log messages about `NewEpoch` events

---

cmd/neofs-node/tree.go
pkg/local_object_storage/engine/tree.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/interface.go
pkg/local_object_storage/shard/tree.go
pkg/services/tree/drop.go

Close #1630.
I think removing based on morph event covers our main use-case.
Do we need an RPC to remove trees without removing the container? @alexvanin @KirillovDenis

services/tree: allow to drop trees from the database

---

cmd/neofs-node/config.go
pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza.go

Because it is without `s` in the examples, I think we should leave it as it is.

Fix node configuration parsing

---

pkg/local_object_storage/metabase/VERSION.md
pkg/local_object_storage/metabase/containers.go
pkg/local_object_storage/metabase/counter.go
pkg/local_object_storage/metabase/db.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/get.go
pkg/local_object_storage/metabase/graveyard.go
pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/iterators.go
pkg/local_object_storage/metabase/list.go
pkg/local_object_storage/metabase/lock.go
pkg/local_object_storage/metabase/movable.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/shard_id.go
pkg/local_object_storage/metabase/storage_id.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/metabase/version.go

Close #1482 .
```
name                        old time/op    new time/op    delta
Select/string_equal-8         8.87µs ± 5%    2.92µs ± 7%  -67.05%  (p=0.000 n=10+10)
Select/string_not_equal-8     4.95ms ±11%    1.34ms ± 9%  -73.04%  (p=0.000 n=10+10)
Select/common_prefix-8        55.5µs ± 6%    15.5µs ± 9%  -72.08%  (p=0.000 n=9+10)
Select/unknown-8              3.32µs ± 9%    0.85µs ± 8%  -74.46%  (p=0.000 n=10+10)
Put/parallel-8                1.27ms ±12%    1.13ms ±19%  -11.07%  (p=0.009 n=10+10)
Put/sequential-8              4.55ms ±14%    4.32ms ±12%     ~     (p=0.190 n=10+10)
ListWithCursor/1_item-8       4.96µs ±16%    3.25µs ± 7%  -34.32%  (p=0.000 n=10+10)
ListWithCursor/10_items-8     15.4µs ±14%     6.5µs ± 8%  -57.47%  (p=0.000 n=10+10)
ListWithCursor/100_items-8     119µs ± …
```

Do not use base58 encoded keys in the metabase

---

CHANGELOG.md
cmd/neofs-cli/modules/container/delete.go

[nspcc-dev#1692] cli: Remove `--generate-key` option in `neofs-cli container delete`

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/control.go
cmd/neofs-node/object.go
pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/engine/evacuate_test.go
pkg/services/control/server/evacuate.go
pkg/services/control/server/server.go
pkg/services/policer/check.go
pkg/services/replicator/process.go
pkg/services/replicator/task.go

Allow to replicate object to other nodes in `control.EvacuateShard`

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/config/engine/config.go
cmd/neofs-node/config/engine/config_test.go
cmd/neofs-node/config/engine/shard/blobstor/blobovnicza/config.go
cmd/neofs-node/config/engine/shard/blobstor/config.go
cmd/neofs-node/config/engine/shard/blobstor/fstree/config.go
cmd/neofs-node/main.go
cmd/neofs-node/validate.go
cmd/neofs-node/validate_test.go
config/mainnet/config.yml
config/testnet/config.yml
pkg/local_object_storage/blobstor/blobovniczatree/blobovnicza.go
pkg/local_object_storage/blobstor/fstree/fstree.go

We need this for #1770 .
Related #1764.
The list of checks will be extended. Currently only storage section is supported, as the most important one.

Validate config before usage

---

CHANGELOG.md
cmd/neofs-cli/modules/container/get_eacl.go
cmd/neofs-cli/modules/netmap/nodeinfo.go

Description updated because the command returns information about the remote node that is listening to the `--rpc-endpoint`

Fix description of nodeinfo command

---

cmd/neofs-node/config.go
cmd/neofs-node/config/config.go
cmd/neofs-node/config/engine/shard/blobstor/fstree/config.go
cmd/neofs-node/main.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/fstree/option.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/engine/control_test.go
pkg/local_object_storage/engine/engine_test.go
pkg/local_object_storage/engine/lock_test.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/engine/shards_test.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/shard.go

Related to #1770.
1. Storage interface could be unified: `Open` and `Reload` could have the same args list but that will require additional refactoring, not sure if we need that.
2. It now seems like we have duplication of configuration structs: one placed in the `main` pkg and another in the `cmd/neofs-node/config` dir. They could be merged somehow if we need them to be together.

Feat/Reload config on SIGHUP

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go

Refactor/Config in SN

---

CHANGELOG.md
cmd/neofs-cli/modules/session/util.go
go.mod
go.sum
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/util.go
pkg/services/object/acl/v2/util_test.go

In previous implementation of `neofs-node` app object session was not checked for substitution of the object related to it. Also, for access checks, the session object was substituted instead of the one from the request. This, on the one hand, made it possible to inherit the session from the parent object for authorization for certain actions. On the other hand, it covered the mentioned object substitution, which is a critical vulnerability.
Next changes are applied to processing of all Object service requests:
- check if object session relates to the requested object
- use requested object in access checks.
Disclosed problem of object context inheritance will be solved within #1420.
* relates #1420

object/acl: Fix correlation of object session to request

---

CHANGELOG.md
cmd/neofs-node/config/morph/config.go
cmd/neofs-node/morph.go
config/example/node.yaml
docs/storage-node-configuration.md

[#1846] neofs-node: Make morph.cache_ttl equal to block time by default

---

CHANGELOG.md
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/inhume.go

If shard is in read-only or degraded mode, there is no need to increase error counter.
Found by @EliChin .
```
2022-10-04T14:55:12.765Z        warn    engine/engine.go:44     could not inhume object in shard        {"shard_id": "FsrPomaDsLXubwDYC1epFA", "error count": 22, "error": "shard is in read-only mode"}
2022-10-04T14:55:12.765Z        warn    engine/engine.go:44     could not inhume object in shard        {"shard_id": "FsrPomaDsLXubwDYC1epFA", "error count": 23, "error": "shard is in read-only mode"}
```

engine: handle Inhume errors properly

---

CHANGELOG.md
cmd/neofs-cli/internal/common/netmap.go
cmd/neofs-cli/modules/container/delete.go
cmd/neofs-cli/modules/container/get.go
cmd/neofs-cli/modules/container/get_eacl.go
cmd/neofs-cli/modules/container/list_objects.go
cmd/neofs-cli/modules/container/nodes.go
cmd/neofs-cli/modules/container/root.go
cmd/neofs-cli/modules/container/set_eacl.go
cmd/neofs-cli/modules/netmap/snapshot.go

Closes #1704
Example of `short` output:
```
@:~/workspace/neofs-node$ neofs-cli container nodes --from ~/cnt --wallet ~/workspace/neofs-dev-env/wallets/wallet.json --rpc-endpoint 192.168.130.71:8080 --short
Enter password > 
Rep 1
Node 1: 022bb4041c50d607ff871dec7e4cd7778388e0ea6849d84ccbd9aa8f32e16a8131 ONLINE /dns4/s01.neofs.devenv/tcp/8080 
Node 2: 038c862959e56b43e20f79187c4fe9e0bc7c8c66c1603e6cf0ec7f87ab6b08dc35 ONLINE /dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080 
Rep 2
Node 1: 022bb4041c50d607ff871dec7e4cd7778388e0ea6849d84ccbd9aa8f32e16a8131 ONLINE /dns4/s01.neofs.devenv/tcp/8080 
Node 2: 038c862959e56b43e20f79187c4fe9e0bc7c8c66c1603e6cf0ec7f87ab6b08dc35 ONLINE /dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080 
```
Example of normal output: …

Add command `container nodes` to output list of nodes for container, grouped by replica

---

cmd/neofs-node/config.go

Config was reread from the file only once in two SIGHUPs.

Fix config rereading

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/root.go
cmd/neofs-cli/modules/netmap/nodeinfo.go

1. Print proper status in `neofs-cli netmap nodeinfo`
2. Allow to set config in neofs-adm without --force flag.

Minor fixes for maintenance mode in `neofs-cli` and `neofs-adm`

---

CHANGELOG.md
cmd/neofs-node/config.go

neofs-node: use `writecache.max_object_size` from the config

---

CHANGELOG.md
pkg/services/control/server/set_shard_mode.go

Close #1931.
It hasn't been working since the initial implementation 7fb15fa1d0df0.

[#1931] control: Allow to clear errors in `SetShardMode` RPC

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/local_client.go
cmd/neofs-adm/internal/modules/morph/n3client.go
cmd/neofs-cli/internal/key/key_test.go
go.mod
go.sum

* relates #1946
Unsafe but at least compiles.

Bump neo-go module to v0.99.4

---

CHANGELOG.md
pkg/network/cache/multi.go

Close #1936.
After an SDK update `Dial` can return an error.

[#1936] network/cache: Handle dial errors

---

CHANGELOG.md
pkg/local_object_storage/shard/gc.go

Close #1907.
I hasn't been able to reproduce, but this should fix it.

[#1907] shard: Return from `Close` after GC has stopped

---

cmd/neofs-cli/internal/client/sdk.go

* relates to #1920
I've checked that command falls back to the timeout specified in the config file if `--timeout` flag is missing.
Can we close the related issue?
I don't think this change deserves changelog.

cli: Print used RPC timeout in verbose exec

---

CHANGELOG.md
pkg/local_object_storage/engine/container.go
pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/engine/select.go
pkg/local_object_storage/metabase/containers.go
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/metabase/graveyard.go
pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/iterators.go
pkg/local_object_storage/metabase/lock.go
pkg/local_object_storage/metabase/movable.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/shard/container.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/list.go

Make `metabase.ContainerSize` actually read-only

---

CHANGELOG.md
cmd/neofs-cli/internal/commonflags/flags.go
cmd/neofs-cli/modules/acl/extended/create.go
cmd/neofs-cli/modules/container/delete.go
cmd/neofs-cli/modules/container/get.go
cmd/neofs-cli/modules/container/get_eacl.go
cmd/neofs-cli/modules/container/list_objects.go
cmd/neofs-cli/modules/container/nodes.go
cmd/neofs-cli/modules/container/set_eacl.go
cmd/neofs-cli/modules/control/synchronize_tree.go
cmd/neofs-cli/modules/object/delete.go
cmd/neofs-cli/modules/object/get.go
cmd/neofs-cli/modules/object/hash.go
cmd/neofs-cli/modules/object/head.go
cmd/neofs-cli/modules/object/lock.go
cmd/neofs-cli/modules/object/put.go
cmd/neofs-cli/modules/object/range.go
cmd/neofs-cli/modules/object/search.go
cmd/neofs-cli/modules/object/util.go
cmd/neofs-cli/modules/storagegroup/delete.go
cmd/neofs-cli/modules/storagegroup/get.go
cmd/neofs-cli/modules/storagegroup/list.go
cmd/neofs-cli/modules/storagegroup/put.go
cmd/neofs-cli/modules/storagegroup/root.go
cmd/neofs-cli/modules/storagegroup/util.go
cmd/neofs-cli/modules/tree/add.go
cmd/neofs-cli/modules/tree/add_by_path.go
cmd/neofs-cli/modules/tree/get_by_path.go
cmd/neofs-cli/modules/tree/list.go
cmd/neofs-cli/modules/tree/root.go

Closes #1338
With flag `--binary` user can point to the file with serialized object structure - id + signature + header + payload
Added for development purposes.

Add support to store/restore/delete binary objects

---

CHANGELOG.md
pkg/local_object_storage/engine/tree.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/forest_test.go
pkg/local_object_storage/pilorama/interface.go
pkg/local_object_storage/shard/tree.go

Currently there is a possibility for modifying operations to fail because of I/O errors and a new tree to be created on another shard. This commit adds existence check for modifying operations. Read operations remain as they are, not to slow things. `TreeDrop` is an exception, because this is a tree removal and trying multiple shards is not an unwanted behaviour.

engine: always select proper shard for a tree

---

CHANGELOG.md
cmd/neofs-cli/modules/object/lock.go
cmd/neofs-node/object.go
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/services/object/put/distributed.go
pkg/services/object/put/local.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/put/validation.go

Closes #1972.
Includes:
1. CLI `object lock`'s `lifetime` flag fix;
2. Changing broadcasting logic: a node does not save object relations if it is not in the object's container. I did not find any usage of that, but it disallows correct object handling: putting a TS record to a storage of a node that does not belong to the container skips any lock object checks (it just does not have any helper objects of the container) and does not have any reasons. @fyrchik, @cthulhu-rider, please, double-check that.

[SUPPORT] Fix/Helper object broadcasting

---

CHANGELOG.md
pkg/services/object/get/assemble.go
pkg/services/object/get/util.go
pkg/services/object/internal/client/client.go

Fixes some autotests with bad ranges and expected `out of range` error.

services/object: Unify apistatus errors

---

CHANGELOG.md
pkg/local_object_storage/shard/writecache.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/flush_test.go

Close #1906.
It was needed before we started to flush during transition to `degraded` mode. Now it is confusing.

[#1906] writecache: Do not require `read-only` mode in `Flush`

---

CHANGELOG.md
cmd/neofs-cli/modules/object/util.go

Closes #2000 _exactly_, neither more nor less.

[SUPPORT] Fix/Object removal with a bearer token

---

CHANGELOG.md
pkg/services/object/put/distributed.go

```
fatal error: concurrent map writes
goroutine 4337 [running]:
github.com/nspcc-dev/neofs-node/pkg/services/object/put.(*traversal).submitProcessed(...)
github.com/nspcc-dev/neofs-node/pkg/services/object/put/distributed.go:78
github.com/nspcc-dev/neofs-node/pkg/services/object/put.(*distributedTarget).iteratePlacement.func1()
github.com/nspcc-dev/neofs-node/pkg/services/object/put/distributed.go:198 +0x265
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
github.com/panjf2000/ants/v2@v2.4.0/worker.go:68 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
github.com/panjf2000/ants/v2@v2.4.0/worker.go:48 +0x65
```

(SUPPORT) services/object: Fix concurrent map writes in traverser

---

CHANGELOG.md
cmd/neofs-cli/modules/object/hash.go

All the other object commands already have it.
Closes #2029.

[SUPPORT] Fix/Allow attaching static session to `object hash`

---

cmd/neofs-cli/modules/object/hash.go

Oups. Missclick while copy-pasting in #2039 (or just wrong autocomplete by IDE, do not remember).

[SUPPORT] Fix/Panic caused by flag redefinition

---

cmd/neofs-cli/modules/object/util.go

If an external session is provided and is not opened by CLI itself, add children objects to it too. It fixes "not found" errors when removing a big object with a predefined session (from a file).
Closes #1978.

[SUPPORT] Fix/Big objects removal with static sessions

---

CHANGELOG.md
pkg/services/object/get/assemble.go
pkg/services/object/util/prm.go

Closes #2040.
See #2046 about the first commit.

Fix/Big object `GET` with bearer

---

pkg/local_object_storage/engine/engine.go

Related to #2053.
```
Nov 14 02:42:42 az neofs-node[14468]: 2022-11-14T02:42:42.148Z        debug        writecache/flush.go:122        tried to flush items from write-cache        {"shard_id": "UdNgukPGsHGaTvDp7tGtz3", "count": 1, "start": ""}
Nov 14 02:42:42 az neofs-node[14468]: 2022-11-14T02:42:42.148Z        warn        engine/engine.go:153        can't update object storage ID        {"shard_id": "UdNgukPGsHGaTvDp7tGtz3", "error count": 2, "error": "status: code = 2049"}
Nov 14 02:42:42 az neofs-node[14468]: 2022-11-14T02:42:42.148Z        warn        engine/engine.go:153        can't update object storage ID        {"shard_id": "UdNgukPGsHGaTvDp7tGtz3", "error count": 3, "error": "status: code = 2049"}
Nov 14 02:42:42 az neofs-node[14468]: 2022-11-14T02:42:42.148Z        warn …
```

[SUPPORT] Fix/Non-logical shard mode switch

---

CHANGELOG.md
pkg/local_object_storage/writecache/flush.go

Fixes
```
Nov 03 08:10:25 vedi neofs-node[606]: 2022-11-03T08:10:25.933Z        debug        writecache/flush.go:121        tried to flush items from write-cache        {"shard_id": "Q4JVDpjCDxx5as5HYzRdyZ", "count": 1, "start": ""}
Nov 03 08:10:25 vedi neofs-node[606]: 2022-11-03T08:10:25.933Z        debug        writecache/flush.go:121        tried to flush items from write-cache        {"shard_id": "Q4JVDpjCDxx5as5HYzRdyZ", "count": 1, "start": ""}
Nov 03 08:10:25 vedi neofs-node[606]: 2022-11-03T08:10:25.933Z        debug        writecache/flush.go:121        tried to flush items from write-cache        {"shard_id": "Q4JVDpjCDxx5as5HYzRdyZ", "count": 1, "start": ""}
Nov 03 08:10:25 vedi neofs-node[606]: 2022-11-03T08:10:25.933Z        debug        writecache/flush.go:121        tried …
```

[SUPPORT] Fix/Write-cache flush duplication

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
pkg/morph/client/nns.go

In https://github.com/nspcc-dev/neofs-node/pull/1748 we've introduced a small inconsistency in NNS hash parsing:
* In function [parseNNSResolveResult](https://github.com/nspcc-dev/neofs-node/blob/support/v0.34/cmd/neofs-adm/internal/modules/morph/initialize_nns.go#L250) we support 2 hash formats (Uint160DecodeStringLE и StringToUint160).
* In function [nnsResolve](https://github.com/nspcc-dev/neofs-node/blob/support/v0.34/pkg/morph/client/nns.go#L140) we support only 1 format (Uint160DecodeStringLE).
This PR updates implementation of nnsResolve so that it is consistent with parseNNSResolveResult.
Per discussion with @fyrchik for now we just add missing logic to nnsResolve. In the future we will refactor implementation so that the logic is implemented in a single place.

Support new hash format in morph nns client

---

CHANGELOG.md
pkg/morph/client/notary.go

morph/client: Ignore error if a transaction already exists

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go

```
Error: could not perform test invocation: script failed (FAULT state) due to an error: at instruction 117 (SYSCALL): element is not an array 
```
Contract arguments have to be packed.

adm: Pack parameters for `setPrice` invocation

---

CHANGELOG.md
cmd/neofs-cli/modules/object/head.go

OID signature should always be present in an object; it does not relate to the object split.
It is about [the field](https://github.com/nspcc-dev/neofs-api/blob/813c04bea4a23b99fb90666b1b325c95e0a364cf/object/types.proto#L202).

Fix/OID signature in CLI output

---

go.mod

go.mod: Retract `v1.*` versions

---

CHANGELOG.md
cmd/neofs-cli/modules/container/create.go

Perform this check on container creation.
Close #2038

neofs-cli: Check the sufficiency of the number of nodes in the selector for replicas

---

CHANGELOG.md
pkg/metrics/object.go
pkg/services/object/metrics.go

Close #1984.
Prometheus has `CounterVec` which could be used here, I have decided to save compatibility instead.
In the current implementation logical errors (not found, already removed) is counted as an error, IMO this is a right thing to do. cc @anatoly-bogatyrev

Add separate metrics for success/failed requests

---

CHANGELOG.md
cmd/neofs-node/morph.go
pkg/innerring/notary.go
pkg/morph/client/notary.go

It's time to solve `fallback transaction is valid after deposit is unlocked` once and for all.
Closes #1486 
Questions from original issue.
> I do not remember if it is allowed to make the same notary deposits (the same till, the same amount).
It is allowed.
> Doing a deposit with max int64 forces us to use the same till in all the further deposits (it is impossible to make deposits with newTill < currentTill).
Yes. Once we go for it, we won't be able to go back in the side chain. Don't see a problem with that.
> We have the same deposit logic in the side and main chains. While it is kinda ok to block some GAS forever in the sidechain, doing that in the main chain may have some misunderstanding (if we ever have notary turned on in the main chain).
Main chain is not affected by new …

Use endless notary deposit for side chain

---

CHANGELOG.md
cmd/neofs-cli/modules/object/range.go
pkg/services/object/get/assemble.go
pkg/services/object/get/get_test.go
pkg/services/object/get/prm.go
pkg/services/object/get/v2/util.go

Fix/panic in `GETRANGE`

---

CHANGELOG.md
pkg/core/netmap/nodes.go

Previously we have given external addresses a priority in some circumstances.
Now we prioritize internal addresses.
Should fix a problem where data interface is used even though internal is available.

core/netmap: change node addresses iteration order

---

CHANGELOG.md
pkg/services/policer/policer.go

We use cache to avoid policing the same object multiple times in a short time span (< 30 seconds). If we have 200_000 objects in a blobstor, it is a bit useless -- if it takes 1 second to process an object and we have `replicator.pool_size: 20` in config, the next iteration will happen in 10_000 second which is much larger than 30 second. However we still consume a lot of memory, so it makes sense to use saner default.

policer: Reduce default cache size

---

CHANGELOG.md
pkg/local_object_storage/pilorama/boltdb.go
pkg/services/tree/sync.go

Randomize tree synchronization

---

CHANGELOG.md
pkg/local_object_storage/engine/metrics.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/shard/metrics_test.go
pkg/local_object_storage/shard/mode.go
pkg/local_object_storage/shard/shard.go
pkg/metrics/object.go

How it looks in prometheus:
```
neofs_node_object_readonly{shard="4SVWUS1TajZ9ZwPRbUaNMY"} 1
neofs_node_object_readonly{shard="NoxKcaHtMd4rQp8DjqJiP5"} 0
```
Close #2022

Add metric `readonly` to get shards mode

---

CHANGELOG.md
pkg/services/tree/sync.go

There was a goroutine leak here.
No need to test.

services/tree: close connection after the syncronization

---

CHANGELOG.md
pkg/local_object_storage/shard/get.go
pkg/local_object_storage/shard/head.go
pkg/local_object_storage/writecache/delete.go
pkg/local_object_storage/writecache/init.go
pkg/local_object_storage/writecache/put.go
pkg/local_object_storage/writecache/storage.go
pkg/local_object_storage/writecache/writecache.go

Fix/Storage Group expiration

---

CHANGELOG.md
cmd/neofs-cli/modules/bearer/create.go
cmd/neofs-cli/modules/object/lock.go
cmd/neofs-cli/modules/object/put.go
cmd/neofs-cli/modules/storagegroup/get.go

Clarify help for `--expire-at` parameter for commands `object lock/put` and `bearer create`

---

pkg/local_object_storage/pilorama/boltdb.go

It should be similar to a `TreeAddByPath`. `applyOperation` is used for `Apply` when the operation can be inserted in the middle of a log.

pilorama: use `do` in `TreeMove`

---

CHANGELOG.md
pkg/local_object_storage/pilorama/boltdb.go

Close pilorama in degraded mode

---

pkg/local_object_storage/pilorama/batch.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/pilorama/forest.go
pkg/local_object_storage/pilorama/inmemory.go
pkg/local_object_storage/pilorama/types.go
pkg/services/tree/replicator.go
pkg/services/tree/service.go

Currently under consistent high load for >30m the performance degrade. The number of goroutines also increases (up to ~60k).
In think PR we do 2 things:
1. Simplify DB layout (this speeds up all transactions and reduces degradation)
2. Use non-blocking send (fix goroutine unbounded increase)

Tree service fixes

---

pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/shard/mode.go

1. Partially written object is deleted.
2. First write to a temporary file to avoid partially written files during hard-reset
Also, log time-consuming operations to help administrator observe system behaviour until we have a proper async operations support in `control` service.

Improve FSTree behaviour for partially written objects

---

CHANGELOG.md
cmd/neofs-node/cache.go
cmd/neofs-node/container.go

Close #2152 .
Close #2155. (?) @acid-ant 
Close #2052. (?)
Update the list of all containers if needed.

[#2152] neofs-node: Update container list cache properly

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/dump_hashes.go

If we had lots of domains in one zone, `dump-hashes` for all others can miss some domains, because we need to restrict ourselves with _some_ number.
In this commit we use neo-go sessions by default, with a proper failback to in-script iterator unwrapping.

adm: use native neo-go sessions in `dump-hashes`

---

CHANGELOG.md
pkg/local_object_storage/pilorama/batch.go
pkg/local_object_storage/pilorama/boltdb.go

To achieve high performance we must choose proper values for both batch size and delay. For user operations we want to set low delay. However it would prevent tree synchronization operations to form big enough batches. For these operations, batching gives the most benefit not only in terms of on-CPU execution cost, but also by speeding up transaction persist (`fsync`).
In this commit we try merging batches that are already _triggered_, but not yet _started to execute_. This way we can still query batches for execution after the provided delay while also allowing multiple formed batches to execute faster.
Hardware performance tests show ~10x improvement for small objects put in _one_ bucket.

pilorama: merge in-queue batches

---

CHANGELOG.md
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/storage.go

Here is a scenario:
1. Read from `flushed` inside of a `View` transaction.
2. Eviction handler in other goroutine deletes items from the database which can lead to allocating new storage for mmap.

writecache: fix possible deadlock

---

CHANGELOG.md
cmd/neofs-node/config.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/engine/control_test.go
pkg/local_object_storage/shard/control.go

Fix bugs along the way.
Invalid mode on a directory is an approximation of missing media.
We expect any `Open`/`Init` errors to be logged and a shard to be disabled.

engine: Add tests for initialization failure

---

CHANGELOG.md
cmd/neofs-node/config/replicator/config.go
config/example/node.yaml
docs/storage-node-configuration.md

Inspired by MainNet. "Fast" networks are considered more rare and requiring detailed configuration.

node: Increase default replication timeout to 1 minute

---

CHANGELOG.md
cmd/neofs-cli/internal/client/client.go

200MB object put time went down from 30s to 5s. Basically server spent _too_ much time verifying signatures.

cli: Fix default buffer size for object PUT

---

CHANGELOG.md
pkg/metrics/object.go

metrics: Fix request count metrics names

---

CHANGELOG.md
pkg/local_object_storage/writecache/init.go

Fix #2234.
In case we have many small objects in the write-cache, `indices` should not be reused between iterations.

[#2234] writecache: Fix possible panic in `initFlushMarks`

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/network/cache/multi.go
pkg/services/object/get/exec.go
pkg/services/object/put/distributed.go

In master:
`network/cache`-related changes will be replaced with gRPC-native keepalive mechanism.
Client cache separation should be approached more rigourously. It seems like a good idea, but we need to evaluate it further.

Fixes for a failover scenario.

---

CHANGELOG.md
cmd/neofs-cli/modules/util/acl.go

Zero value before:
```
RangeHASH    Range      Search     Delete     Put        Head       Get
0 1    0 1 0 1      0 0 0 0    0 1 0 1    0 0 0 0    0 1 0 0    0 1 0 1    0 1 0 1
X F    U S O B      U S O B    U S O B    U S O B    U S O B    U S O B    U S O B
X-Sticky F-Final U-User S-System O-Others B-Bearer
```
Now:
```
RangeHASH    Range      Search     Delete     Put        Head       Get
0 0    0 1 0 0      0 0 0 0    0 1 0 0    0 0 0 0    0 1 0 0    0 1 0 0    0 1 0 0
X F    U S O B      U S O B    U S O B    U S O B    U S O B    U S O B    U S O B
X-Sticky F-Final U-User S-System O-Others B-Bearer
```

cli/util: Fix basic ACL rendering

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/object.go
pkg/services/policer/check.go
pkg/services/policer/policer.go

* closes #2267
* closes #1453
I decided to not directly implement #1453 proposal:
* out-of-container (netmap) cases are handled in a special way
* insta replica removal after successful replication doesn't seem very good behavior: some nodes have been already violated storage policy and lost the object, therefore, it is worth waiting for some time interval, and make a decision already at the next check

Fix potential data loss in `Policer`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

* it makes zero sense
* we treat all issues equal
* most of them come from NSPCC

.github: remove 'community' from default issue labels

---

cmd/neofs-ir/defaults.go

IR: Do not set default value for Sidechain RPC endpoints in Viper

---

CHANGELOG.md
cmd/neofs-node/config.go
pkg/innerring/innerring.go
pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/morph/client/notifications.go
pkg/morph/event/listener.go
pkg/morph/subscriber/subscriber.go

Part of #2219, fixes #2304. Enough for 0.36.1 and we have a set of related tasks to do for 0.37.0.

(almost) Stop using deprecated subscription NeoGo APIs

---

CHANGELOG.md
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/internal/blobstortest/iterate.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/iterate.go

I tried to write tests for it (i really did) and they do pass for `FSTree` and did not pass for blobovniczas cause it caches every object during the iteration and `LazyHandler` means nothing for them (in other words that fix just does not relate them). So i decided to keep it as is for now since it works and _the only one_ unit test for `FSTree` looks strange IMO, cause we use a general test "framework" for every storage.

Fix/Iterating over just removed objects in FSTree

---

CHANGELOG.md
cmd/neofs-cli/internal/commonflags/flags.go
cmd/neofs-cli/internal/key/key_test.go
cmd/neofs-cli/internal/key/raw.go
cmd/neofs-cli/internal/key/wallet.go

Wallets were introduced way back when in 0.27.5 and that's the way keys should be stored. We've had enough transition period for people to adjust to using them. Binary keys are dangerous and inconvenient (NEP-6 is common for all of the Neo tooling, everyone knows how to use it), therefore we shouldn't provide support for them.
Related to #2136.

cli: drop support for binary keys, use wallets

---

.github/workflows/run-tests.yml

This is necessary to reduce the number of steps
in the make dev-env.
This saves a few minutes for each test run.
This PR is necessary for:
https://github.com/nspcc-dev/neofs-dev-env/pull/262

Add write permissions to the vendor/hosts file

---

pkg/services/object/acl/acl.go
pkg/services/object/acl/v2/util.go

Linter:
Error: func `unmarshalPublicKey` is unused (unused)
Error: func `unmarshalPublicKey` is unused (unused)

acl: drop unused unmarshalPublicKey

---

.github/workflows/go.yml

It's handled by setup-go now and it doesn't work anyway:
Restore cache failed: Dependencies file is not found in /home/runner/work/neofs-node/neofs-node. Supported file pattern: go.sum

github: drop obsolete cache step from test run

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/dump_hashes.go
cmd/neofs-adm/internal/modules/morph/dump_names.go
cmd/neofs-adm/internal/modules/morph/renew_domain.go
cmd/neofs-adm/internal/modules/morph/root.go
docs/cli-adm.md

Enough to at least have some visibility into the NNS and be able to renew things.

Adm NNS cmds

---

pkg/morph/deploy/deploy.go
pkg/morph/deploy/group.go
pkg/morph/deploy/group_test.go
pkg/morph/deploy/nns.go
pkg/morph/deploy/notary.go
pkg/morph/deploy/util.go

* one more iteration within #2195
i plan to add contracts' deployment in the next PR to reduce the amount of changes at a time (although there are a lot of current ones)
i've tested changes manually with NNS contract built from https://github.com/nspcc-dev/neofs-contract/tree/6e9b183b219353bd07a5d985f2ee38473f4f6a28 on x4 node cluster from [neo-go ](https://github.com/nspcc-dev/neo-go/blob/master/.docker/docker-compose.yml) project modified with Notary service
i guess it's possible to write unit tests using `neotest` framework, but it'll take too much time i bet
i also plan to describe the procedure in detail in `docs/` after approval (next PR i think)

Introduce procedure for the NeoFS Sidechain deployment

---

CHANGELOG.md
cmd/neofs-node/cache.go

Do not request morph values on morph cache misses concurrently. Closes #1248.

node: Do not update cache twice

---

CHANGELOG.md
cmd/neofs-node/cache.go
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/main.go
cmd/neofs-node/morph.go
cmd/neofs-node/netmap.go

Closes #1337. The https://github.com/nspcc-dev/neofs-node/pull/2406 but for SN. Also tested with https://github.com/notimetoname/neofs-dev-env/tree/local/add-rpc-morph-node.

fix/Restart SN services after `neo-go` is down

---

pkg/local_object_storage/blobstor/blobovniczatree/iterate.go
pkg/local_object_storage/blobstor/blobovniczatree/put_test.go

well, we're willing to get rid of complex blobovnicza tree. But this fix is simple, and it's needed to benchmark flat list of DBs within #2453

blobovnicza: Fix write error at zero depth

---

pkg/local_object_storage/blobstor/blobovniczatree/put_test.go

current results:
```
goos: linux
goarch: amd64
pkg: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/blobovniczatree cpu: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
BenchmarkBlobovniczas_Put/tree=1x0-8                 100          53517515 ns/op         4609697 B/op        109 allocs/op
BenchmarkBlobovniczas_Put/tree=10x0-8                100          53417156 ns/op         5213543 B/op        119 allocs/op
BenchmarkBlobovniczas_Put/tree=2x2-8                 100          52124287 ns/op         5117641 B/op        158 allocs/op
BenchmarkBlobovniczas_Put/tree=4x4-8                 100          37065895 ns/op         2129467 B/op        188 allocs/op
```
according to test, tree management doesn't really help when number of layers is small. 4x4 showed better performance which …

blobovnicza: Add benchmark to test different tree settings

---

CHANGELOG.md
pkg/services/object/acl/v2/service.go

object/put: Process session token of the original request in ACL checks

---

.github/workflows/run-tests.yml

Added a special variable that contains the address where the test result is stored.

workflows: Add TEST_RESULTS_HTTP_GATE env

---

.github/workflows/run-tests.yml

Added publishing docker logs to NeoFS in case of dev-env failed.
Example and tests result:
https://github.com/vvarg229/neofs-node/actions/runs/5789147617/job/15689567527
First, this PR needs to be merged:
https://github.com/nspcc-dev/neofs-testcases/pull/592

Post docker logs to NeoFS

---

CHANGELOG.md
cmd/neofs-cli/internal/client/client.go
cmd/neofs-cli/modules/container/set_eacl.go

force flag added, no-precheck deprecated, ownership check added
Refs #2436.

cli: set-eacl update

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/initialize.go

added checks for commands before wallet creation
Closes #2134.

neofs-adm: init and update-contracts are the only commands for wallets creation

---

cmd/neofs-cli/internal/client/client.go
pkg/services/object/internal/client/client.go

That is the only possible way `client.Client` can say stream has been closed (because of internal logic, not the network/unexpected errors) in the current API. It returned `bool` in the previous versions.
Closes #2513, closes #2502.

fix/Do not treat `EOF` as a network error

---

CHANGELOG.md
README.md
cmd/neofs-cli/internal/common/exit.go
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/container/delete.go
cmd/neofs-cli/modules/container/set_eacl.go
cmd/neofs-cli/modules/container/util.go
docs/cli-exit-codes.md

A new error code is added for awaiting timeout expiration.
Closes [#2380]

cli: add exit code error for timeout await expiration

---

.github/workflows/run-tests.yml

Add the expiration period for Allure test reports. Set the expiration period to 1 month for master, 2 weeks for pull requests and manual runs, no expiration for releases, and 1 week for other events.
First, we need to merge this PR:
https://github.com/nspcc-dev/neofs-testcases/pull/601
and 
add these repository variables to the neofs-node repo:
```
MASTER_EXPIRATION_PERIOD = 744
PR_EXPIRATION_PERIOD = 336
MANUAL_RUN_EXPIRATION_PERIOD = 336
OTHER_EXPIRATION_PERIOD = 168
```

workflows: Add expire to tests reports

---

.github/workflows/run-tests.yml

Because the PR https://github.com/nspcc-dev/neofs-dev-env/pull/272 is already merged, we need to change the ref from the temporary branch back to the master.

workflow: Change neofs-dev-env ref

---

CHANGELOG.md
cmd/neofs-cli/modules/bearer/create.go
cmd/neofs-cli/modules/object/lock.go
cmd/neofs-cli/modules/object/put.go
cmd/neofs-cli/modules/object/util.go
cmd/neofs-cli/modules/session/create.go
cmd/neofs-cli/modules/storagegroup/put.go

The expired-at flag replaces the deprecated lifetime flag. 
Closes #1574.

cli: unify usage of expired-at flag instead of lifetime flag

---

CHANGELOG.md
pkg/innerring/internal/blockchain/blockchain.go

@roman-khimov @AnnaShaleva note that i've left other session-related configurations unset https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.4/pkg/config#RPC, if u have any suggestions about non-default values pls let me know
* see also https://github.com/nspcc-dev/neo-go/issues/3106

ir: Always enable RPC sessions in local consensus launch mode

---

CHANGELOG.md
cmd/neofs-cli/modules/object/nodes.go
cmd/neofs-cli/modules/object/root.go

It applies placement policy rules to the current network map for the provided object. Works the same way `container nodes` does.

feat/Add `object nodes` command

---

Makefile

The directory is a Go lib package, not an application.

Makefile: Exclude `cmd/internal` from `make [all]` target

---

.github/testcases-env

Add flag to enable metabase resync on start.
This flag will be false by default and will not change the behavior of the system in any way.
These changes are needed for system tests, tests will change the RESYNC_METABASE flag.
https://github.com/nspcc-dev/neofs-testcases/issues/556
See also:
https://github.com/nspcc-dev/neofs-dev-env/pull/285

.github: Add flag to enable metabase resync

---

cmd/neofs-cli/modules/session/create.go

Added check of passing `--lifetime` flag by the user and handling of setting `defaultLifetime` value
Closes #2539.

neofs-cli: bugfix expire-at flag for session create command.

---

CHANGELOG.md
cmd/neofs-cli/modules/netmap/netinfo.go

By calling `neofs-cli netmap netinfo`, the user can get information about the container alias fee. NeoFS network configuration has a ContainerAliasFee parameter which is displayed.
Closes #2553.

neofs-cli: netmap netinfo displays ContainerAliasFee network config paramenter

---

CHANGELOG.md
cmd/neofs-lens/internal/blobovnicza/inspect.go
cmd/neofs-lens/internal/blobovnicza/root.go
cmd/neofs-lens/internal/flags.go
cmd/neofs-lens/internal/peapod/inspect.go
cmd/neofs-lens/internal/peapod/root.go
cmd/neofs-lens/internal/printers.go
cmd/neofs-lens/internal/storage/inspect.go
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-lens/internal/writecache/inspect.go
cmd/neofs-lens/internal/writecache/root.go
cmd/neofs-lens/root.go
cmd/neofs-node/config.go
cmd/neofs-node/storage/config.go

Added `neofs-lens object get --address cid/oid --config ./config-sn.yaml --out test.json`  This command pulls out the object from the StorageEngine physical snapshot.
Closes #1336.

neofs-lens: add new command object get

---

CHANGELOG.md
cmd/neofs-lens/internal/flags.go
cmd/neofs-lens/internal/meta/inspect.go
cmd/neofs-lens/internal/meta/list-garbage.go
cmd/neofs-lens/internal/meta/list-graveyard.go
cmd/neofs-lens/internal/meta/put.go
cmd/neofs-lens/internal/meta/root.go

This command places the object into the metabase. It can be useful if you want to add an object directly to the metabase.
`neofs-lens meta put --obj ./myobj --path ./meta.db`
Now if db doesn't exist it creates a new one, Is it expected behavior?
Closes #1816.

neofs-lens: add new command meta object put

---

CHANGELOG.md
cmd/neofs-cli/modules/object/put.go

The `object put` command previously could only retrieve the last `--attributes` parameter if multiple such parameters were provided. Now, the `object put` command correctly parses all `--attributes` values, whether they are provided as comma-separated or single values.
Closes #2427.

neofs-cli: fix pass of several object put --attributes flags

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/config.go

Changed error messages to hide details about implementation.
Closes #2556.

neofs-adm: change morph set config error message

---

.github/workflows/go.yml
cmd/neofs-node/config.go

copylocks: resetCaches passes lock by value: github.com/nspcc-dev/neofs-node/cmd/neofs-node.shared contains sync/atomic.Bool contains sync/atomic.noCopy (govet)
Introduced by #2485.

cmd: fix copyLocks issue

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/root.go
cmd/neofs-cli/modules/netmap/netinfo.go

Comments about the obligatory usage of the `--force` flag for setting unknown parameters have been added. `neofs-cli netmap netinfo` now displays it correctly.
Closes #2555.

neofs-adm: fix displaying values and improve documentation

---

.github/testcases-env

This commit rolls back e1aed14226c5ec28f71fa942bd82d2f07a952e3d It was a mistake to make that change.
Now it is not necessary, https://github.com/nspcc-dev/neofs-testcases/pull/608 allows you to do without a separate flag.

.github: Remove flag RESYNC_METABASE

---

pkg/morph/client/constructor.go

This reverts commit 3b1d8cde18dce7809347a5f8f65e4d079dc06533. It seems that the 
morph client is switching RPC nodes too often (even if no block is detected at 
all) with this setting turned on and is not possible to handle (route) 
notifications before the neo-go client closes the channels.

Revert "morph: Close RPC connections if any blocks appeared"

---

CHANGELOG.md
cmd/neofs-lens/internal/blobovnicza/inspect.go
cmd/neofs-lens/internal/blobovnicza/root.go
cmd/neofs-lens/internal/meta/inspect.go
cmd/neofs-lens/internal/meta/root.go
cmd/neofs-lens/internal/peapod/inspect.go
cmd/neofs-lens/internal/peapod/root.go
cmd/neofs-lens/internal/storage/inspect.go
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-lens/internal/writecache/inspect.go
cmd/neofs-lens/internal/writecache/root.go

Deprecated inspect commands are functional but hidden from help and marked when are called.
Example:
```
neofs-lens storage inspect  --address ApueGak8ZwgXtxhhV3Bf97sbuByBDFkJSAZ4921g7hUr/E6bMcEHxjnrMRaRx5fjPe6WGsFS3jW9Q6SmMvHSskmNr  --config ./data/config/config-sn.yaml
Command "inspect" is deprecated, will be removed in the next release. Use `get` instead.
Version: v2.13
Type: REGULAR
CID: ApueGak8ZwgXtxhhV3Bf97sbuByBDFkJSAZ4921g7hUr
ID: E6bMcEHxjnrMRaRx5fjPe6WGsFS3jW9Q6SmMvHSskmNr
Owner: NZ9DJJkHgKTanE8CHWeTbWZNCHZQBsTqhX
CreatedAt: 3
PayloadSize: 404
Attributes:
FileName: new_wallet.json
Timestamp: 1693585925
``` 
``` 
neofs-lens storage -h …
```

neofs-lens: rename `inspect` commands to `get`

---

CHANGELOG.md
cmd/neofs-lens/internal/meta/root.go
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-node/config.go
cmd/neofs-node/session.go
pkg/local_object_storage/blobovnicza/blobovnicza.go
pkg/local_object_storage/blobstor/peapod/peapod.go
pkg/local_object_storage/engine/control_test.go
pkg/local_object_storage/pilorama/boltdb.go
pkg/local_object_storage/writecache/util.go
pkg/services/session/storage/persistent/options.go

Previously, we always use 100ms timeout for BoltDB flocks.
Closes: #2499.

boltdb: increase timeout to 1s

---

cmd/neofs-cli/internal/client/client.go
pkg/services/object/internal/client/client.go

This reverts commit 4909a08d53b5f1a920006642ae63fe99c240197c. This error is not expected anymore. See https://github.com/nspcc-dev/neofs-sdk-go/issues/496. Closes #2520.

Revert "cli, node: Do not treat `EOF` as a network error"

---

CHANGELOG.md
cmd/neofs-cli/modules/container/set_eacl.go

Remove the "no-precheck" flag, which is equivalent to "force" (skips verification) and has been deprecated since #2490.
Closes: #2496.

neofs-cli: container set-eacl removal of the no-precheck flag

---

cmd/neofs-node/config/policer/config.go
docs/storage-node-configuration.md
pkg/services/policer/policer.go

10 objects per second is OK and seems to be similar to what we have on current public networks.

policer: use 1s as the default replicaton cooldown

---

CHANGELOG.md
cmd/neofs-lens/internal/printers.go
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-lens/internal/storage/status.go
pkg/local_object_storage/blobstor/status.go
pkg/local_object_storage/engine/status.go
pkg/local_object_storage/metabase/status.go
pkg/local_object_storage/shard/status.go
pkg/local_object_storage/writecache/status.go
pkg/local_object_storage/writecache/writecache.go

New command:
```
neofs-lens storage status --address ApueGak8ZwgXtxhhV3Bf97sbuByBDFkJSAZ4921g7hUr/E6bMcEHxjnrMRaRx5fjPe6WGsFS3jW9Q6SmMvHSskmNr  --config ./data/config/config-sn.yaml
``` 
Expected result looks like:
```
Shard ID:  7cCVnpBHZMZdfo8GfhKCSf
Substorage  0
Blob Type:  peapod
Blob Path:  ./data/peapod1.db
Blob Error:  status: code = 2049 message = object not found
Substorage  1
Blob Type:  fstree
Blob Path:  ./data/fstree1
Blob Error:  status: code = 2049 message = object not found
Metabase
Metabase storage ID:  
Metabase path:  ./data/meta1
Metabase object status:  NOT IN GRAVEYARD
Metabase object error:  <nil>
Writecache
Writecache DB path:  
Writecache DB error:  <nil>
Writecache  FSTree path:  
Writecache FSTree error:  <nil>
Shard ID:  QQD7WcPs6crwwSSZ3A3Ak6
Substorage  0 …
```

neofs-lens: storage status new command

---

pkg/local_object_storage/blobstor/fstree/control.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/fstree/fstree_write_generic.go
pkg/local_object_storage/blobstor/fstree/fstree_write_linux.go
pkg/local_object_storage/blobstor/fstree/fstree_write_specific.go

fstree: handle unsupported O_TMPFILE, fix #2609

---

.golangci.yml
go.mod

It is archived and not needed after the standard `error` package release. Sometimes we (our IDEs) import it by a mistake: 4c1ab5e4a7a0ab38baf131a0fa5bd9798598d6e9.
See https://github.com/nspcc-dev/neofs-node/pull/2622#discussion_r1363565785

fix/Deny github.com/pkg/errors module usage

---

CHANGELOG.md
cmd/neofs-cli/modules/object/util.go
cmd/neofs-cli/modules/util/keyer.go
pkg/local_object_storage/blobstor/fstree/control.go
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/blobstor/fstree/fstree_write_generic.go
pkg/local_object_storage/blobstor/fstree/fstree_write_linux.go
pkg/local_object_storage/blobstor/put.go

_Originally posted by @smallhive_
```
warn	engine/engine.go:159	could not put object to shard	{"shard_id": "8TAArEwewr9p3aGppk4GVM", "error count": 24, "error": "could not put object to BLOB storage: operation not supported"}
```

blobstor: Additional context of errors

---

CHANGELOG.md
cmd/neofs-ir/main.go
cmd/neofs-node/main.go
cmd/neofs-node/metrics.go
cmd/neofs-node/pprof.go
pkg/util/http/calls.go

Metrics port should be opened before all other ports, and start served before all other services.
Closes: #2428.

metrics: set the highest priority for metrics service.

---

CHANGELOG.md
cmd/neofs-node/control.go
cmd/neofs-node/main.go
pkg/innerring/innerring.go

control: set the highest priority for control service.

---

CHANGELOG.md
cmd/neofs-cli/modules/container/list_objects.go

Previously, `container list-object` command with `--with-attr` flag printed objects' attributes in raw way. In particular, creation timestamp was showed in Unix format (e.g. 1692609422). While this format is widely known, its human-unreadable. To facilitate the user's experience, the output should be supplemented with a readable format similar to the `object head` command.
Use Go `time.Time` stringer and print the result along with Unix time value. From:
```
HKupeALCqk3VUSmuRXTGdJt6ZZQoJsJ3VtNVV8Pu1Xjd
Timestamp=1692609422
```
to:
```
HKupeALCqk3VUSmuRXTGdJt6ZZQoJsJ3VtNVV8Pu1Xjd
Timestamp=1692609422 (2023-08-21 11:17:02 +0200 CEST)
```

cli/container: Pretty-print creation timestamp in `list-objects` output

---

CHANGELOG.md
go.mod
go.sum

Stable deps

---

cmd/neofs-node/object.go
pkg/services/object/put/v2/service.go
pkg/services/object/put/v2/streamer.go

It does not work this way since 508a28fdc0c41cc63a64fbfd43fc56719b6e716d.

node/put: Do not use session keystorage for nothing

---

CHANGELOG.md
pkg/morph/deploy/contracts.go
pkg/morph/deploy/deploy.go

deploy: Fix witnesses for Balance and Container contract deployments

---

CHANGELOG.md
cmd/neofs-node/config.go
pkg/innerring/rpc.go
pkg/network/cache/client.go
pkg/network/cache/multi.go

It simplifies connection drop inspection cause after the first connection drop, there are a lot of `client has recently failed, skipping` logs, and it is not clear what exact reason did not allow the node to communicate with a "problem" one. It could be dropped in the future, but a connection loss for 30s (default reconnection interval for now) is not a normal situation in general, and it causes replication processes, data duplication, etc., so logs about it can be kept.

node/client-cache: Log errors that led to a connection drops

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/generate.go
cmd/neofs-adm/internal/modules/morph/generate_test.go
cmd/neofs-adm/internal/modules/morph/root.go

Add `wallets-number` flag that "duplicates" requests to the `neofs-adm`. Passwords and labels are the same for all the wallets being created. Names differ with the suffix-numbers.

adm: Allow generation more than one SN wallet per call

---

cmd/neofs-adm/internal/modules/morph/root.go

Neo-go naming is really confusing here. Regression from d41d7a7d37ecec6a86bed9352e92d177a6f8f41b. Closes #2706.

adm: Do not create but open wallet file

---

CHANGELOG.md
cmd/neofs-lens/internal/meta/get.go
cmd/neofs-lens/internal/meta/root.go
cmd/neofs-lens/internal/peapod/get.go
cmd/neofs-lens/internal/peapod/root.go
cmd/neofs-lens/internal/storage/get.go
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-lens/internal/writecache/get.go
cmd/neofs-lens/internal/writecache/root.go

rm/Delete deprecated `inspect` commands

---

CHANGELOG.md
pkg/morph/client/constructor.go

Do not fail if the first one is unavailable but more endpoints are provided.

morph: Try all endpoints on client creation

---

.github/workflows/run-tests.yml

Changed test report publishing from custom to using the gh-push-allure-report-to-neofs action.
This reduces the amount of code and unifies workflow with other projects in the organization.

Change test report publication

---

CHANGELOG.md
pkg/innerring/processors/netmap/process_peers.go

See #2612, https://github.com/nspcc-dev/neofs-contract/pull/324. Refs #830.

ir: Do not create new notary requests for SN netmap entrances

---

CHANGELOG.md
pkg/innerring/processors/netmap/nodevalidation/availability/validator.go

Logs like "*number* differs *number*" may confuse, public keys are more common.

ir: Do not hash public keys to check orig/announced SN diff

---

config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/innerring.go
pkg/morph/client/nns.go
pkg/morph/deploy/funds.go

Add some Inner Ring UX improvements

---

.github/workflows/run-tests.yml

Changed test report publishing from custom to using the gh-push-allure-report-to-neofs action.
This reduces the amount of code and unifies workflow with other projects in the organization.
Tests result:
https://github.com/vvarg229/neofs-node/actions/runs/7602847388/job/20703858094?pr=53
https://http.t5.fs.neo.org/86C4P6uJC7gb5n3KkwEGpXRfdczubXyRNW5N9KeJRW73/417-1705859595/index.html
First, this PR should be merged:
https://github.com/nspcc-dev/gh-push-allure-report-to-neofs/pull/4

workflows: Change test report publication

---

CHANGELOG.md
pkg/morph/client/notifications.go

Scenario:
0. at least one subscription has been performed
1. another subscription is being done
2. a notification from one of the `0.` point's subs is received
If `2.` happens b/w `0.` and `1.` a deadlock appears since the notification routing process is locked on the subscription lock while the subscription lock cannot be unlocked since the subscription RPC cannot be done before the just-arrived notification is handled (read from the neo-go subscription channel).
Relates #2559.

morph: Fix subscription deadlock

---

CHANGELOG.md
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go

node: Validate session tokens attached to objects

---

CHANGELOG.md
pkg/services/container/morph/executor.go
pkg/services/container/morph/executor_test.go

If container session token is incorrect, there is no need in Alphabet's check, the error can be returned immediately to a client; otherwise he has to wait for the TX to persist infinitely with not feedback. Closes #2466.

fix: Do not allow broken session token by SN

---

CHANGELOG.md
cmd/neofs-cli/modules/object/put.go
go.mod
go.sum
pkg/services/object/put/slice.go

* based on https://github.com/nspcc-dev/neofs-sdk-go/pull/539

Reduce memory consumption for data slicing into objects

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/deploy.go

It's the only way since neofs-contract 0.18.0, "register" just fails with
Error: could not perform test invocation: script failed (FAULT state) due to an error: at instruction 1794 (THROW): unhandled exception: "TLD denied"

neofs-adm: use registerTLD to register TLD

---

CHANGELOG.md
pkg/services/container/morph/executor.go
pkg/services/container/morph/executor_test.go

Do not require container ID to be set if wildcard is true. Also, for all containers case check that a requested operation relates a container that belongs to the attached token's issuer.

node: Support wildcard for container sessions

---

.github/workflows/build.yml
CHANGELOG.md
docs/release-instruction.md

And rework release procedure a bit. Don't rely on external tools and make CHANGELOGs better.

workflows: add build/release workflow

---

pkg/network/transport/accounting/grpc/service.go
pkg/network/transport/container/grpc/service.go
pkg/network/transport/netmap/grpc/service.go
pkg/network/transport/object/grpc/service.go
pkg/network/transport/reputation/grpc/service.go
pkg/network/transport/session/grpc/service.go

* https://pkg.go.dev/github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/object/grpc#UnimplementedObjectServiceServer
* https://github.com/grpc/grpc-go/issues/3794

node: Respond with `UNIMPLEMENTED` status when RPC is not yet supported

---

CHANGELOG.md
pkg/services/object/get/exec.go

This reverts commit 907f427b99768ff010834621578441ef81dc0ff9.
GET requests with TTL=1 are absolutely correct regardless of the need to assemble the object. This TTL blocks request forwarding - it does not happen. At the same time, assembling an object on the server spawns new requests from scratch, which is not forwarding. The original commit does not have a description of the cause, and it was never discovered.
Fixes #2447.

object: Perform assembly with `TTL=1`

---

go.mod
go.sum
pkg/services/object/acl/v2/service.go

Node code is not ready for them, will be updated via another PR.

go.mod: Downgrade SDK to the version without split changes

---

CHANGELOG.md
go.mod
go.sum

* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/561
* blocked by https://github.com/nspcc-dev/neofs-node/pull/2750
to check:
1. run dev env
2. `make bin/neofs-cli`
3. `neofs-cli -r grpcs://s01.neofs.devenv:8080 netmap netinfo --timeout 3s`

*: Receive explicit reasons for NeoFS API dial failures

---

Makefile
docs/release-instruction.md

btw we also have https://github.com/nspcc-dev/neofs-node/blob/df2cc08a08191ce0f6ff84f36c393ed9b26f20da/docs/release-instruction.md?plain=1#L12: need to ref https://github.com/nspcc-dev/neofs-testcases or be removed since we have GH action with integration tests? @roman-khimov 
i always skip this step

Release guide fixes

---

CHANGELOG.md
cmd/neofs-adm/internal/modules/morph/generate.go

A copy-paste regression from the d41d7a7d37ecec6a86bed9352e92d177a6f8f41b.

adm: Read GAS from the correct flag in `generate-storage-wallet`

---

go.mod
go.sum
pkg/services/object/acl/v2/service.go

node: Use header limit from SDK

---

pkg/services/object/acl/eacl/v2/headers.go

SplitID may be nil for small objects too (the same way it is for the new V2 split scheme). Do not try to search for a non-existing first object for small objects.

node/put/acl: Do not treat small objects as big

---

pkg/local_object_storage/metabase/VERSION.md

fix a typo: `auxilliary`->`auxiliary`

chore: fix typos

---

CHANGELOG.md
cmd/neofs-lens/internal/object/link.go
cmd/neofs-lens/internal/object/root.go
cmd/neofs-lens/root.go

V2 link scheme does not allow analyzing link objects without additional tools due to the missing children info in the split header: children are in the link object's payload. Add a simple command for inspecting new link objects.

neofs-lens: Add a simple link objects inspector

---

CHANGELOG.md
cmd/neofs-node/grpc.go
cmd/neofs-node/object.go
cmd/neofs-node/policy.go
cmd/neofs-node/policy_test.go
pkg/core/client/client.go
pkg/network/cache/multi.go
pkg/network/transport/object/grpc/replication.go
pkg/network/transport/object/grpc/replication_test.go
pkg/network/transport/object/grpc/service.go
pkg/services/object/put/local.go
pkg/services/object/put/remote.go
pkg/services/replicator/process.go

* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/565
---
replication demux inside PUT is planned for the next PR

Use new API for background replication

---

.github/workflows/run-tests.yml

Testcases were updated to 0.30.0 behavior in https://github.com/nspcc-dev/neofs-testcases/pull/772 so 0.29.0 will produce false errors. And we should be using the latest stable anyway.

.github: update S3 gateway used for tests to 0.30.0

---

CHANGELOG.md
pkg/services/object/acl/eacl/v2/eacl_test.go
pkg/services/object/acl/eacl/v2/headers.go

If we are checking a first object, it is impossible to HEAD the first object to check ACL rules, get its parent directly from the header instead. It is also an optimization for last and LINK object ACL checks (they have a parent in the header too).

node/put: Fix fetching first object for a first object

---

CHANGELOG.md
pkg/morph/client/container/client.go
pkg/morph/client/container/delete.go
pkg/morph/client/container/eacl_set.go
pkg/morph/client/container/estimations.go
pkg/morph/client/container/put.go
pkg/morph/client/static.go

Provide notary signature status with explicit parameter. Some calls are always expected to be Alphabet signed (at least for the current contracts), make it explicit for a code reader, that is more error proof. This commit also fixes container size estimations writing: they were tried to be notary signed, but the Alphabet does not handle such requests. This is also the reason why this kinda refactor does not touch other contracts; general client improvements can be done with another PR.

pkg/morph/container: Do not create client with notary status

---

CHANGELOG.md
pkg/local_object_storage/metabase/iterators.go

Errors in GC cycle can be logged, and the cycle can be continued, there is no reason not to handle leftover garbage. Make it async (up to 1000 concurrent calls) cause most of the meta code is performed in bbolt transaction, so blocking will slow general performance.

meta: Do not stop iteration in GC on errors

---

CHANGELOG.md
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/inhume_test.go
pkg/local_object_storage/engine/shards.go

It is possible to store an object on a shard that is not the first one after object address hash sorting and not-found-object-inhuming is also errorless, so the actual shard does not delete objects in such cases. Closes #2821.

engine: Be ready to delete objects on unexpected shards

---

.github/workflows/build.yml
CHANGELOG.md

workflows: build arm64/darwin binaries

---

CHANGELOG.md
pkg/services/object/tombstone/verify.go
pkg/services/object/tombstone/verify_test.go

First objects do not have `first` field set, so searching with empty ID is a no-op which means no LINK will ever be found => dropping a first object is allowed.

node/tombstones: Protect first objects from removal

---

cmd/neofs-adm/internal/modules/morph/balance.go
cmd/neofs-adm/internal/modules/morph/config.go
cmd/neofs-adm/internal/modules/morph/container.go
cmd/neofs-adm/internal/modules/morph/deploy.go
cmd/neofs-adm/internal/modules/morph/dump_hashes.go
cmd/neofs-adm/internal/modules/morph/dump_names.go
cmd/neofs-adm/internal/modules/morph/epoch.go
cmd/neofs-adm/internal/modules/morph/estimation.go
cmd/neofs-adm/internal/modules/morph/initialize.go
cmd/neofs-adm/internal/modules/morph/initialize_deploy.go
cmd/neofs-adm/internal/modules/morph/initialize_nns.go
cmd/neofs-adm/internal/modules/morph/netmap_candidates.go
cmd/neofs-adm/internal/modules/morph/remove_node.go
cmd/neofs-adm/internal/modules/morph/renew_domain.go

And use a bit more of NNS wrapper.
Notice that this changes "alphabet X" to "alphabetX" in dump output, but I consider this to be an improvement (since that's the contract name).
It also deoptimizes some carefully crafted code to extract a number of names in one call. Likely it's not a performance issue you care about and it's actually somewhat broken in that it assumes one result per invocation (but you can get zero or more than one).
Many more things can be improved, but let's start with this.
Refs. #2826.

adm: never use GetContractStateByID(1) to retrieve NNS hash

---

CHANGELOG.md
pkg/services/util/sign.go

support for non-status returns makes no sense after such a period

node: Return status responses only

---

CHANGELOG.md
pkg/services/object/get/assembly_v2.go
pkg/services/object/get/assembly_v2_test.go

If small object bounds equal a range request bound, it led to [X:0] requests. Closes #2849.

node/range: Do not request for empty payload

---

CHANGELOG.md
pkg/innerring/config.go
pkg/innerring/config_test.go

_Originally posted by @evgeniiz321_
following P2P config
```yaml
p2p:
listen:
- localhost:59893
```
led to no consensus for 4x setup although it should have. Making it
```yaml
p2p:
listen:
- localhost:59893
peers:
min: 2
```
fixed the problem. Thus, the declared default was not fulfilled https://github.com/nspcc-dev/neofs-node/blob/9a9a5d5f4a9452cbb566d51548390d31f9038e5d/config/example/ir.yaml#L76-L78

ir/config: Fix unenforced `morph.consensus.p2p.peers.min` config default

---

.github/workflows/run-tests.yml

With updated SDK and NeoGo dependencies, 0.30.0 fails to start currently.

workflows: switch to post-0.30.0 S3 test gateway

---

CHANGELOG.md
cmd/neofs-node/object.go
cmd/neofs-node/transport.go
pkg/network/cache/multi.go
pkg/services/object/put/distributed.go
pkg/services/object/put/local.go
pkg/services/object/put/prm.go
pkg/services/object/put/proto.go
pkg/services/object/put/proto_test.go
pkg/services/object/put/remote.go
pkg/services/object/put/service.go
pkg/services/object/put/streamer.go
pkg/services/object_manager/placement/traverser.go

* based on and blocked by #2801 (first 2 commits)

node/objects: Distribute objects in container via replication protocol 

---

CHANGELOG.md
cmd/neofs-lens/internal/storage/root.go
cmd/neofs-lens/internal/storage/sanity.go

Checks can be extended later (or in this PR if suggestions appear).

neofs-lens/storage: add a sanity storage check

---

CHANGELOG.md
cmd/neofs-node/policy.go
cmd/neofs-node/policy_test.go

code and unit tests are ready, intergration tests pass. I also want to take a memory profile in devenv
---
i created 5 containers and ran 30 routines sending 1000 search queries (each time to random container)
---
<details>
<summary>Go script</summary>
```go
func TestDevenv(t *testing.T) {
strCnr := []string{
"3SDKVLon6bk6ALm8PCEjaGHUeg8cP5d6cvSJdpuMJ3qy",
"5gGHUYnAXfB7y5XSFJb4SBr2g3NvEnkAELDAV9rxFdWL",
"65NX4euCiJDDkduNeSc8puo7oKa3ddZC2dHxNMSS3UBA",
"9EPJGmDDDv9iNqP1rAy7pyYuaJHRy2XSyMZt81DL35cD",
"ArUd3NXPUhaDLNZuEKYHjbc4GS7u4nViDTKbyLiDtENW",
}
const endpoint = "s01.neofs.devenv:8080"
const workers = 30
ctx := context.Background()
signer := test.RandomSignerRFC6979(t)
cnrs := make([]cid.ID, len(strCnr))
for i := range strCnr {
require.NoError(t, cnrs[i].DecodeString(strCnr[i]))
}
c, err …
```

Cache storage policy application results (`Search`, `Replicate`)

---

CHANGELOG.md
config/example/ir.yaml
pkg/innerring/internal/blockchain/blockchain.go

Follow https://github.com/nspcc-dev/neo-go/pull/3518 for new and otherwise default setups, we don't need this long history of chain.

ir: lower default max_traceable_blocks to 17280

---

CHANGELOG.md
cmd/neofs-node/config/cast.go
cmd/neofs-node/config/cast_test.go
cmd/neofs-node/config/test/config.json
cmd/neofs-node/config/test/config.yaml

It was not used in practice before, so no issues were opened, or tests were written, but it still looks like a valid configuration value.

fix/allow "1b" config values for memory amount

---

.dockerignore

It was 688Mb on my laptop, never cleaned it and never know what exactly is using it but we have it in `.gitignore` since d83f2e8b47e2da1e14c5a6a05db223fc86736b18. Building docker images locally made docker send this full dir as a context. Tried to drop it, and make my ordinary commands (lint, tests, buildings), but nothing created anything new in this dir. Dropping this dir completely (from .gitignore too) is preferable if anybody knows what this is for and also can prove that it is not used anymore.

.dockerignore: exclude .cache directory

---

cmd/neofs-node/config.go
cmd/neofs-node/main.go
cmd/neofs-node/morph.go
cmd/neofs-node/netmap.go
pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/innerring/notary.go
pkg/morph/client/client.go
pkg/morph/client/notary.go

neofs-adm is not touched to save mental health (https://github.com/nspcc-dev/neofs-node/issues/2905 was left). Closes #2902.

Feat/use neo-go 0.106.3 features

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/object.go
cmd/neofs-node/policy.go
cmd/neofs-node/policy_test.go
pkg/services/object/get/container.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go

* continues #2892
---
i created 2 containers with 5 object in each and ran 30 routines sending 1000 GET queries (each time random object)
---
<details>
<summary>Go script</summary>
```go
strObjs := []string{
"47pRu4GKKHL3yJ5wkXRDZj5QsyfH3wUUy27x9eEp7wgK/7GRiZmkxHruwrR5YbwfiTCMzo5rnEHr8HmyNAPwAEzex",
"47pRu4GKKHL3yJ5wkXRDZj5QsyfH3wUUy27x9eEp7wgK/3ZSUCYqacwGY3teqJm3f9gDYSsEtB4uccXUp5in6jXBc",
"47pRu4GKKHL3yJ5wkXRDZj5QsyfH3wUUy27x9eEp7wgK/EMdsnvaUK2XQtxLf1zFjVeFFtbszEwKu8mvYt9W15oMw",
"47pRu4GKKHL3yJ5wkXRDZj5QsyfH3wUUy27x9eEp7wgK/En1K6HVfzoQtX9Vn2nW85szWduXqepdbmeAt9t2NMQJL",
"47pRu4GKKHL3yJ5wkXRDZj5QsyfH3wUUy27x9eEp7wgK/B7UjiPD8UcCQsWHpDLZWswATnA7q4bWvbHAvJJXCtbPq",
"2GN486btkTpxsYHsVjz5tZzug65YiSFUAYqAQiEkg4sg/FtRXxUBiTteyCM5QyeKKwFsJiJsNQGDMG31dTchagep3", …
```

Cache storage policy application results (`Get`/`Head`/`GetRange`)

---

CHANGELOG.md
cmd/neofs-node/object.go
pkg/services/object/acl/v2/opts.go
pkg/services/object/acl/v2/service.go

Split objects are validated and it required to do some additional requests for it. Such operation can be restricted for a non-container node, so checking for it is an unsolvable problem, skip ACL checks in such cases. Closes #2909.

node/acl: fix acl checks for non-container nodes

---

CHANGELOG.md
cmd/neofs-cli/modules/acl/extended/create.go
cmd/neofs-cli/modules/acl/extended/create_test.go
cmd/neofs-cli/modules/util/acl.go

Set up account alongside pub key in eacl rules in CLI

---

cmd/neofs-cli/modules/util/acl.go

Regression from c72af12127e852779d4c3dddd648a5b6326da048. As I have already said in associated PR, new SDK turned out to be a counter-CLI thing.

cli: do not overwrite parsed eacl rules

---

pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/shard/control.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/gc_test.go
pkg/local_object_storage/shard/shard.go

Similar to edc447f530cd040ab4c2e79e06235b8271680183, we can't have any meaninful context here and current context checks are broken. Fixes #1911, the last case of
Error in `cmd/neofs-node/config.go`: `Function `Reload->Init->init->listenEvents` should pass the context parameter`.
goes away with this.

shard: drop more of context from local stores

---

pkg/local_object_storage/metabase/delete_test.go

Behavior has changed a few times since the original implementation. Also, the test was broken a little in 8107c8d1a9cc2635510988828e5bfeec13656b4d. Parent/child relations were changed and now are treated differently at higher levels, so this test is not so important (see new `TestDeleteAllChildren` below, it plays a more important role in metabase testing), but keeping it in working condition with correct statements is not a bad idea.

meta: fix `Delete` test

---

CHANGELOG.md
cmd/neofs-cli/modules/container/create.go

Create named container from CLI

---

cmd/neofs-adm/main.go

Fix error format, that is broken from #2942, becuse of `SilenceErrors` in `cobra` command.

Fix error format in `neofs-adm`

---

CHANGELOG.md
cmd/neofs-cli/modules/container/create.go

Because of https://github.com/nspcc-dev/neofs-node/issues/2682#issuecomment-2381331159, rewrite #2950.
Closes #2682.

Add `--global-name` flag for `neofs-cli container create`

---

CHANGELOG.md
cmd/neofs-cli/modules/util/sign_session.go
pkg/innerring/processors/container/common.go

CLI change is under discussion, see https://github.com/nspcc-dev/neofs-node/issues/2947#issuecomment-2388521485

Fix unauthorized container ops with sessions

---

CHANGELOG.md
cmd/neofs-ir/main.go
cmd/neofs-node/config.go

logs: hide timestamp if the program is run not in TTY

---

CHANGELOG.md
cmd/neofs-lens/internal/fstree/cleanup.go
cmd/neofs-lens/internal/fstree/root.go
cmd/neofs-lens/root.go
pkg/local_object_storage/blobstor/fstree/fstree.go

Add `lens` command and also clean up due startup.
Closes #2291.

fstree : clean up temporary files

---

CHANGELOG.md
config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/config_test.go

Closes #2420.
Is it necessary to document default ports, except the example config?

ir/config: assign default to missing port in TCP addresses

---

CHANGELOG.md
docs/storage-node-configuration.md

Small improvement to the SN-configuration document. I found several sections that were not included in the structure table at the top of the document, making navigation more difficult without them.  
Feel free to reject if you don't like it.

docs: Add several missing sections to the SN structure table

---

CHANGELOG.md
cmd/neofs-cli/modules/control/object.go
cmd/neofs-cli/modules/control/object_revive.go
pkg/local_object_storage/engine/revive.go
pkg/local_object_storage/metabase/revive.go
pkg/local_object_storage/metabase/revive_test.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/shard/revive.go
pkg/services/control/convert.go
pkg/services/control/rpc.go
pkg/services/control/server/object_revive.go
pkg/services/control/service.pb.go
pkg/services/control/service.proto
pkg/services/control/service_grpc.pb.go
pkg/services/control/service_neofs.pb.go

Revive dead object via control service

---

CHANGELOG.md
pkg/morph/client/constructor.go

Defect of 0d08b51afe772444a5bf280b2c6750bb1d001d48. Previously, node unconditionally visited all configured FS chain endpoints, and the result of the connection to the last address was final. In the case where the previous nodes (at least one) were available but the last one was not, a general init error occurred.
Now node breaks on first successful dial.
Fixes #2986.

node: Fix false negative connection to FS chain in multi-endpoint setup

---

cmd/neofs-cli/modules/object/hash.go

Closes #1693.
The `object hash` command has logic when `len(ranges) == 0`, so I don't think it should be made obligatory.

cli: add a default range for `object hash` to cli `help`

---

CHANGELOG.md
cmd/neofs-cli/modules/container/create.go
cmd/neofs-cli/modules/object/put.go

cli: fix overriding of the `Timestamp` container attribute

---

CHANGELOG.md
cmd/internal/configvalidator/validate.go
cmd/neofs-ir/defaults.go
cmd/neofs-ir/defaults_test.go
cmd/neofs-ir/internal/validate/config.go
cmd/neofs-ir/internal/validate/validate.go
cmd/neofs-ir/internal/validate/validate_test.go
cmd/neofs-node/config/config.go
cmd/neofs-node/config/internal/validate/config.go
cmd/neofs-node/config/internal/validate/validate.go
cmd/neofs-node/config/internal/validate/validate_test.go
cmd/neofs-node/config/opts.go
cmd/neofs-node/config/test/config.go
config/example/node.json
config/example/node.yaml
config/mainnet/config.yml
config/testnet/config.yml
docs/storage-node-configuration.md

Closes #2663, #1950.
The problems I have encountered:
- node config: `grpc` section with list of structures and `node` section with unlimited number of attributes.
- `.env` files are not being processed, because of the work of the `viper` package. Should I do it? It might be more difficult.

Reject configuration with unknown fields

---

CHANGELOG.md
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/metabase/control_test.go

metabase: `Open(readOnly)` moves metabase in RO mode

---

CHANGELOG.md
cmd/neofs-node/config.go
docs/sighup.md
pkg/morph/client/client.go
pkg/morph/client/constructor.go
pkg/morph/client/multi.go
pkg/morph/client/reload.go

morph: support reloading morph endpoints with sighup

---

CHANGELOG.md
cmd/neofs-ir/main.go
cmd/neofs-node/config.go

The default Zap config is:
> Sampling is enabled at 100:100 by default, meaning that after the first 100 log entries with the same level and message in the same second, it will log every 100th entry with the same level and message in the same second. You may disable this behavior by setting Sampling to nil.
It leads to message loss too easily and we care a lot about each and every object. Notice that it was disabled in NeoGo as well in a52e016c22de2269fcc7362f33317cebfa7e8e4c (https://github.com/nspcc-dev/neo-go/pull/598).

ir/node: disable log sampling

---

pkg/local_object_storage/engine/container.go
pkg/local_object_storage/engine/control.go
pkg/local_object_storage/engine/delete.go
pkg/local_object_storage/engine/engine.go
pkg/local_object_storage/engine/evacuate.go
pkg/local_object_storage/engine/exists.go
pkg/local_object_storage/engine/get.go
pkg/local_object_storage/engine/head.go
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/engine/inhume_test.go
pkg/local_object_storage/engine/lock.go
pkg/local_object_storage/engine/put.go
pkg/local_object_storage/engine/range.go
pkg/local_object_storage/engine/revive.go
pkg/local_object_storage/engine/select.go
pkg/local_object_storage/engine/shards.go
pkg/local_object_storage/engine/status.go
pkg/local_object_storage/engine/tree.go

This continues #3008 with internal refactoring that is mostly about making code simpler and dropping useless code.

Simplify engine internals

---

.docker/Dockerfile.adm
.docker/Dockerfile.cli
.docker/Dockerfile.ir
.docker/Dockerfile.storage
.docker/Dockerfile.storage-testnet
Makefile

The GH workflow uses the [build-push-action](https://github.com/docker/build-push-action), where images are built with `buildx`. So I made it like this in our `Makefile`.
Also, fix warnings in Dockerfiles.
Closes #3006.

Makefile: use `buildx` component to build images with BuildKit

---

cmd/neofs-node/config.go

It was unavailable at feature release time.

node: use version attribute setter from SDK

---

CHANGELOG.md
cmd/neofs-lens/internal/peapod/root.go
cmd/neofs-lens/internal/storage/sanity.go
cmd/neofs-node/validate.go
cmd/peapod-to-fstree/main.go
cmd/peapod-to-fstree/main_test.go
pkg/local_object_storage/blobstor/peapod/peapod.go

Closes #2924.
Is there anything else I should do in this pr?

Deprecate peapod, provide migration to fstree

---

CHANGELOG.md
cmd/neofs-node/attributes.go
cmd/neofs-node/attributes_test.go
cmd/neofs-node/config.go
cmd/neofs-node/container.go
cmd/neofs-node/netmap.go
docs/sighup.md
pkg/core/object/fmt.go
pkg/local_object_storage/blobstor/put_test.go
pkg/morph/client/reload.go
pkg/services/object/tombstone/verify_test.go

Closes #1870.
Also fix bug from #2998, that incorrectly checked when to reconnect.

node: support reloading node attributes with SIGHUP

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/control.go
cmd/neofs-node/main.go
cmd/neofs-node/metrics.go
cmd/neofs-node/netmap.go
cmd/neofs-node/object.go
cmd/neofs-node/pprof.go
cmd/neofs-node/storage.go

Closes #1868.
Is it right that we should reload services, even if the config is not updated?
There is also such a linter error:
```contextcheck  Function `preRunAndLog->preRunAndLog$2->Shutdown` should pass the context parameter```
Do I need to pass the context honestly or is there some another way?

metrics, pprof: support reloading services with SIGHUP

---

CHANGELOG.md
pkg/services/object/put/distibuted_test.go
pkg/services/object/put/distributed.go

If ants pool is busy and cannot take task, early `return` without `wg.Wait()`
leads to `iterateNodesForObject`'s `return` and all the buffers for binary
replication from now may be reused while are still in use by the other routines
inside the pool. Wait for WG before any `return` is called. Closes https://github.com/nspcc-dev/neofs-node/issues/2978, https://github.com/nspcc-dev/neofs-node/issues/2988,
https://github.com/nspcc-dev/neofs-node/issues/2975, https://github.com/nspcc-dev/neofs-node/issues/2971.

object/put: fix concurrent PUT data corruption

---

CHANGELOG.md
cmd/neofs-node/config.go
cmd/neofs-node/main.go
cmd/neofs-node/metrics.go
pkg/metrics/engine.go

node: add metrics for shard's capacity

---

docs/cli-adm.md
docs/deploy.md
docs/maintenance.md
docs/sighup.md
docs/storage-node-configuration.md
docs/verified-node-domains.md

docs: rename `morph` to `fschain`

---

CHANGELOG.md
cmd/neofs-node/config/config.go

This is a check in case there is a ",remain" tag in the configuration field, and if there is an incorrect data format, then the value of the field was ignored, since then there will be a check to see if this field is correct or not. This makes some errors clearer after unmarshalling.
Closes #3034.
Actually, I don't like this fix. I want the attribute field to be a list.

node: add check for unmarshalling config to validate

---

CHANGELOG.md
pkg/services/object/put/streamer.go

raised in https://github.com/nspcc-dev/neofs-sdk-go/actions/runs/12164435066/job/33926084474#step:4:141

node/object: Fix Put op condition checking requests with copies number

---

CHANGELOG.md
pkg/innerring/innerring.go

Similar to 19c72bfe0b5d322e4de8019df5c1431af35ca5f6, but for IR.
We've got
neofs-ir[1394797]: warn        event/listener.go:248        listener worker pool drained        {"chain": "fschain", "capacity": 10}
in testnet.

ir: increase fschain pool size

---

cmd/neofs-node/config.go
cmd/neofs-node/netmap.go
cmd/neofs-node/reputation.go

node: init blockchain state on startup

---

CHANGELOG.md
cmd/neofs-ir/defaults.go

Now it is clear that the error is related to reading the config.

ir: improve error messages during configuration validation

---

CHANGELOG.md
pkg/morph/client/multi.go
pkg/morph/client/notifications.go

When the RPC connection is lost and a recovery attempt occurs, the variable `conn` responsible for the connection may be nil and therefore additional verification is needed.
I couldn't come up with a better solution, so I'm open to smart thoughts.
Closes #3061.

morph: fix nil pointer dereferencing to connection

---

pkg/local_object_storage/pilorama/forest_test.go

It disrupts, and it is decided not to fix it. No changes are expected to be done in the pilorama.

node/pilorama: supress flipping tree test

---

cmd/neofs-node/transport.go
pkg/core/client/client.go
pkg/local_object_storage/shard/gc_test.go
pkg/network/address.go
pkg/network/cache/multi.go
pkg/services/object/get/v2/util.go
pkg/services/object/internal/key.go
pkg/services/object/put/v2/service.go
pkg/services/object/put/v2/streamer.go
pkg/services/object/search/v2/util.go

one more cut from #3057, continues #3078

node: Use `github.com/nspcc-dev/neofs-api-go/v2` module less

---

CHANGELOG.md
cmd/neofs-ir/internal/validate/config.go
config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/internal/blockchain/blockchain.go

Add `KOL` and `RUB` neo-go parameters support

---

CHANGELOG.md
pkg/local_object_storage/engine/inhume.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/shard/gc.go
pkg/local_object_storage/shard/gc_test.go

Fix #3026.
For bug about expired objects that aren't deleted after locks expire, there's also a simpler solution - [here](https://github.com/nspcc-dev/neofs-node/blob/8b65833d3651185fd9078e36b5acac73b1eaf762/pkg/local_object_storage/shard/gc.go#L121) make it consistently: handle expired locks and then handle expired objects. But really I don't like this, because the parallelism in the calculations is lost, and the logic for deleting the locks may still be wrong.

Fix bugs with removing split objects

---

CHANGELOG.md
cmd/neofs-cli/modules/acl/extended/create.go
cmd/neofs-cli/modules/acl/extended/create_test.go
cmd/neofs-cli/modules/util/acl.go
docs/cli-commands/neofs-cli_acl_extended_create.md

cli/eacl: drop using public key targets in eACL tables

---

CHANGELOG.md
pkg/local_object_storage/engine/exists.go
pkg/metrics/engine.go

Fix `neofs_node_engine_list_containers_time_bucket` and `neofs_node_engine_exists_time_bucket` metrics.
Closes #3102.

Fix broken metrics

---

CHANGELOG.md
pkg/local_object_storage/blobstor/fstree/fstree.go
pkg/local_object_storage/writecache/delete.go
pkg/local_object_storage/writecache/migrate_test.go
pkg/local_object_storage/writecache/options.go
pkg/local_object_storage/writecache/put.go
pkg/local_object_storage/writecache/state.go
pkg/local_object_storage/writecache/storage.go
pkg/local_object_storage/writecache/writecache.go

Closes #3101.
> Keep object list in memory along with sizes (map address to size)
Why are we doing this? We don't use it anywhere, do we?
Also, I forgot to include tests for migration from #3091, so I did it here.

Change `WC` size estimations

---

cmd/neofs-node/netmap.go

The first heartbeat attempt after the node bootstrap can end up this way:
warn    neofs-node/netmap.go:189        can't send heartbeat tx {"error": "incorrect current network map status OFFLINE, restart recommended"
Which is not critical since the next one will succeed, but the root of the problem is _two_ asynchronous handlers started for a new epoch, one of them updating local node data and the other sending heartbeats. This problem existed even before nodeV2, but with the old heartbeat mechanism it wasn't visible.
I doubt we need two routines here, everything can be performed with a single one sequentially and correctly.

node: fix race between heartbeat and state updater

---

pkg/local_object_storage/metabase/containers.go
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/metadata_test.go
pkg/local_object_storage/metabase/put.go
pkg/local_object_storage/metabase/select.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/metabase/util_test.go

Store object metadata in metabases for SearchV2 service

---

CHANGELOG.md
cmd/neofs-node/object.go
pkg/core/object/metadata.go
pkg/core/object/metadata_test.go
pkg/local_object_storage/engine/select.go
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/shard/select.go
pkg/metrics/object.go
pkg/services/object/acl/v2/service.go
pkg/services/object/acl/v2/util.go
pkg/services/object/server.go
pkg/services/object/server_test.go

* based on and blocked by #3080

Serve `ObjectService.SearchV2` RPC

---

pkg/local_object_storage/metabase/VERSION.md
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/version.go
pkg/local_object_storage/metabase/version_test.go

* based on and blocked by #3124

Metabase migration for SearchV2

---

CHANGELOG.md
pkg/innerring/state.go
pkg/morph/client/notary.go
pkg/morph/event/rolemanagement/designate.go

The alphabetic key change event comes from the main chain with its hash, and when calculating vub, an error is returned because there is no hash in the fs chain. Ignore the error and calculate the value in another way.

Fix error from `CalculateNonceAndVUB`

---

CHANGELOG.md
pkg/innerring/processors/container/handlers.go
pkg/innerring/processors/container/process_announce_load.go
pkg/innerring/processors/container/processor.go
pkg/morph/client/container/load.go
pkg/morph/event/container/announce_load.go
pkg/morph/event/container/announce_load_notary.go

Closes #3129.
```
$ neo-go query tx --rpc-endpoint http://ir01.neofs.devenv:30333 -v fa93c36cad8ffdcce764c0446f2751d7203df1f1fea6e46973775afbe6b5f5ff
Hash:			fa93c36cad8ffdcce764c0446f2751d7203df1f1fea6e46973775afbe6b5f5ff
OnChain:		true
BlockHash:		f47c609369e5f5a49e9f1ea23422a14bea595e93856e403de3c0f6b2df5163bb
Success:		true
Signer:			Nb7aVeU98VySALvRo4mBfyVh59hHr5pZy8 (None)
Signer:			NfgHwwTi3wHAS8aFAN243C5vGbkYDpqLHP (WitnessScope(65))
Signer:			NPTmih9X14Y7xLvmD6RVtDHdH1Y9qJwoTe (WitnessScope(65))
Signer:			NRNp25VPHahL3umVxBcMLuEENGZR9cHxtc (None)
SystemFee:		0.4007524 GAS
NetworkFee:		0.3792789 GAS
Script:			DCECrJIM198LYbKJBy5rlG4tpOGjG5qxxiG7R14w+kqxAsMCsSIVAAwgw96yKzw10YleF8Z9YTY/SDE42F8J4pWnsTKq4Wm79lAUFMAfDBBwdXRDb250YWluZXJTaXplDBT9G8bLGk90cBmczNNgGoQo1gKSXUFifVtS
INDEX …
```

container: make `putContainerSize` method as notary request

---

CHANGELOG.md
pkg/local_object_storage/writecache/doc.go
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/flush_test.go
pkg/local_object_storage/writecache/get.go
pkg/local_object_storage/writecache/init.go
pkg/local_object_storage/writecache/iterate.go
pkg/local_object_storage/writecache/storage.go
pkg/local_object_storage/writecache/writecache.go

Closes #3077.
IIUC, the LRU cache was needed since the boltDB was processed in parallel and it was not safe to delete objects directly from there, but now only fstree and therefore it is no longer needed?

Delete objects from wc after flushing

---

cmd/neofs-node/meta.go
pkg/services/meta/meta.go
pkg/services/meta/notifications.go
pkg/services/meta/notifications_test.go

7b502637fbbe7fffc7b6ccaf3309c20a4ebde565 was incomplete, upon receiving a new container event the service still tries to handle it.

meta: do not try processing non-meta-enabled containers

---

pkg/services/meta/blocks.go
pkg/services/meta/meta.go
pkg/services/meta/notifications.go
pkg/services/meta/notifications_test.go

Subscribe for blocks only if there are containers with meta-on-chain enabled AND the current node is included in the placement. Closes #3175.

node/meta: do not keep block subscription without meta-containers

---

CHANGELOG.md
pkg/local_object_storage/writecache/writecache.go

Closes #3185.
I checked and in this case `encoder` is not nil.

writecache: make migration on init

---

CHANGELOG.md
cmd/neofs-ir/internal/validate/config.go
config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/internal/blockchain/blockchain.go

Make `P2PNotaryRequestPayloadPoolSize` configurable

---

CHANGELOG.md
pkg/morph/client/container/client.go
pkg/morph/client/container/list.go

Use iterators for container listings

---

CHANGELOG.md
pkg/morph/client/notary.go
pkg/morph/client/static.go

Add retries for `Invoke` function

---

CHANGELOG.md
cmd/neofs-ir/internal/validate/config.go
config/example/ir.yaml
pkg/innerring/config.go
pkg/innerring/config_test.go
pkg/innerring/internal/blockchain/blockchain.go

Make `MaxGasInvoke` configurable

---

CHANGELOG.md
pkg/innerring/internal/blockchain/blockchain.go

Follow NeoGo commit 3abddc78c0581c832a2754f21acf8215ee6e0f59 (https://github.com/nspcc-dev/neo-go/pull/3063) where ErrAlreadyExists was split into ErrAlreadyExists and ErrAlreadyInPool. Both are perfectly fine for this callback (transaction assembled and added into pool, nothing more to do).

ir: drop annoying "new transaction callback finished with error" log

---

.github/workflows/changelog.yml
.github/workflows/config-update.yml

It was recently compromised and even though changes to tags were reverted it's still worth upgrading (GH also warns about <=45.0.7).
I've checked this repository, we've not leaked anything since March 14 (the day of the attack).
See https://github.com/tj-actions/changed-files/issues/2463 also.

workflows: upgrade tj-actions/changed-files to v46

---

CHANGELOG.md
pkg/local_object_storage/writecache/flush.go
pkg/local_object_storage/writecache/flush_test.go
pkg/local_object_storage/writecache/writecache.go

Closes #3099.
Do I have to do this for every error, or just like now, if we can't write an object to the main storage?

writecache: retry flush after delay if an error is received

---

CHANGELOG.md
pkg/innerring/processors/netmap/process_peers.go

SNs on old networks with v1 node netmap send two bootstrap requests one after another, v1 and v2. But IR approves only one because of "updated" check:
neofs-ir[1458]: info        netmap/handlers.go:45        notification        {"type": "add peer"}
neofs-ir[1458]: info        netmap/handlers.go:64        notification        {"type": "add node"}
neofs-ir[1458]: info        netmap/process_peers.go:66        approving network map candidate        {"key": "03aeff8a19f0202090afb0916b1c00b432321be7e8623a06c9b9b5db8ee5c053a4"}
Even though the system works with the old map fine we can't switch to v2 because that map is either empty or has 1-2 node (sometimes v2 is approved before v1 due to concurrency).
This is a minimal fix to always approve correct v2 nodes, then after the switch we'll simplify …

netmap: always approve v2 node bootstrap

---

pkg/services/meta/containers.go
pkg/services/meta/containers_test.go
pkg/services/meta/notifications.go

Every epoch go through expiration attribute index and clean every non-locked object. Closes #3138.

meta: handle expired objects

---

CHANGELOG.md
pkg/local_object_storage/metabase/corruption_test.go
pkg/local_object_storage/metabase/delete.go

Objects that cannot be read are stuck forever if reading error prevents GC cycle from finish. Closes #3239.

metabase: if object is corrupted, clean up any possible data

---

pkg/services/meta/containers_test.go

ebf8f8b3f56347c4c1adb99e130f2749af6a6270 from #3241 had no lines conflicting with 7b730e476688a5e9f095417d3489a74f56adb574 from #3242, but in fact merging it broke tests.

meta: fix broken tests

---

pkg/innerring/processors/container/common.go

We've got test_static_session_token_container_delete failing after 4b7eee5c02938b9c2e84fe1e78a61f40581af4a4. This happens because deletion event has no real key and we're substituting it by the key used when container was created. It's an issuer key effectively, not a session key. And IMO this check is not very useful, we're checking signature against session-bound key anyway adn we trust this key because the token is issued by correct owner. The key from event is not very useful from the security perspective then.
The code extracting the key is moved as well because we can avoid decoding for the tokenized case.

ir: drop session key check

---

CHANGELOG.md
cmd/neofs-cli/modules/object/util.go
internal/crypto/common.go
internal/crypto/ecdsa.go
internal/crypto/errors.go
internal/crypto/tokens.go
internal/crypto/tokens_test.go
pkg/core/object/fmt.go
pkg/core/object/fmt_test.go
pkg/innerring/processors/container/common.go
pkg/services/container/server.go
pkg/services/container/server_test.go
pkg/services/object/acl/acl.go
pkg/services/object/acl/acl_test.go
pkg/services/object/acl/v2/errors.go
pkg/services/object/acl/v2/util.go

preparation for #3194. If we agree, i'll extend the approach to all signature verification cases in the system. With this, N3 account support will simply be an additional `case` in the `switch`

Refactor and improve verification of tokens' signatures

---

pkg/innerring/processors/container/common.go

An omission of 8968f55364eab0536b188bcc63900cc2085e1e2c, this part wasn't committed. The logic is the same since v.binPublicKey is not used with v.binTokenSession.

ir: don't extract the key when it's not needed

---

pkg/services/meta/blocks.go
pkg/services/meta/meta.go
pkg/services/meta/notifications.go
pkg/services/meta/notifications_test.go

Do not subscribe for containers additionally, use blocks as a single source of notifications. Now meta service is always in one of the two mutually exclusive state:
1. IDLE: subscribed to new containers event and not subscribed to blocks
2. ACTIVE: subscribed to blocks and not subscribed to new containers
Refs #3175, closes #3259.

meta: handle container events via blocks

---

pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/metadata.go

1. Cleanup new index based only on current new index's state
2. Keep actual stored objects' size based only on new index's state
3. Delete old indexes based on their old state, but do not involve them in new routines
Tests for counters and parent objects are based on PUT + DELETE operations, so they are actual for the new code too. Closes #3245.

metabase: GC objects using new searchV2 index

---

cmd/neofs-node/config.go
cmd/neofs-node/object.go

for #3194, smth definite should be done for this. I decided to trust the contract and drop verification. If we'll decide to keep the check, it should be globalized/deduplicated and refactored same as #3265

node: Do not verify signature of eACLs from the Container contract

---

pkg/innerring/innerring.go

The comments and method names do not match.
This pr fix function name in comment.

chore: fix function name in comment

---

CHANGELOG.md
cmd/peapod-to-fstree/main.go

Read actual containers from FS chain on start and skip objects whose containers are not in the actual list. In practice, it's going to save us a lot of time.

peapod-to-fstree: do not migrate objects without container

---

CHANGELOG.md
pkg/local_object_storage/metabase/metadata.go

`bytes.LastIndex` can be buggy in this case since filter's value _may_ have a zero byte in an object ID, checksum, etc. (any system header fields in other words). In particular, it closes #3277.

metabase: fix meta data cleaning

---

CHANGELOG.md
cmd/peapod-to-fstree/main.go

I don't know how to check it, but in theory it should work.

peapod-to-fstree: ignore corrupt objects without container

---

CHANGELOG.md
pkg/morph/client/notifications.go

If connection was lost quite fast after the previous reconnection, a separate restoration routine may decline `for`'s next reconnection iteration and lead to reconnection deadlock. Do not reuse restoration channel b/w iterations. Closes #3292.

morph/client: sync subs restoration with main notify cycle

---

CHANGELOG.md
cmd/neofs-cli/modules/accounting/balance.go

Regression of 9ac84e30c21:
can't decode owner ID wallet address: %!w(<nil>)

cli: fix --owner flag of accounting balance

---

CHANGELOG.md
pkg/local_object_storage/metabase/metadata.go

Next() can always return nil. Fixes
goroutine 8378 [running]:
github.com/nspcc-dev/neofs-node/pkg/local_object_storage/metabase.(*DB).searchUnfiltered.func1(0xc009167420)
github.com/nspcc-dev/neofs-node/pkg/local_object_storage/metabase/metadata.go:305 +0x4e8
go.etcd.io/bbolt.(*DB).View(0xc0001d5a00?, 0xc009222f38)
go.etcd.io/bbolt@v1.4.0/db.go:939 +0x6c
github.com/nspcc-dev/neofs-node/pkg/local_object_storage/metabase.(*DB).searchUnfiltered(0xc00148e030, {0xc0, 0xe6, 0xf5, 0xe7, 0x60, 0x1e, 0x7e, 0x28, 0xe0, ...}, ...)
github.com/nspcc-dev/neofs-node/pkg/local_object_storage/metabase/metadata.go:294 +0x156
github.com/nspcc-dev/neofs-node/pkg/local_object_storage/metabase.(*DB).Search(0x46fafd?, {0xc0, 0xe6, 0xf5, 0xe7, 0x60, 0x1e, 0x7e, 0x28, 0xe0, ...}, ...) …

metabase: fix NPE in metadata search

---

CHANGELOG.md
cmd/neofs-ir/validate_test.go
config/example/ir.yaml
go.mod
go.sum
pkg/innerring/config/fschain.go
pkg/innerring/config_test.go
pkg/innerring/internal/blockchain/blockchain.go

Adapt to the new TimePerBlock handling (it's a part of the Policy contract now),

go.mod: upgrade to NeoGo 0.109.0

---

CHANGELOG.md
cmd/neofs-node/object.go
pkg/services/object/server.go
pkg/services/object/tombstone/verify.go
pkg/services/object/tombstone/verify_test.go

Closes #3143.
I hope I understood correctly what exactly needs to be changed.

services/object: use SearchV2 for search objects

---

CHANGELOG.md
pkg/innerring/blocktimer.go
pkg/innerring/innerring.go
pkg/innerring/processors/settlement/basic/distribute.go
pkg/innerring/processors/settlement/calls.go
pkg/innerring/processors/settlement/events.go
pkg/innerring/processors/settlement/processor.go
pkg/innerring/settlement.go
pkg/morph/client/balance/transfer.go

Distribution is tightly related to collection and if we run them asynchronously we easily end up with
info	settlement/calls.go:54	start basic income collection	{"epoch": 5}
info	settlement/calls.go:99	start basic income distribution	{"epoch": 5}
info	basic/distribute.go:17	zero total size of all estimated containers, skip distribution of funds
Even though there are valid estimations:
debug	innerring/settlement.go:240	basic income: transfer was successfully sent	{"sender": "NPBzbkvZUcWjyMNmiQr8hXGg1E7jjHxkqe", "recipient": "NL1H4he1ggRajT1ZVqn23zveMRaH9jDvfh", "amount (GASe-12)": "1303851604461", "details": "410500000000000000"}

ir: unify basic income collection and distribution, fix #3338

---

CHANGELOG.md
cmd/neofs-node/grpc.go

finally https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3250-1747219312/index.html

node/grpc: Return to passthrough address resolution scheme

---

CHANGELOG.md
go.mod
go.sum

0.109.1 is out and we need it.

go.mod: upgrade to the latest and greatest NeoGo

---

pkg/services/object/server.go

1. When the first filter is EQ comparing values makes zero sense.
2. We've got a panic after 5249ab03a1f14e721d322cc0971e43a67abc18d1: panic: runtime error: index out of range [0] with length 0
goroutine 16844 [running]:
github.com/nspcc-dev/neofs-node/pkg/core/object.MergeSearchResults(0x3e8?, {0xc00927e300, 0x12}, 0x0, {0xc001deaa20, 0x4, 0x834923cc0a0b85cb?}, {0xc006bde668, 0x4, 0x8})
github.com/nspcc-dev/neofs-node/pkg/core/object/metadata.go:81 +0x110f
github.com/nspcc-dev/neofs-node/pkg/services/object.(*Server).ProcessSearch(0xc00020c420, {0x13dde30, 0xc003099b30}, 0xc0019232c0)
github.com/nspcc-dev/neofs-node/pkg/services/object/server.go:2048 +0xc53
github.com/nspcc-dev/neofs-node/pkg/services/object.(*Server).processSearchRequest(0xc00020c420, {0x13dde30, 0xc003099b30}, …

object: optimize search result merger for EQ case, fix #3347

---

CHANGELOG.md
pkg/innerring/processors/settlement/basic/collect.go

basic: skip basic income distribution if rate is 0

---

pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/writecache/writecache.go
pkg/services/session/storage/persistent/storage.go
pkg/util/state/storage.go

An omission of 2f878435915cfb4f0be03d0aad3cf46fe36b2510.

*: open bolt with no statistics

---

pkg/local_object_storage/metabase/bench_test.go

It's reminiscent of what we have in S3 gateway, some objects, a lot of attributes returned. Initial results suggest that it's good enough already:
cpu: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
BenchmarkSearch-16         65149             17728 ns/op
reducing the number of returned attributes to 1 doesn't change much, so not a problem either:
cpu: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
BenchmarkSearch-16         67246             17272 ns/op

metabase: add a simple search benchmark

---

CHANGELOG.md
pkg/local_object_storage/writecache/get.go
pkg/local_object_storage/writecache/state.go

We have a complete object list in memory, it's easy to check it. This should improve read performance for objects that are gone from write cache.

writecache: improve reads, don't check fstree is it's not needed

---

CHANGELOG.md
go.mod
go.sum

tx batching is updated to use 5% block time by default here. Connection management improved and Faun introduced.

go.mod: upgrade NeoGo to 0.110.0

---

CHANGELOG.md
go.mod
go.sum
pkg/services/object/server.go

* based on and blocked by https://github.com/nspcc-dev/neofs-sdk-go/pull/719
tested S3 and REST GWs require signatures to be presented. Passed tests assert proposed behavior is backward compatible. Note that clients which do _not_ set API version are also served with signatures

Support unsigned object GET/HEAD responses

---

pkg/local_object_storage/metabase/graveyard.go
pkg/morph/client/notary.go
pkg/services/object/internal/client/client.go
pkg/services/object/server.go

In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.

refactor: use the built-in max/min to simplify the code

---

pkg/services/control/types.pb.go
pkg/services/control/types.proto

improved wording and consistency in code:
`administative` - `administrative`

minor text cleanup

---

pkg/local_object_storage/blobstor/fstree/bench_test.go
pkg/local_object_storage/blobstor/fstree/common_test.go
pkg/local_object_storage/blobstor/fstree/head_bench_test.go
pkg/local_object_storage/blobstor/fstree/head_test.go
pkg/local_object_storage/blobstor/fstree/range_bench_test.go

Add more tests for FSTree

---

.github/workflows/build.yml

The only thing it does in PR is ensures that Docker images can be built, they're not pushed into any registry, so they can't be used and no one needs the result. Building in master is sufficient for the purpose of finding failed Docker builds (they don't break often), but we better avoid doing it in PRs since it takes a considerable amount of time blocking runners available to project/organization.

workflows: don't build Dockers in PRs

---

CHANGELOG.md
internal/crypto/n3.go

It requires to compensate BlockHeight behaviour with persisting block. Details in row 538 https://github.com/nspcc-dev/neo-go/blob/44d7da54f41ce82d852cf7320d6ed00fb3c1eb96/pkg/core/interop/context.go#L528-L544

Fake persisted block

---

CHANGELOG.md
pkg/local_object_storage/metabase/version.go
pkg/local_object_storage/metabase/version_test.go

It corresponds to 0.44.0 release, I don't think there is anyone running pre-0.44.0 now and this code has inhumeV2() is tests which is ugly as hell and not easy to maintain.

metabase: drop 2->3 migration

---

CHANGELOG.md
pkg/local_object_storage/engine/revive_test.go
pkg/local_object_storage/metabase/put_test.go
pkg/local_object_storage/metabase/revive.go
pkg/local_object_storage/metabase/revive_test.go
pkg/local_object_storage/shard/put_test.go
pkg/local_object_storage/shard/revive.go

Closes #3486.
Now, if you revive an object on a specific node, then it can only be retrieved on it. It will still be unavailable on other nodes. And the tombstone object is physically deleted only if it was in that node. Is this the right logic?

Fix tomstoned objects revival not working

---

CHANGELOG.md
pkg/morph/client/container/client.go

An attempt to list 2K+ containers ended up this way:
error	handler/util.go:34	call method	{"status": 500, "request_id": "0cedec2b-935d-4575-a0c2-94ed4650c978", "method": "ListBuckets", "bucket": "", "object": "", "description": "something went wrong", "error": "list user containers via connection pool: status: code = 1024 message = json error: too big: size"}
We're trying to get 2K items from the iterator in a single call, each item is base64 of CID, so it's 42 bytes, but then it's wrapped into VM type/value struct like this:
{"value":"","type":"ByteString"}
which adds another 32 bytes. For 2K elements this yields 144K JSON (not including other data which is also present) which NeoGo refuses to return given that the maximum size is 128K (https://github.com/nspcc-dev/neo-go/pull/3185). …

container: reduce the number of fetched iterator items

---

CHANGELOG.md
pkg/services/object/get/assemble.go
pkg/services/object/get/assembly_v2.go
pkg/services/object/get/exec.go
pkg/services/object/get/get_test.go
pkg/services/object/get/local.go
pkg/services/object/get/remote.go
pkg/services/object/get/service.go
pkg/services/object/get/util.go

services/object: use stream API for `Get` operation

---

CHANGELOG.md
pkg/local_object_storage/metabase/VERSION.md
pkg/local_object_storage/metabase/containers.go
pkg/local_object_storage/metabase/control.go
pkg/local_object_storage/metabase/counter.go
pkg/local_object_storage/metabase/delete.go
pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/graveyard.go
pkg/local_object_storage/metabase/inhume.go
pkg/local_object_storage/metabase/list.go
pkg/local_object_storage/metabase/metadata.go
pkg/local_object_storage/metabase/revive.go
pkg/local_object_storage/metabase/status.go
pkg/local_object_storage/metabase/status_test.go
pkg/local_object_storage/metabase/util.go
pkg/local_object_storage/metabase/version.go
pkg/local_object_storage/metabase/version_test.go

metabase: use meta bucket to mark containers with GC

---

pkg/innerring/nns.go
pkg/innerring/processors/netmap/nodevalidation/privatedomains/validator_test.go
pkg/network/group.go
pkg/services/object/acl/v2/util_test.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code

---

CHANGELOG.md
pkg/local_object_storage/metabase/exists.go
pkg/local_object_storage/metabase/lock.go
pkg/local_object_storage/metabase/lock_test.go

When checking the lock bucket, it now checks whether the lock has expired or not.

meta: fix expired lock still locked the object

---

pkg/services/object/put/distributed.go

Placement vectors must be the same length, but signatures should be cleaned up correctly. Problem was added in a9202b1c6b8776beb2ff8276144d7bb947934e00.

node/objectsvc: clean up signatures correctly

---

cmd/neofs-node/object.go
go.mod
go.sum
pkg/innerring/processors/settlement/calls.go
pkg/morph/client/container/load.go

e2ff883a39997b2f87082c790773b8042889c31f was used. Container space loads have no epoch args anymore.

*: update contracts

---

CHANGELOG.md
pkg/local_object_storage/engine/evacuate_test.go

engine: fix flaky shard evacuate test

---

pkg/morph/client/container/load.go

It has an additional field now after https://github.com/nspcc-dev/neofs-contract/pull/517.

morph: fix parsing container load reports

---

CHANGELOG.md
cmd/neofs-cli/internal/key/raw.go
cmd/neofs-cli/modules/container/list.go
cmd/neofs-node/container.go
docs/cli-commands/neofs-cli_container_list.md
pkg/services/container/server.go

`neofs cli container list` lists nothing
